### ISSUE TITLE
Allow Edits in Wiki?

### ISSUE THREAD

**Issue by nathancolgate** [TrestleAdmin/trestle#101]
Our team really enjoys Trestle, so first: a big thanks for the tool.

One frustration we have is the lack of documentation, so we dig around in the code a bunch, which is fine.

But it would be really neat if we could add our findings to the wiki, similar to [CarrierWave](https://github.com/carrierwaveuploader/carrierwave/wiki).

Just a thought!

**Comment by spohlenz** [comment]
This is a good idea, thanks! I've just enabled public write access to the wiki.

It will also give me a good idea of what I should cover in the official documentation.
