### ISSUE TITLE
current_user undefined in collection?

### ISSUE THREAD

**Issue by mzdz** [TrestleAdmin/trestle#102]
```
Trestle.resource(:products) do
   collection do
      Product.all
   end
  
    #use trestle-search gem
    search do |query|
          query ? collection.where("name like ?", "%#{query}%") : collection
     end
   
end

```
it work, but:

```
Trestle.resource(:products) do
     collection do
        #use trestle-auth gem
        current_user.products
    end
     
      #use trestle-search gem
      search do |query|
          query ? collection.where("name like ?", "%#{query}%") : collection
     end
end
```
throw error: 
   NameError - undefined local variable or method `current_user'

**Comment by spohlenz** [comment]
The `collection` block currently executes within the scope of the Resource class. This is definitely something I need to correct, as your use case highlights.

I'm not sure yet exactly how I will solve it, since the default collection block implementation relies on resource methods such as `model`. It may be that I add the controller as an additional optional parameter to the collection block, although it would be nice to be able to make all adapter method executions consistent (the params is one exception that currently executes within the controller scope).

**Comment by cpunion** [comment]
@spohlenz Other cases includes menu navigation visible, enable actions or making readonly by administrators' role, etc.

**Comment by hudsonsza** [comment]
When I need to work with params I use the controller and make changes in the self.collection method

I believe this is what @spohlenz said
@mzdz example of use:
```
 controller do
    def index
      _collection = admin.prepare_collection(params)
      self.collection = current_user.is_admin? ? _collection : _collection.where(user_id: current_user.id)

      respond_to do |format|
        format.html
        format.json { render json: collection }
      end
    end
  end
```

**Comment by okliv** [comment]
is somehow possible for now to vary table structure based on current_user?

```ruby
table do 
    column :total, if: -> { current_user.financial_officer? }
end
```

**Comment by jfrux** [comment]
this is🙁

**Comment by spohlenz** [comment]
A solution for this is very close to being ready. I've gone through a number of iterations and am finally converging on something I am happy with. I was hoping to have it ready today which is now looking unlikely, but the next day or two is realistic.

**Comment by spohlenz** [comment]
This is now supported in `master`. It's a relatively large change to the way adapters work (although it is intended to be backwards-compatible) so I would appreciate it if you could give it a test run and let me know if there are any issues. If you are using `trestle-search` you may need to update to `master` also.

The following situations are now supported:

**1.** Referencing controller methods (such as `current_user`, `request`, etc) from within a `collection` or other override block. e.g.

```ruby
Trestle.resource(:articles) do
  collection do
    current_user.articles
  end

  build_instance do |attrs|
    current_user.articles.build(attrs)
  end
end
```

**2.** Toggling table columns using `:if`/`:unless` options (@okliv):

```ruby
table do 
  column :total, if: -> { current_user.financial_officer? }
end
```

**3.** Toggling navigation items using `:if`/`:unless` options (@cpunion):

```ruby
menu do
  item :users, if: -> { current_user.administrator? }
end
```

Enabling/disabling actions or readonly status based on a proc is not yet implemented. These problems I will have to solve in a different way (in `trestle-auth`) but will be on my list very soon.

**Comment by jfrux** [comment]
So awesome man, you rock.
Thank you. Still trying to find my groove and where I think makes the most sense for where I can contribute. I’ll find it soon.

--
Joshua F. Rountree | UX Developer
The E.W. Scripps Company
312 Walnut Street, Suite 2800, Floor 29th, Office 29W109
Cincinnati, Ohio 45202-4024
(513) 977-3840 (office, M-F, 7a-4p)
(513) 827-7936 (mobile)
