### ISSUE TITLE
Documentation about custom table actions

### ISSUE THREAD

**Issue by sbusso** [TrestleAdmin/trestle#104]
There is documentation about adding custom actions to admin but not how to add it to a table view. Is it the right way ?

```ruby
table do
    actions do |a|
      a.button icon("fa fa-check"), a.instance, action: :validate, method: :post, class: "btn btn-primary" if a.instance.pending?
      a.delete
    end
end
```

**Comment by cpunion** [comment]
I guess you are right. Learned and updated my code, much better now.

Thanks!

**Comment by spohlenz** [comment]
Whilst this will continue to work (at least for now), here is the recommended way to do this using the new toolbars API in `trestle` 0.8.10:

```ruby
table do
  actions do |a|
    a.link "Validate", a.instance, action: :validate, method: :post, style: :primary, icon: "fa fa-check" if a.instance.pending?
    a.delete
  end
end
```

**Comment by coezbek** [comment]
What I don't understand in this example is that by doing a `table do` you lose all the automatic columns. How to add an action but keep the standard columns?
