### ISSUE TITLE
Select Collection From Helper

### ISSUE THREAD

**Issue by ariefrizkyr** [TrestleAdmin/trestle#105]
I have select field in my admin resource and I have the category list in my `application_helper.rb` . I want to have the select field to load the category listed in my helper. How to achieve it? Thanks!

```
# application_helper.rb

def category_list
   ["Category 1", "Category 2"] 
end
```

```
form do |article|
    row do
        select :category
    end
end
```

**Comment by spohlenz** [comment]
The second argument to the `select` field helper is the list of options, so you can pass it in directly:

```ruby
form do |article|
  row do
    select :category, category_list
  end
end
```

In order to access the helper methods, you will need to specify the helper in either the admin:

```ruby
Trestle.resource(:articles) do
  helper ApplicationHelper

  form do |article|
    ...
  end
end
```

or globally within `config/initializers/trestle.rb`:

```ruby
Trestle.configure do |config|
  config.helper ApplicationHelper
end
```
