### ISSUE TITLE
[doubt] How get results of table in the view index?

### ISSUE THREAD

**Issue by patybastos** [TrestleAdmin/trestle#106]
Hi @spohlenz, I want to use `search` in the results of table in the index view. My collection have one scope, e.g.:
```ruby
  collection do |params|
    Event
        .find_by(generated_sku: params[:id])
        .attendees.eligible_for_attending
  end
```

and in the search, i do:
```ruby
  search do |query|
    collection.search(query)
  end
```

But in the search, when i call collection, I don't have more the `params`. Is there no way to do this?

<img width="721" alt="captura de tela 2018-04-24 as 19 12 22" src="https://user-images.githubusercontent.com/5859987/39216800-7cb26d52-47f3-11e8-8d46-95afc4191d30.png">

**Comment by svoboda-jan** [comment]
It doesn't seem to be possible now, but if you only need to include the ID, there is a workaround:

Override the search partial (create a file `app/views/trestle/search/_search.html.erb`):

```erb
<% if defined?(admin) && admin.respond_to?(:searchable?) && admin.searchable? -%>
  <div class="searchbox">
    <%= form_tag admin.path(nil, id: params[:id]), method: :get do %>
      <%= hidden_field_tag :id, params[:id] %>
      <div class="input-group">
        <span class="input-group-addon"><icon class="fa fa-search"></icon></span>
        <%= text_field_tag :q, params[:q], class: "form-control", placeholder: t("admin.search.placeholder", default: "Search") %>
      </div>
    <% end %>
  </div>
<% end -%>

```

And update the search block:

```ruby
search do |query, params|
  Event
    .find_by(generated_sku: params[:id])
    .attendees.eligible_for_attending
    .search(query)
end
```

**Comment by spohlenz** [comment]
As @svoboda-jan demonstrates, the params are passed in as the second parameter to the `search` block so you can then pass that on to the collection block:

```ruby
search do |query, params|
  collection(params).search(query)
end
```

As for the `id` param, you might wish to try adding it to the `config.persistent_params` list (if you haven't already) which will ensure that it is passed through to search, sorts, pagination, etc.

In `config/initializers/trestle.rb`:

```ruby
config.persistent_params << :id
```

**Comment by patybastos** [comment]
Oh ok, thank you @svoboda-jan and @spohlenz.
