### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by richardvenneman** [TrestleAdmin/trestle#11]
First of all thanks for this great library. Fantastic onboarding experience!

Is there any recommended approach for [ActiveRecord enums](http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html) in forms? Ideally I'd like to have a select box with the possible values and the selected value pre-selected. I tried the `select` helper as well as `collection_radio_buttons` but couldn't get the actual value to pre-select.

```ruby
# app/models/booking.rb
class Booking < ApplicationRecord
  enum status: {
    initiated: 0,
    requested: 1,
    accepted: 2,
    rejected: 3,
    cancelled: 4
  }
end

# app/admin/bookings_admin.rb
...

form do |booking|
  select :status, choices: Booking.statuses.to_a, selected: booking.status
end
```

While the form component code looks really clear I couldn't figure out how to create a custom type, otherwise I would have issued a PR directly!

**Comment by spohlenz** [comment]
Hi @richardvenneman. The following should do the trick:

```ruby
form do |booking|
  select :status, Booking.statuses.keys.map { |status| [status.humanize, status] }
end
```

The `.map` is technically optional but makes the UX a little nicer.

**Comment by richardvenneman** [comment]
Thanks for the quick reply! Great stuff, this works perfect! 🍺
