### ISSUE TITLE
How to apply sort?

### ISSUE THREAD

**Issue by hopewise** [TrestleAdmin/trestle#115]
I could not find how to set sort order using specific column? ex: updated_at, descending ..

**Comment by spohlenz** [comment]
The documentation is definitely lacking still, but here's a round-up of what you can do with regards to sorting...

By default most columns that aren't defined with a block are sortable by the column name. If the column name doesn't map to a database column, or you have defined a custom block, you can set the sort field with the `:sort` option:

```ruby
column :name, sort: :name_column
# or
column :name, sort: { field: :name_column }
```

You can set the default sort order (the order to use when you initially click on the sort icon) using the `sort: { default_order: }` option (default is `:asc`):

```ruby
column :name, sort: { default_order: :desc }
```

If you are already applying some default sorting in the collection block (e.g. `order(created_at: :desc)` or similar), you can specify that column as the default sorted column:

```ruby
column :created_at, sort: { default: true, default_order: :desc }
```

Custom column sorts can be defined using the `sort_column` method (within the admin block, not the table block). This is particularly useful when doing advanced sorting, e.g. applying a `NULLS LAST` or similar. The `order` block param is sanitized to be either `:asc` or `:desc`.

```ruby
sort_column(:name) do |collection, order|
  collection.reorder("name #{order} NULLS LAST")
end
```

**Comment by hopewise** [comment]
Thanks, but where to put the `column :updated_at, sort: { default: true, default_order: :desc }` ? I could not within the `Trestle::Resource::Builder`

**Comment by spohlenz** [comment]
The `column` definitions go within a `table` block. e.g.

```ruby
Trestle.resource(:articles) do
  table do
    column :updated_at, sort: { default: true, default_order: :desc }
  end
end
```

**Comment by hopewise** [comment]
Thanks, but it seems that its always `: asc` even if I set `default_order: :desc`

**Comment by spohlenz** [comment]
Here's a more complete example. I hope it clears things up a little.

```ruby
Trestle.resource(:articles) do
  collection do
    # Set the default order when manual sorting is not applied
    Article.order(created_at: :desc)
  end

  table do
    # When the index is first loaded, we will not be sorting by title (so the sort icon shows as the lines).
    # After clicking the sort icon once, the collection will be reordered in ascending order by the title field.
    # After clicking the sort icon a second time, the collection will be reordered in descending order.
    # Strictly speaking, setting `default_order` to `:asc` here is unnecessary as that is the default.
    column :title, sort: { default_order: :asc }

    # When the index is first loaded, we will be sorting by updated_at (since it is set in the `collection` block above),
    # and since default is true, the sort icon is shown as the down arrow. (Note that the `default_order` option
    # here doesn't actually reorder the collection -- it just sets what order to use when first ordering by that field)
    # After clicking the sort icon once, the collection will be reversed and shown in ascending order.
    column :updated_at, sort: { default: true, default_order: :desc }
  end
end
```

**Comment by JonCrawford** [comment]
Can you apply sorts to column tab views? I have the following column and it doesn't seem to work.

```ruby
column :sale_amount, align: :center, sort: { field: :sale_amount_cents } do |purchase|
  purchase.sale_amount.format
end
```

**Comment by basharabdullah** [comment]
Sorry, opening this again. Is this code still valid? I tried and it doesn't give error, but doesn't sort either

```
  collection do
    Job.order(created_at: :desc)
  end
```

**Comment by quantavi** [comment]
> Sorry, opening this again. Is this code still valid? I tried and it doesn't give error, but doesn't sort either
> 
> ```
>   collection do
>     Job.order(created_at: :desc)
>   end
> ```

Maybe try this instead:
```
collection do
  model.order(created_at: :desc)
end
```

I have checked it in Trestle 0.9.3 and it works

**Comment by basharabdullah** [comment]
@quantavi Thanks for the followup. It is working now, but unfortunately I do not remember what got it to work. 

I'm at 0.9.2 now. Should have remembered to update here. Sorry

**Comment by biancajemsten** [comment]
Does anyone have a solution for the scenario @JonCrawford mentioned? I can't seem to get sort working for tables that are in a tab view.

**Comment by quantavi** [comment]
> Does anyone have a solution for the scenario @JonCrawford mentioned? I can't seem to get sort working for tables that are in a tab view.

Could you share a screenshot and maybe a part of admin file? I am not sure what do you mean by 'a tab view'

**Comment by biancajemsten** [comment]
> > Does anyone have a solution for the scenario @JonCrawford mentioned? I can't seem to get sort working for tables that are in a tab view.
> 
> Could you share a screenshot and maybe a part of admin file? I am not sure what do you mean by 'a tab view'

Yes of course. Here's a screenshot of it. Thank you for looking into it!
 
![image](https://user-images.githubusercontent.com/37228766/103556137-9cb1ad80-4eb1-11eb-8fad-b3a288e4576a.png)

**Comment by quantavi** [comment]
@biancajemsten Are you using similar code to this to render the table under the tab?
```ruby
    tab :newsletter_subscribers, label: "Subskrybenci", badge: investment.newsletter_subscribers.size do
      render "newsletter_subscribers", newsletter_subscribers: investment.newsletter_subscribers.per_page_kaminari(1) unless investment.newsletter_subscribers.nil? || investment.newsletter_subscribers.empty?
    end
```
and in _newsletter_subscribers.html.erb:
```ruby
<div data-context="<%= admin.instance_path(instance, action: :newsletter_subscribers, page: params[:page]) %>">
  <%= table NewsletterSubscribersAdmin.tables[:subscriber], collection: newsletter_subscribers %>

  <footer class="main-content-footer">
    <%= pagination collection: newsletter_subscribers, entry_name: NewsletterSubscribersAdmin.model_name, remote: true, params: { action: :newsletter_subscribers } %>
  </footer>
</div>
```

and in newsletter_admin.rb:
```ruby
Trestle.resource(:newsletter_subscribers) do
  table :subscriber do
    column :id, sort: { default_order: :asc }
    column :email
  end
end
```

Unfortunately, it looks like we have the same problem in this project, but bigger. For some reason, we are missing sort option for any column. It is perhaps fallout after monkey-patching. If you doing this in a different way, maybe this will work for you. 

BTW. Anyone had an issue, where sorting disappeared all together in Trestle?

**Comment by biancajemsten** [comment]
@quantavi  We have something more along the lines of: 
companies_admin.rb:
```
tab :record_queries do 
   table Company::RecordQueriesAdmin.table, collection: company.record_queries
end
```

and in company/record_queries_admin.rb:
```
Trestle.resource :record_queries, scope: Company, model: RecordsQuery do
   table do
       column :label
       ...
   end
end
```

I've tried using all of the suggestions mentioned in this thread but unfortunately none of them work :(
