### ISSUE TITLE
How to set column width percentage?

### ISSUE THREAD

**Issue by hopewise** [TrestleAdmin/trestle#117]
Is there an easy way to set width percentage or class of a column  in table using the resource admin ?

**Comment by spohlenz** [comment]
You can set the class of a column using the `:class` option, and then set the width via CSS.

e.g. in your admin

```ruby
table do
  column :name, class: "name-col"
end
```

and in `app/assets/stylesheets/trestle/_custom.scss`:

```scss
.name-col {
  width: 25%;
}
```
