### ISSUE TITLE
how can remove create action on header 

### ISSUE THREAD

**Issue by hrz3424** [TrestleAdmin/trestle#119]

**Comment by spohlenz** [comment]
You can remove the button by removing the corresponding `new` action. e.g.

```ruby
Trestle.resource(:articles) do
  remove_action :new
end
```

If you want to keep the `new` action whilst removing the button, you'll need to copy and edit the index template from https://github.com/TrestleAdmin/trestle/blob/master/app/views/trestle/resource/index.html.erb.

I'm hoping to make customizing the toolbars easier in future, but need to complete the custom actions API first.

**Comment by swrobel** [comment]
@spohlenz has this changed with the 0.9 release?
