### ISSUE TITLE
Rails dependency

### ISSUE THREAD

**Issue by matthewd** [TrestleAdmin/trestle#12]
You should depend on `railties` rather than `rails`, so you won't force extra frameworks onto people who've skipped them. That does then imply you should also depend on any additional frameworks you do actually require.. but at a brief glance, there may not be any?

(Note `rails` itself is completely empty: it is nothing but a list of default dependencies. The interesting bits are all in `railties`, so you're not missing out on anything by doing this.)

**Comment by spohlenz** [comment]
Thank you. ActiveModel might become a required dependency once I resolve the issues in #2, but will add that in when it is necessary.

**Comment by matthewd** [comment]
Probably worth checking whether you need sass-rails too... I can't advise on that, because I don't immediately recall what it brings to the table. But sprockets has built-in support for `.scss` files: that gem adds a couple of (IIRC) rarely used features.
