### ISSUE TITLE
Change table and form column name

### ISSUE THREAD

**Issue by staroflead** [TrestleAdmin/trestle#124]
Can I change column name in table index and form? 
Edit: i figured out that using label for form I could change the input label. Still doesn't work out for index table.
Edit2: ok, I found out how to use different column name for index. But the left sidebar items must be changed via translation, crmiiw.

**Comment by spohlenz** [comment]
As it looks like you've found, table column headers can be altered using the `:header` option:

```ruby
column :title, header: "Custom Header"
```

Form field labels can be altered using the `:label` option:

```ruby
text_field :title, label: "Custom Label"
```

and navigation items can be altered using the `:label` option also:

```ruby
item :articles, label: "My Articles"
```
