### ISSUE TITLE
Date_field min max date

### ISSUE THREAD

**Issue by staroflead** [TrestleAdmin/trestle#125]
Can you tell me how can I set max/ min date for date_field? I see that the lib flatpickr is being used. Is it the only way to archive this goal by adding a partial with js code?

**Comment by spohlenz** [comment]
You can use the data options to set the minDate and maxDate (and other flatpickr options):

```ruby
datetime_field :published_at, data: { picker: true, min_date: 5.days.ago, max_date: 1.week.from_now }
```

Note that the `picker: true` option is currently required but is something I intend to fix.

**Comment by staroflead** [comment]
how can I use the option `time_24hr:true` for flatpickr ?

**Comment by spohlenz** [comment]
This is a bit quirky since Rails automatically converts underscores in data options to dashes, and Flatpickr appears to require the underscore:

```ruby
datetime_field :published_at, "data-time_24hr": true
```
