### ISSUE TITLE
Update model attribute from index page?

### ISSUE THREAD

**Issue by hopewise** [TrestleAdmin/trestle#127]
How would it possible to view checkbox for boolean attribute type of a model and link it to Ajax request that would update the attribute without having to click on row, edit and save? (while still at index page)

That would make it much more practical for admins..

**Comment by spohlenz** [comment]
Here's a really quick example of how to achieve this. It's fairly basic, and you'd probably want to customize it further to add in a loading state. I'm sure it could be improved in other ways too.

I'll use an example of features that can be enabled or disabled.

In your resource table:

```ruby
table do
  column :name
  column :enabled?, align: :center do |instance|
    trestle_form_for(instance, url: admin.instance_path(instance, action: :update), data: { behavior: "live-checkbox" }) do |f|
      f.check_box :enabled
    end
  end
end
```

and in `app/assets/javascripts/trestle/custom.js`:

```js
$(document).on('click', '[data-behavior="live-checkbox"]', function(e) {
  e.stopPropagation();

  $.ajax({
    type: "POST",
    url: $(this).attr('action'),
    data: $(this).serialize(),
    dataType: "script"
  });
});
```
