### ISSUE TITLE
How to hook up namespaced resource?

### ISSUE THREAD

**Issue by kevinelliott** [TrestleAdmin/trestle#128]
I'm trying to manage a resource that is in a namespace. How do we hook that up? So far, all syntax I see only allows for a symbol, but not a full class path. I have already searched past issues and pull requests and it was not clear if this was possible.

**Comment by spohlenz** [comment]
You can pass the `:scope` option to set the admin namespace. e.g.

`app/admin/scoped/my_resources_admin.rb`
```
Trestle.resource(:my_resources, scope: Scoped) do
  ...
end
```

This example will automatically use the model `Scoped::MyResource` with the path `/admin/scoped/my_resources` but you can override these with the `:model` and `:path` options respectively.

**Comment by hoangnv2107** [comment]
Hi Mr @spohlenz in this case, how do i use search with "Trestle.resource(:my_resources, scope: Scoped)". Thanks you very much
