### ISSUE TITLE
Custom actions

### ISSUE THREAD

**Issue by richardvenneman** [TrestleAdmin/trestle#13]
I've almost ported over most of our rails_admin panels (which was very easy to do!) except for some custom actions. I would like to show a form section which can trigger a custom controller action other than updating the model instance.

Reading the source I couldn't find any methods to do this. Should I just link to a controller outside of Trestle, or is there a recommended approach to do this? E.g. we currently have an action like this:

```erb
<h4>Send update</h4>
<textarea name="body" rows="4" cols="40"></textarea><br>
<button name="commit" type="submit" value="update" class="btn btn-primary"><i class="icon-envelope icon-white"></i> Send update</button>
```

```ruby
module RailsAdmin
  module Config
    module Actions
      class Updates < RailsAdmin::Config::Actions::Base

        ...

        register_instance_option :controller do
          proc do
            if params[:commit] == 'update'
              email = ::Emails::UpdatedEmail.new(@object)
              email.body = params[:body]
              email.send

              flash[:success] = 'Update successfully sent'
            end
          end
        end
      end
    end
  end
end
```

**Comment by spohlenz** [comment]
I'm planning a proper DSL for custom actions, including support for batch actions and modals. However in the mean time, you can drop down an abstraction layer to define your actions and routes within the admin:

```ruby
Trestle.resource(...) do
  form do |instance|
    ...

    toolbar(:secondary) do
      link_to "Send Email Update", admin.path(:email_update, id: instance.id), method: :post, class: "btn btn-info"
    end
  end

  controller do
    def email_update
      self.instance = admin.find_instance(params)

      # email = ::Emails::UpdatedEmail.new(instance)
      # email.body = params[:body]
      # email.send

      flash[:message] = "Email successfully sent"
      redirect_to admin.path(:show, id: instance)
    end
  end

  routes do
    # Routes are declared as if they are within the resources routing block
    post :email_update, on: :member
  end
end
```

You should be able to follow this pattern to add in an interstitial page for the email content (although you'll likely need to define a custom view template).

**Comment by richardvenneman** [comment]
Great! I just implemented this for some of our emails and it was actually very easy to do. I ended up adding a translation and using the `flash_message` helper:

```ruby
flash[:message] = flash_message('success.email_update')
```

With a view added in `app/views/admin/businesses/emails.html.erb`:

```erb
<% title = t("admin.titles.emails", default: "%{model_name} Emails", model_name: admin.model_name, pluralized_model_name: admin.model_name.pluralize) %>

<% content_for(:title, title) %>
<% breadcrumb instance.name, admin.path(:show, id: instance) %>
<% breadcrumb title %>

<%= render layout: 'layout' do %>
  <%= trestle_form_for instance, url: admin.path(:emails, id: admin.to_param(instance)), method: :get do %>
    <button name="commit" type="submit" value="invite" class="btn btn-primary">Invite</button>
    <button name="commit" type="submit" value="password_reset" class="btn btn-primary">Password reset</button>
  <% end %>
<% end %>
```

**Comment by richardvenneman** [comment]
For anyone reading this, I had to add a guard clause for the toolbar link rendering to support the "new" action:

```ruby
unless instance.new_record?
  toolbar(:secondary) do
    link_to admin.path(:emails, id: instance.id), method: :get, class: 'btn btn-info' do
      tag.i ' Emails ', class: 'fa fa-envelope'
    end
  end
end
```

**Comment by jfrux** [comment]
Can we have a route that doesn't require the instance id?
like `/my_admin_path/query_something` and render json?

Or do we just do that in a different controller somewhere?

**Comment by krtschmr** [comment]
googling this, ended up here.
is there already an official support for it? the demo code doesn't leave a hint

**Comment by spohlenz** [comment]
@krtschmr The example in [my comment above](https://github.com/TrestleAdmin/trestle/issues/13#issuecomment-321707155) is still the best way to do custom actions.

Some recent additions though are support for toolbar hooks, to make it easier to add buttons to the index view, as well as batch actions to apply actions to multiple rows via checkbox selection. You can see a basic example of both those in the sandbox code [here](https://github.com/TrestleAdmin/trestle/blob/main/sandbox/app/admin/articles_admin.rb#L15-L20).

A custom actions DSL is still coming (many years later admittedly). Now that I have completed an overhaul of the front-end, I am revisiting the internals and rebuilding momentum on the project.
