### ISSUE TITLE
undefined method `start_with?' for #<Regexp:0x00007f99920c7eb0>

### ISSUE THREAD

**Issue by daniyalhussain** [TrestleAdmin/trestle#132]
Hi there,

I just setup trestle.
I followed these 2 steps:

 `$ rails generate trestle:install
$ rails generate trestle:resource Customer
`

when i visited the http://localhost:3000/admin. I get the error undefined method `start_with?' for #<Regexp:0x00007f99920c7eb0>.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/5901712/43046148-9eb9614a-8dc5-11e8-9a1f-7e53c85968ae.png)

**Comment by spohlenz** [comment]
Thank you for the report. This should now be fixed in 406c391.
