### ISSUE TITLE
undefined method `output_buffer=' for Trestle::Form instance

### ISSUE THREAD

**Issue by cpunion** [TrestleAdmin/trestle#135]
I used `content_tag` in `static_field`:

```ruby
    static_field 'video_preview' do
      content_tag(:div, align: "center", class: "video embed-responsive embed-responsive-4by3") do
        video_tag video.play_url, controls: true, poster: video.cover_url
      end
    end
```

It raised an error:

```
undefined method `output_buffer=' for #<Trestle::Form::Builder:0x007fb7dca1d3d0>
```

This code worked for months ago. Currently, I am using `rails@5.2.0` and `trestle@0.8.9`. I tried to rollback to `rails@5.2.0.beta.1`, and `trestle@0.8.7`, but still can work.

It works in the following:

```
    static_field 'video_preview' do
      video_tag video.play_url, controls: true, poster: video.cover_url
    end
```

So seems just `content_tag` can work within that.

**Comment by spohlenz** [comment]
This seems like it is likely related to #107 but I unfortunately haven't been able to replicate either on my end. Are you able to upload a test application to GitHub that exhibits the issue? That would help immensely in tracking this down.

**Comment by cpunion** [comment]
Aha, found it. Just add `gem 'simple_captcha2', require: 'simple_captcha'`, then it's broken.

**Comment by cpunion** [comment]
https://github.com/pludoni/simple-captcha/blob/master/lib/simple_captcha/form_builder.rb#L6

Just remove this line, all works fine. It's not a bug of Trestle.

Thanks!

**Comment by cpunion** [comment]
https://github.com/pludoni/simple-captcha/blob/master/lib/simple_captcha/engine.rb#L14

`ActionView::Helpers::FormBuilder` included it. I think it's unnecessary.
