### ISSUE TITLE
Customise link for the top of the sidebar

### ISSUE THREAD

**Issue by timdiggins** [TrestleAdmin/trestle#138]
Loving trestle admin -- thank you for great work.

I wanted to customise the link for the logo (navbar-brand) at the top of the sidebar -- currently the Trestle root (`<%= link_to trestle_title, Trestle.config.path, class: "navbar-brand" %>`) - I'd like it to link to overall site root, rather than trestle root (to be inline with rest of site).

Would you welcome a PR for this? And would you recommend adding a hook (to customise the whole of this link) or a new config item with default (and commented out in the default initialiser `# config.site_title = Trestle.config.path `)

**Comment by spohlenz** [comment]
I see a couple of opportunities for improvements here:

1) Add a configuration option (I'm thinking `Trestle.config.root`) that determines the link target for the main title and root breadcrumb. This would default to `Trestle.config.path`.

2) Allow the `hook` helper to accept a block which would be the default when no custom hooks are present. This would then allow a custom hook to be defined for the site title (`navbar-brand`).

I should hopefully be able to get these in place today.

**Comment by spohlenz** [comment]
These changes are now in place:

* 3a26328f1bc366b13dc0fe35e943125c58c34075
* 2a5b6bef37f531e3b2ee67ab625848f6468089e0
* 8b1e599f95dc6ec55d1337a473efaeb8a9d3bc94

**Comment by timdiggins** [comment]
Wow fast work, thanks @spohlenz -- it's just what I needed.
