### ISSUE TITLE
Polymorphic association issue

### ISSUE THREAD

**Issue by dendomenko** [TrestleAdmin/trestle#14]
Default table and form throw an error in polymorphic associations.
![screenshot from 2017-08-10 16-51-18](https://user-images.githubusercontent.com/9824288/29173517-3646a940-7dec-11e7-879b-c4cd755ab819.png)

**Comment by spohlenz** [comment]
Are you able to upload a sample app to GitHub. I'm unable to reproduce this particular error.

I am seeing an error for polymorphic associations on the form page that I need to fix. However it is slightly different to what you are experiencing.

**Comment by dendomenko** [comment]
I can't upload this app to GitHub, But can share some models code.  
`post_community.rb` which cause of an error.
```
class PostCommunity < ApplicationRecord
  belongs_to :taggable, polymorphic: true

  belongs_to :community

end
```

community.rb

```
class Community < ApplicationRecord
  has_many :post_communities
end
```
social.rb
```
class Social < ApplicationRecord
  belongs_to :user
  has_many :post_communities, as: :taggable


end
```
Also, I have Blog and Event models, but they have the same associations like Social

**Comment by spohlenz** [comment]
Ah, I see now why I wasn't able to reproduce (my test app had a constant with the same name as the polymorphic association). I should have what I need now to get this fixed.

**Comment by dendomenko** [comment]
And also Comment model which also polymorphic `belongs_to :commentable, polymorphic: true` throws same error

**Comment by spohlenz** [comment]
Polymorphic association support has been added in 034238b. For now it is read-only, since enumerating the possible types for a dropdown is not an easy one to solve.
