### ISSUE TITLE
How are plugins injected into the framework?

### ISSUE THREAD

**Issue by jfrux** [TrestleAdmin/trestle#141]
For instance, I see the _search.html.erb partial in trestle-search but not sure how that partial gets injected?  I'm not seeing it anywhere in the search plugin to override a content_for or place itself inside of something?

**Comment by spohlenz** [comment]
The main mechanism for extension is via hooks.

For example, the trestle-search plugin injects the search field into the `view.header` hook defined within the Trestle views [here](https://github.com/TrestleAdmin/trestle/blob/master/app/views/trestle/shared/_header.html.erb).

It does this from the [`config/initializers/trestle.rb`](https://github.com/TrestleAdmin/trestle-search/blob/master/config/initializers/trestle.rb#L8-L10) initializer within trestle-search.

The available hooks are currently fairly limited but if you need one for a specific use case, I will almost certainly be happy to add it in.

**Comment by jfrux** [comment]
Nice!!!
Exactly what I was looking for.

Was looking at adding features via plugins and just realized I had no idea about how to do it.
You continue to set my mind at ease with each passing day.  Thanks again.

I think my biggest hang up is not Trestle, but my lack of Rails knowledge.  It shows evident I’m guessing. :D
