### ISSUE TITLE
Is anyone able to share some of the ways to use tag_select?

### ISSUE THREAD

**Issue by jfrux** [TrestleAdmin/trestle#142]
I'm wanting to use it for like a One to Many select box... so I don't want like actual "tags" just a single option that is searchable but also has the option to add a new one and actually save to the relationship.

like umm... a dropdown field that can also add, like a combo box.  Trying to get decent UX with it.

**Comment by jfrux** [comment]
like, select2({ tags: true}) but with createTag built in somehow?

**Comment by spohlenz** [comment]
Here's how I handled this on a recent project. In this instance, I didn't use createTag since I didn't want the associated model to be created until the form was submitted successfully, and I didn't actually use `tag_select` since I decided the styling wasn't appropriate.

The model relationships are Article <-> Authorships <-> Author:

```ruby
class Article < ApplicationRecord
  has_many :authorships
  has_many :authors, through: :authorships
end

class Authorship < ApplicationRecord
  belongs_to :author
  belongs_to :article
end

class Author < ApplicationRecord
  has_many :authorships
  has_many :articles, through: :authorships
end
```

and the code in the `ArticlesAdmin` form is also relatively simple:

```ruby
Trestle.resource(:articles) do
  form do
    select :author_ids, Author.all, { label: "Author(s)" }, { multiple: true, data: { tags: true } }
  end
end
```

The main work is in the `Article` model where I define a custom `author_ids=` setter:

```ruby
class Article < ApplicationRecord
  def author_ids=(ids)
    self.authors = Array(ids).reject(&:blank?).map { |id|
      (id =~ /^\d+$/) ? Author.find(id) : Author.new(name: id)
    }
  end
end
```

This approach does have some drawbacks. In particular it won't work with UUIDs, and it also won't work when the associated value consists purely of digits. Passing in a mixed array of IDs and value strings to a method named `author_ids` I also find a bit messy. The approach worked for my use case but I'd definitely like to find a more flexible solution.

My more typical use case for `tag_select` is with a gem such as `acts-as-taggable-on` or even a simple Postgres array column. For tagging with `acts-as-taggable-on`, it's as simple as:

```ruby
Trestle.resource(:articles) do
  form do
    tag_select :tag_list, label: "Tags"
  end
end
```

**Comment by jfrux** [comment]
I absolutely love the time you put into your responses.
They can be easily copy and pasted into a new Wiki page.  If you don’t mind, I could do those for you to help out.  I’ve been reviewing a lot of your tickets and most of them seem like they’re articles by themselves.

I’m not sure if there is a benefit in doing that, but maybe there is? Hmm.

Anyway, thanks for the response - this is very helpful.

**Comment by spohlenz** [comment]
> They can be easily copy and pasted into a new Wiki page.  If you don’t mind, I could do those for you to help out. 

That would be fantastic if you're willing to. It can sometimes be hard in my shoes to work out which pieces of information people would find useful.

**Comment by jfrux** [comment]
I’ll give you a hint… ALL INFORMATION, no matter how significant… will be found to be useful to everyone…
I challenge you to paste your responses as Wiki Pages instead of issue responses and then link users to them from the issues.  Although people are finding them from Google, if you get them into Wiki we can all contribute to organizing them and making them more sucinctly and adequately organized for you. :)

:). I mean, you’re already generously taking the time to express how something is done - may as well share it as a “How To” in the wiki or something.

I think it will pay off later.

Or… possibly an even better solution might be to just throw it up on GitBook.io or something so that it’s better indexed and richer with images and things of that nature.

Doesn’t have to be fancy, just something that is indexed and able to be edited by everyone.

I’m kind of doing that now with another project, which is what lead me to you to begin with.
I think Trestle takes the perfect amount of advantage of Rails and is the prime usage for Rails in this day in age where everyone is trying to avoid these types of frameworks…

Things like rails_admin were cool when everyone wanted everything to be done for them but everyone realizes that it’s not SENSIBLE and offers less value than something they can truly expand upon without it being over bearing and controlling.

It’s about balance and I think you do have that balance with this framework.
We just need to find a way to bridge the developer on boarding a bit… I tried Testle and went to something with more “Stars” just because…. But then came back to it and gave it a second chance and love it.

I think it’s just the on-boarding is suffering quite a bit and I’d love to help.  People don’t really use Github Wiki much but would be probably more interested in maintaining the docs either in the main repo in a sub folder, or within GitBook or something.

I don’t like GitBook because of its business model and it’s lack of ability for ANYONE to edit it without tying it to a GitHub repo but it is better than nothing.

I’d even think doing PR’s to your main repo might be enticing for people to start contributing too.

People love getting PR’s under their belt even for small docs changes lol.

I dunno!

Anyway, happy to help!
