### ISSUE TITLE
Redirect logout

### ISSUE THREAD

**Issue by AnthonyLatty** [TrestleAdmin/trestle#144]
Is there a way i can change the logout to redirect the user to the main page instead of the login forms? If not can a link be placed on the forms referencing the main page?? @spohlenz

**Comment by spohlenz** [comment]
I'm not sure if you have found an alternative solution. However being able to customize the post-login/logout redirect locations is a reasonable thing to have, which I have implemented in https://github.com/TrestleAdmin/trestle-auth/commit/82aed44219092dc908116dd215b89298fc2b0a6d.

**Comment by AnthonyLatty** [comment]
Thanks for your response, i will test this and update you accordingly.
