### ISSUE TITLE
Cleanest way to change the data-url to use the slug of a record versus id?

### ISSUE THREAD

**Issue by jfrux** [TrestleAdmin/trestle#146]
I've tried a few things but none of them seem universally okay for just modifying it to work for a particular list page.

**Comment by spohlenz** [comment]
What you need here is a combination of the `to_param` and `find_instance` blocks:

```ruby
Trestle.resource(:articles) do
  to_param do |instance|
    instance.slug
  end

  find_instance do |params|
    Article.find_by(slug: params[:id])
  end
end
```

**Comment by jfrux** [comment]
Holy sh**… I constantly over complicate.
You are a rockstar.

Thanks man!
