### ISSUE TITLE
Man... I just do not get the menu item priority...

### ISSUE THREAD

**Issue by jfrux** [TrestleAdmin/trestle#147]
I just don't understand how to use it effectively...

It seems to do all sorts of things and I don't think it's sorting alphanumerically or based on priority... no clue.  Very odd.

**Comment by dayves** [comment]
to priority group and item, try something like this
`menu do
    group 'ADMIN',  priority: 2 do
      item :accounts, label: 'Account', icon: 'fa fa-users', priority: 1
    end
  end`
the group priority, rank by other group or ungrouped item and the item priority rank by other item inside the group

Hope I helperd you

**Comment by jfrux** [comment]
Thanks… that’s what I thought I was doing… kind of wish we just had a config file that could specify them all.
Kind of hard to know what each files priority is so I know what to set one to.  It’s just not a very clean DSL for this… maybe it should be done in the initializer or something who knows.

Or even if there was like a root Trestle.admin() that has a global menu.

And I’m not familiar enough with Ruby to understand why we aren’t using Classes instead of Trestle.admin() too.

**Comment by dayves** [comment]
Hmm... I understand your problem now, but I don't know how to help.

Sorry

**Comment by spohlenz** [comment]
As @dayves mentioned, you'll want to use a nested `group` definition in most cases. I should update the example in the README and on the web site as I rarely use the short-hand version.

Groups have a priority from `-∞` ... `-1`, `0`, `1` ... `+∞` (default `0`). You can also use `:first` to refer to `-Float::Infinity` or `:last` to refer to `+Float::Infinity`. There is also an implicit/null group that items go into when no group is specified, that always appears first in the menu. I'll generally just put a Dashboard admin in there and everything else into groups.

Items are ordered using a similar priority level but scoped to within the group only.

If multiple items/groups share the same priority, then they will be sorted in the order in which they were loaded. In most cases (assuming admins loaded from a single flat directory) this will be alphabetical but this can obviously get more complicated assuming nested directories and alternative load paths (e.g. engines).

> Or even if there was like a root Trestle.admin() that has a global menu.

Good news! You can do this if you prefer.

This needs to be added to your `config/initializers/trestle.rb` so the Rails app will need to be restarted when you make any changes. You'll also need to specify the path explicitly for each item.

```ruby
Trestle.configure do |config|
  config.menu do
    item :dashboard, Trestle.lookup(:dashboard).path, icon: "fa fa-dashboard"

    group :my_group do
      item :articles, Trestle.lookup(:articles).path
    end
  end
end
```

Although I'd like to fine-tune this to allow simpler definitions, e.g.

```ruby
item :articles, admin: :articles
```

My personal preference is to define the menus within each admin (hence why I made it the default), but I can definitely see the benefits and clarity in this approach.

> And I’m not familiar enough with Ruby to understand why we aren’t using Classes instead of Trestle.admin() too.

The most honest answer I can give you is probably: this is what I was able to make work.

The `Trestle.admin` call does a reasonable amount of setup (main bits are here: https://github.com/TrestleAdmin/trestle/blob/master/lib/trestle/admin/builder.rb#L18-L40). In particular it add the admin to the global Trestle admin registry, and creates up the controller, etc.

It also does all this within the context of a Builder object, which keeps the DSL separate from the main admin class.
