### ISSUE TITLE
Can we change the path of an admin?

### ISSUE THREAD

**Issue by jfrux** [TrestleAdmin/trestle#149]
I'm looking to change the URL of a route, guessing I just do it manually in routes the "Rails" way but didn't know if there was just a simple way to change it for the Admin so that table links and saves and things all point to that URL as well...?

**Comment by spohlenz** [comment]
The path to an admin can be customized by passing the `:path` option to `Trestle.admin` or `Trestle.resource`. e.g.

```ruby
Trestle.resource(:articles, path: "myarticles") do
  ...
end
```

The path will always be scoped within `Trestle.config.path`, i.e. usually under `/admin`.
