### ISSUE TITLE
Updating font-awesome to 5.0?

### ISSUE THREAD

**Issue by jfrux** [TrestleAdmin/trestle#150]
So many nice features available.
I've been using it in other projects and would love to see it here.

I know its probably not difficult, but didn't know if you supported the migration if I were to PR it.

**Comment by spohlenz** [comment]
I certainly wouldn't reject a PR to upgrade FontAwesome within the current build system. However you may want to consider the following caveats:

1. I am currently working on overhauling the build system (and updating the front-end dependencies) which would invalidate this work. I would like to say that this is only a couple of weeks away. However I wouldn't want to be held to that.

2. I am not sure how easy it will be to update to version 5.0 in the current bower-based build system, given FA5 has its own significant changes to the way it is built.

Out of interest (and so I keep it in mind as I work on the upgrades), apart from the expanded icon range, what were the new features in FA5 are you keen to use?

**Comment by jfrux** [comment]
@spohlenz would love to hear the overhauling involves some webpacker usage instead of sprockets... current build is sooo slow just to make a custom change to a css file makes the whole thing hang forever.

Unless you have a solution to this that is cleaner?

**Comment by jfrux** [comment]
Good news about FA5 is they include shims for V4 so there shouldn't be a lot of extra work behind upgrading it.

**Comment by jfrux** [comment]
or maybe just upgrade the V4 version at the very least...
current version is missing some good icons such as:
https://fontawesome.com/v4.7.0/icon/pencil-square-o

**Comment by jfrux** [comment]
Oops, ignore the latest one about missing the icon... was my mistake.

**Comment by shrmnk** [comment]
@spohlenz Any word on when the build system will be updated? (and what build system will you be moving towards?)

**Comment by spohlenz** [comment]
Please see #195 for the PR with the new build system and the update to FontAwesome 5, Bootstrap 4, etc. I'd encourage you to try it out and let me know if you encounter any issues.
