### ISSUE TITLE
Real quick, how do I override collection method?

### ISSUE THREAD

**Issue by jfrux** [TrestleAdmin/trestle#151]
@spohlenz real quick, how do I override a collection exactly in a Resource?

When I use:

```
collection do |params|
   byebug
end
```

It's not being called...

**Comment by spohlenz** [comment]
If you're on the admin index page then that method should be called, with one exception:

If you are using `trestle-search` and have defined a `search` block, then the search block overrides the collection block (even when not explicitly searching). However it can be called manually.

If you're seeing something different to the above, can you post more of the admin?

**Comment by jfrux** [comment]
Thank you thank you.
