### ISSUE TITLE
Question how would you handle Associations?

### ISSUE THREAD

**Issue by AnthonyLatty** [TrestleAdmin/trestle#152]
I understand how to have a resource, i am wondering how would you handle an association? Example:
`class Author < ApplicationRecord
  has_many :books, dependent: :destroy
end
 
class Book < ApplicationRecord
  belongs_to :author
end`

**Comment by spohlenz** [comment]
Check out this wiki page for the best way to do this currently:
https://github.com/TrestleAdmin/trestle/wiki/Has-Many-Relationship-Tab

I do have plans to achieve this more comprehensively, but it is not something I have been able to look at so far.
