### ISSUE TITLE
Problem with associations after adding trestle-active_storage gem

### ISSUE THREAD

**Issue by PunkMaldito** [TrestleAdmin/trestle#155]
I have a form working properly with a has_one association between `Company` and `CompanyAddress`, with something like this in the admin file:

```ruby
  form do |company|
    tab :company_info do
      row do
        col(sm: 6) { text_field :name }
        col(sm: 6) { text_field :trade }
      end

      row do
        col(sm: 6) { text_field :cnpj }
        col(sm: 6) { select :segment, ApplicationRecord::SEGMENTS }
      end

      row do
        col(sm: 6) { date_field :foundation }
        col(sm: 6) { active_storage_field :logo }
      end
    end

    tab :company_phones do
      render 'phones'
    end

    tab :company_address do
      fields_for :company_address, company.company_address || company.build_company_address do
        row do
          col(sm: 6) { text_field :zip_code }
          col(sm: 6) { text_field :number }
        end

        row do
          col(sm: 6) { text_field :street }
          col(sm: 6) { text_field :complement }
        end

        row do
          col(sm: 6) { text_field :city }
          col(sm: 6) { text_field :state }
        end

        url_field :website
      end
    end
  end
```

The catch is that when I add the _trestle-active_storage_ gem, the parameter sent for the address that used to be _company_address_attributes_, becomes _company_address_. And Trestle raises the error:
```
ActiveRecord::RecordNotFound in CompaniesAdmin::AdminController#update

Couldn't find CompanyAddress with ID=2 for Company with ID=
```

If I remove the symbol after the _fields_for_, passing only the object, Trestle raises a type mismatch error. Because it's not an instance of `CompanyAddress`, but an instance of `ActiveSupport::HashWithIndifferentAccess`.

Am I missing something? How can I solve that?

By the way, the has_many association between Company and CompanyPhone also has the same problem.

**Comment by PunkMaldito** [comment]
By the way, the _has_many_ association between `Company` and `CompanyPhone` also has the same problem.

**Comment by PunkMaldito** [comment]
Problem solved with a gem update. ;-)

**Comment by vbrazo** [comment]
I'm having the same problem here. Which versions were you using? @PunkMaldito

**Comment by vbrazo** [comment]
I've just fixed it. I forgot to add `accepts_nested_attributes_for :shipping_address` to my model, that's why I was getting

```ruby
ActiveRecord::AssociationTypeMismatch (::Merchants::Contact(#70292973777220) expected, got {"name"=>"a", "email"=>"a", "phone"=>""} which is an instance of ActiveSupport::HashWithIndifferentAccess(#70292925115780)):
```
