### ISSUE TITLE
dependency kaminari not documented

### ISSUE THREAD

**Issue by koenhandekyn** [TrestleAdmin/trestle#156]
was getting undefined method 'per', root cause missing kaminari. probably this needs to be part of the getting started / installation instructions

**Comment by spohlenz** [comment]
Trestle should automatically depend on Kaminari and require it on load.

The error you are seeing may be happening if you have the `will_paginate` gem installed. In that case, create and add the following to `config/initializers/kaminari.rb`:

```ruby
Kaminari.configure do |config|
  config.page_method_name = :per_page_kaminari
end
```

**Comment by koenhandekyn** [comment]
i actually had will_paginate installed indeed.
