### ISSUE TITLE
Using .includes to avoid N+1 queries?

### ISSUE THREAD

**Issue by johnrees** [TrestleAdmin/trestle#158]
Is there a way to add `.includes` to a resource's index page query without adding it as the default scope in the model file?

For example if an `Order` has a `Customer` and I want to display `column :customer` in the `orders_admin.rb` file, can trestle somehow request `Order.includes(:customer).all` instead of `Order.all` and multiple `Customer.find(x)` queries.

I initially tried to do this using `scope :all, -> { Order.includes(:customer).all }` in the trestle resource file but I don't think the scopes are designed handle relations?

**Comment by spohlenz** [comment]
This is something I commonly do by overriding the `collection` block for the admin:

```ruby
collection do
  Order.includes(:customer)
end
```

All other queries (scopes, pagination, etc.) will build off of this base collection scope.
