### ISSUE TITLE
How to render a search form in the index?

### ISSUE THREAD

**Issue by develaper** [TrestleAdmin/trestle#159]
I'm trying to add a search form before the index view table but the only solution I figured out is to override the index view.
Is there any other solution to add a partial?

**Comment by spohlenz** [comment]
Check out the `trestle-search` gem (https://github.com/TrestleAdmin/trestle-search), which lets you easily add a search field.

Even you decide it doesn't meet your needs, you may find some clues there as to how to achieve the desired result (check out the view hook injected from `config/initalizers/trestle.rb`, as well as the custom adapter methods that get mixed into `Trestle::Resource` and `Trestle::Resource::Builder`).

**Comment by develaper** [comment]
Thanks @spohlenz
