### ISSUE TITLE
Any plan for column Filtering ? 

### ISSUE THREAD

**Issue by MatthiasRMS** [TrestleAdmin/trestle#16]
Is there any plan to develop filters on models attributes ? 
I'd be happy to submit a PR with filters built with [Ransack](https://github.com/activerecord-hackery/ransack)

**Comment by spohlenz** [comment]
I'm planning on building this out as part of the `trestle-search` plugin, with the filtering implemented as a popover or modal triggered by clicking on an 'advanced' button in the search area.

My current thinking is that the DSL should allow general scope filters, and should not depend on Ransack directly, but perhaps there would be another integration plugin `trestle-search-ransack` that would make Ransack filters easy to write.

I've started an issue to track this at https://github.com/TrestleAdmin/trestle-search/issues/2.

**Comment by StandardNerd** [comment]
Hi MatthiasRM, did you developed filters feature using Ransack?

**Comment by Alxzu** [comment]
Hey, which is the sate of this? Any progress?

**Comment by karan-ta** [comment]
Any news on this one. 
Any interim ideas? 
Please let me know. 
I need to make column filtering.
