### ISSUE TITLE
Add TinyMCE plugin and languages

### ISSUE THREAD

**Issue by shenhf** [TrestleAdmin/trestle#165]
Hi, @spohlenz 
How to Add a TinyMCE plugin like [MathType for TinyMCE](http://docs.wiris.com/en/mathtype/mathtype_web/integrations/html/tinymce) . Also, I'd like to add TinyMCE language files.

thank for you help.

**Comment by spohlenz** [comment]
The `trestle-tinymce` plugin uses the [`tinymce-rails`](https://github.com/spohlenz/tinymce-rails) under the hood to include the TinyMCE assets. See the section on [Custom Plugins & Skins](https://github.com/spohlenz/tinymce-rails#custom-plugins--skins) in that project's README to see where to place the plugin assets.

For TinyMCE language files, you can install the [`tinymce-rails-langs`](https://github.com/spohlenz/tinymce-rails-langs) gem.
