### ISSUE TITLE
Rendering autoformatted value for table column cell in case of block

### ISSUE THREAD

**Issue by okliv** [TrestleAdmin/trestle#17]
if i use

```ruby

# products_admin.rb

table do
    column :category
end
```

it autoformats category cell value with `belongs_to :category` into a link to category instance

but if i use 

```ruby
column do |instance|
      instance.category #it is not making much sense in exact this case but lets assume i need exact this syntax (i have more difficult situation, but do not want to mess with it here)
end
```

it shows unpleasant `instance.inspect` output `#<Category:0x007fd2eeb1ed60>`. is it wrong behavior or do i have to do something more inside a block?

all i digged for now is 

```ruby
column do |instance|
   self.display(instance.category)
end
```
but it gives only a name of category without `admin_link_to`

**Comment by spohlenz** [comment]
Here's the most likely form of what you want:

```ruby
column :category do |instance|
  admin_link_to display(instance.category), instance.category
end
```

The `display` helper tries to render a friendly human form of the instance by trying each of the methods specified in `Trestle.config.display_methods`. You may prefer just to write `instance.category.name` or similar.

If the admin can't be inferred (e.g. if it is within a module scope), then you can specify the admin using the admin option. e.g.

```ruby
admin_link_to display(instance.category), instance.category, admin: :categories
```
