### ISSUE TITLE
current_user undefined in menu using custom link?

### ISSUE THREAD

**Issue by mansur-usis** [TrestleAdmin/trestle#171]
Trestle.resource(:restaurants, model: Trestle.config.auth.user_class, scope: Auth) do
  menu do
    group :restaurant_food, priority: 2 do
          item :restaurants, "admin/auth/restaurants/#{current_user.id}", icon: "fa fa-lock", priority: 1
      end
  end

throw error
undefined local variable or method `current_user' for #<Trestle::Navigation::Block::Context:0x007fe374b19838>

**Comment by spohlenz** [comment]
Apologies for the delay. This should now be fixed in 6d16fb8.
