### ISSUE TITLE
JSON(B) serialisation issue

### ISSUE THREAD

**Issue by richardvenneman** [TrestleAdmin/trestle#18]
When I save an instance with a JSONB field, the field value gets converted to a string.

```ruby
create_table "bookings", id: :serial, force: :cascade do |t|
    ...
    t.jsonb "client_params"
end
```

Configured with `text_area` (but this also occurs with auto configuration)
```ruby
form do |booking|
  text_area :client_params
end
```

---

Value before save:
```ruby
puts instance.client_params
=> {"language"=>"en", "inbound_date"=>"2017-08-10"}
```

Value after save:
```ruby
puts instance.client_params
=> "{\"language\"=>\"en\", \"inbound_date\"=>\"2017-08-10\"}"
```

I'm guessing we might need to do some parsing ([RailsAdmin JSON field ref](https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/fields/types/json.rb)) but couldn't figure this out unfortunately.

**Comment by spohlenz** [comment]
There's currently a couple of ways to solve this one.

The cleanest option will be to define a custom writer method on your model:

```ruby
def client_params=(params)
  params = JSON.parse(params) if params.is_a?(String)
  super(params)
end
```

Another option would be to define a custom `params` block in your admin:

```ruby
params do |params|
  params.require(:booking).permit(:client_params).tap do |p|
    p[:client_params] = JSON.parse(p[:client_params])
  end
end
```

Eventually I'd like to add built-in support for form objects which would make this even cleaner, but this is some way off.

**Comment by richardvenneman** [comment]
Thanks for the support @spohlenz. Because Rails returns the JSON as a Hash in string form I had to make a few adjustments. I created this concern for use with multiple models:

```ruby
module JSONSerializable
  extend ActiveSupport::Concern

  included do
    json_attributes = attribute_names.map do |name|
      name if type_for_attribute(name).type == :jsonb
    end.compact

    json_attributes.each do |attr|
      define_method("#{attr}=".to_sym) do |value|
        value = JSON.parse(value.gsub('=>', ':')) if value.is_a?(String)
        super(value)
      end
    end
  end
end
```

**Comment by kevinelliott** [comment]
@spohlenz Revisiting this issue that @richardvenneman had.

I was wondering what support for this officially might look like.

Would you prefer:

1. a custom field class, `json_text_area` that incorporated the conversions above
2. a flag to `text_area` that allowed for explicit hash/json handling but reuses existing field class
or
3. auto-detection of the attribute type in the model as JSON/JSONB and then internal handling of this (details still unclear where that would occur though)

?

**Comment by spohlenz** [comment]
The form helpers in Trestle are only responsible for the front-end rendering, not the back-end processing. Whilst they could potentially be made to handle the server-side processing too, I don't see a way of doing that without making things too "rigid".

However an approach that I have been considering since the start is to introduce a form object that could handle these sorts of things, in order to keep them from cluttering up the model.

It would probably look something like this:

```ruby
form_object do
  reject_blank :tags
  json :metadata

  def title=(title)
    instance.title = title.titlecase
  end
end
```

**Comment by sudoaza** [comment]
Also don't forget the `text_area :metadata, value: metadata.to_json` in the form
