### ISSUE TITLE
Favicon?

### ISSUE THREAD

**Issue by okliv** [TrestleAdmin/trestle#180]
```` ruby
ideas = TrestleLayoutFile.all.map(&:dig).compact
ideas.empty? #=> true
````
any ideas how to add a favicon for trestle application?

**Comment by spohlenz** [comment]
Currently you'll need to use a hook (`:head`) in your initializer:

```ruby
config.hook :head do
  favicon_link_tag "myfavicon.ico"
end
```

This does deserve it's own configuration option though I think.

**Comment by spohlenz** [comment]
The `config.favicon` option has been added in 81a8f65.

Example:
```ruby
config.favicon = "favicon.ico"
```
