### ISSUE TITLE
Integration with Discard gem for soft-deletes

### ISSUE THREAD

**Issue by yagudaev** [TrestleAdmin/trestle#181]
It would be great to provide an integration to the `discard` gem for  soft deletes.

Adding some good documentation (we need a docs folder like AA has) would really help.

What I've done was add it like this:

```ruby
# admin/posts.rb
Trestle.resource(:posts) do
  controller do
    # TODO: can extract this to generic soft delete helper
    def destroy
      success = instance.discard

      respond_to do |format|
        format.html do
          if success
            flash[:message] = flash_message("destroy.success", title: "Success!", message: "The %{lowercase_model_name} was successfully deleted.")
            redirect_to_return_location(:destroy, instance, default: admin.path(:index))
          else
            flash[:error] = flash_message("destroy.failure", title: "Warning!", message: "Could not delete %{lowercase_model_name}.")

            if self.instance = admin.find_instance(params)
              redirect_to_return_location(:update, instance, default: admin.instance_path(instance))
            else
              redirect_to_return_location(:destroy, instance, default: admin.path(:index))
            end
          end
        end
        format.json { head :no_content }
        format.js
      end
    end
  end

# models/post.rb
class Post < ApplicationRecord
  include Discard::Model
  # using default scope for the sake of trestle, not sure how to integrate properly
  default_scope -> { kept }
end
```
What I'd like to do is:

1) Avoid copying destroy/index methods directly from gem source
2) Avoid using default scopes
3) Hook into collection and instance methods to customize how resources are fetch while still retaining the nice pagination, sorting and so on features

**Comment by spohlenz** [comment]
> Avoid copying destroy/index methods directly from gem source

You can override the instance method that is used for deletion by defining a custom adapter method in your admin:

```ruby
Trestle.resource(:posts) do
  delete_instance do |instance|
    instance.discard
  end
end
```

If you want to provide a 'force delete' option, you might want to pass that in as an additional parameter with your delete links:

```ruby
Trestle.resource(:posts) do
  delete_instance do |instance, params|
    if params[:force]
      instance.destroy
    else
      instance.discard
    end
  end
end
```

> Avoid using default scopes

Rather than using default model scopes, you can define scopes within the admin, one of which can be the default:

```ruby
Trestle.resource(:posts) do
  scope :active, -> { model.kept }, default: true
  scope :deleted, -> { model.discarded }
end
```

**Comment by yagudaev** [comment]
@spohlenz this is great, should we add this to the wiki?

**Comment by spohlenz** [comment]
@yagudaev That would be great, thank you. 👍

**Comment by vbrazo** [comment]
After discarding the record, how can we hide the `delete` button when viewing/editing the record again?

**Comment by spohlenz** [comment]
@vbrazo You can override the secondary toolbar within your form block to customize the delete button functionality.

```ruby
form do |article|
  toolbar(:secondary, clear: true) do |t|
    unless article.new_record? || article.discarded?
      t.link admin.t("buttons.delete", default: "Delete %{model_name}"), instance, action: :destroy, method: :delete, style: :danger, icon: "fa fa-trash", data: { toggle: "confirm-delete", placement: "bottom" }
    end
  end
end
```

Combining this with a custom action and you could potentially implement an undelete button in this fashion.
