### ISSUE TITLE
No support Ssl or https authentication

### ISSUE THREAD

**Issue by halleyrv** [TrestleAdmin/trestle#183]
Hi I use trestle in production when i tried login with app configurate to https not workin I have a message error.

```
Parameters: {"utf8"=>"✓", "authenticity_token"=>"UpwtvP0sNUrNqQazOh9BiLEv0uuOi75shw/leYNDJrPC9jpv7Qv9ShzZvFslBakHO+NjTtJPQ7bphiMbaBXzKg==", "email"=>"user@example.com", "password"=>"[FILTERED]", "commit"=>"Login"}
W, [2019-03-11T16:52:04.342504 #7304]  WARN -- : [fb212b57-7199-49df-b85f-3a0c8ff81ea8] HTTP Origin header (https://example.com) didn't match request.base_url (http://example.com)
D, [2019-03-11T16:52:04.395429 #7304] DEBUG -- : [fb212b57-7199-49df-b85f-3a0c8ff81ea8]
```

In localhost or if I disable htps  to my server not problem.

How i resolved this problem?

**Comment by spohlenz** [comment]
I believe that this is most likely a web server configuration issue, and that you'll need to configure the headers that are passed by the proxy.

See https://github.com/rails/rails/issues/22965#issuecomment-172929004 for a possible solution.

**Comment by halleyrv** [comment]
Thanks a lot @spohlenz . The solution in the links works for me
