### ISSUE TITLE
Support for Rails 6

### ISSUE THREAD

**Issue by FreeApophis** [TrestleAdmin/trestle#194]
I try to use trestle on Rails 6.

Basic functionality works, however I see a few issues:

* rich_text_area should be supported since it's now part of the Rails builder.
* I tried to do that via custom field, and ran into the next problem
   * the trix JS is not loaded, so it does not work
   * then I found assets/javascript/testle/custom.js
   * At that point I got stuck, I cannot include trix AFAIK because that is included via the webpacker asset pipeline, and this is using the old way via webpacker. 

I never liked the assets pipeline from rails, and now it's twice as complicated, because you can use both, and there is no real documentation from rails, on how it should work in the first place.

If anyone got it to work, would be nice to hear from you.

**Comment by spohlenz** [comment]
I'm not decided yet on how I'll handle things like `rich_text_area`, although I'm most inclined to put it in a plugin rather than core, since I want to continue to support Rails versions earlier than 6.

However it should be possible to still get it working without a plugin. My recommendation would be to:

1. Generate a new Webpacker pack that just includes the Trix JS.
2. Inject the pack into Trestle from `config/initializers/trestle.rb`:

```ruby
config.hook(:javascripts) do
  javascript_pack_tag "trix"
end
```

Note: this is untested but should lead you on the right path at least.

**Comment by FreeApophis** [comment]
Thank you for the hint, it took a little experimenting and guessing and looking around but I got it to work entirely, and it actually looks pretty well suited out of the box!

If someone else wants to use this, do the following steps:

1. Add the class for a new field Type

*app/fields/rich_text_area.rb*

```ruby
class RichTextArea < Trestle::Form::Field
  def field
    content_tag :div, class: 'input-group' do
      builder.raw_rich_text_area(name, options)
    end
  end
end
```

2. Create a new file (pack) 

*app/javascript/packs/trix.js*

    require("@rails/activestorage").start()
    
    require("trix")
    require("@rails/actiontext")

3. Create a new file for the trix stylesheets:

*app/assets/stylesheets/trix.css*

    /*
     * This is a manifest file that'll be compiled into trix.css, which will include all the files
     * listed below.
     *
     *= require actiontext
     */

4. Add at least the trix.css to the precompile targets (I suppose the js is not needed? due to webpack?)

*config/initializers/assets.rb*

    Rails.application.config.assets.precompile += %w( trix.js trix.css )

5. Now we need to register all the parts we just created with trestle, in its initializer we write:

*app/fields/rich_text_area.rb*

```ruby
  config.form_field :rich_text_area, RichTextArea

  config.hook(:javascripts) do
    javascript_pack_tag 'trix', 'data-turbolinks-track': 'reload'
  end

  config.hook(:stylesheets) do
    stylesheet_link_tag 'trix', media: 'all', 'data-turbolinks-track': 'reload'
  end
```

Now you can use `rich_text_area` (or whatever you named it in step 5) like any other field within trestle

**Comment by cvincent** [comment]
This doesn't seem to be working for me. I end up with `undefined method `rich_text_area_tag'`. Does it still work for you? I'm on Rails 6.0.2.2. I have no idea how to debug this without spending the rest of the day going through Trestle's source code, unfortunately, which is more time than I think it should take to simply use a form helper that comes with Rails.
