### ISSUE TITLE
How I implement test with rspec in my custom controller in trestle

### ISSUE THREAD

**Issue by halleyrv** [TrestleAdmin/trestle#197]
I create the controller copy syllabus in trestle

```
Trestle.admin(:copy_syllabus) do
  menu do
    item :copy_syllabus, icon: "fa fa-tachometer"
  end

  controller do
    def index
            
     end
    
    def create
    end
    end
```

So I need to add rspec test for this controller

I tried with  this structure of files

`rspec/admin/copy_syllabus_controller.rb`

But when I run rspec spec  show me the error 

```
NameError:
  uninitialized constant Admin::CopySyllabusController
```

**Comment by spohlenz** [comment]
There's one thing I need to fix up to make this work seamlessly. However here's how you can get this working now.

Assuming an admin named `:test`, the admin builder creates a subclass of `Trestle::Admin` named `TestAdmin`, within which is a subclass of `Trestle::Admin::Controller` named `TestAdmin::AdminController`. If we define a route named `custom` then to test this with RSpec we can use:

```ruby
require 'rails_helper'

RSpec.describe TestAdmin::AdminController, type: :controller do
  controller TestAdmin::AdminController do
    def self.controller_path
      "test_admin/admin"
    end
  end

  routes { Trestle::Engine.routes }

  describe "#custom" do
    specify "GET" do
      get :custom
    end
  end
end
```

Now the controller block overriding `.controller_path` is something that hopefully won't be necessary soon. I'm anticipating that this will be a fairly easy fix.

**Comment by spohlenz** [comment]
As of 3d732d7, the following should be sufficient:

```ruby
require 'rails_helper'

RSpec.describe TestAdmin::AdminController, type: :controller do
  routes { Trestle::Engine.routes }

  describe "#custom" do
    specify "GET" do
      get :custom
    end
  end
end
```
