### ISSUE TITLE
How do disable convert name title of sidebar and breadcrumb which it automation convert  example: TEST -> Test

### ISSUE THREAD

**Issue by hoangnv2107** [TrestleAdmin/trestle#198]
it automation convert example: TEST -> Test

**Comment by spohlenz** [comment]
Trestle will automatically titlecase the menu item unless you explicitly specify the label option:

```ruby
Trestle.resource(:test) do
  menu do
    item :test, icon: "fa fa-star", label: "TEST"
  end
end
```

For breadcrumbs, you can override the custom breadcrumb:

```ruby
Trestle.resource(:test) do
  breadcrumb "TEST"
end
```

**Comment by hoangnv2107** [comment]
Oh thanks you very much @spohlenz . How do change breadcrumb-item  ? I know there is a way to handle override show and edit, new in template, is there a more concise way of handling such as change label ?
About  breadcrumb-item: Example: Home -> Test -> AtiClE.

**Comment by spohlenz** [comment]
You can do this by editing your locale file (e.g. `config/locale/en.yml`).

```yaml
en:
  admin:
    test:
      titles:
        edit: "Custom Title"
```

Editing the one i18n key (`admin.{{admin_name}}.titles.{{action_name}`) will currently apply to both the title and breadcrumb, but I will likely change this to two independent settings at some point in the near future.

**Comment by hoangnv2107** [comment]
Oh yes, i can use file i18n. but it will convert from CusTOM -> Custom ? So i need  you help. @spohlenz

**Comment by spohlenz** [comment]
Can you paste your locale file and a screenshot? I'm not seeing that behaviour on my end.

**Comment by hoangnv2107** [comment]
ah language is :ja. Not :en. Thanks you. I will share earliest available a locale file and a screenshot.

**Comment by hoangnv2107** [comment]
Ah so sorry, i changed it ^^ thanks you very much @spohlenz
