### ISSUE TITLE
How does you create  a pagination in form -> tab -> table ?

### ISSUE THREAD

**Issue by hoangnv2107** [TrestleAdmin/trestle#200]
How does you create a pagination in form -> tab -> table ?
And we can use :sort with :id this case. 
<img width="655" alt="Screen Shot 2019-05-20 at 9 23 34 PM" src="https://user-images.githubusercontent.com/45548185/58040103-c728e880-7b5e-11e9-8285-3f14b3b19044.png">

**Comment by spohlenz** [comment]
This currently isn't supported. However it is a planned feature (along with AJAX pagination as in #201).

I'll be introducing a "subresource" feature, which will allow child relations to be modelled and embedded within the view/edit action of a parent resource.

**Comment by quantavi** [comment]
@spohlenz Any news on that feature?

**Comment by spohlenz** [comment]
In the latest commit a4577826ba37c926f03a425a334087c07dbafd00 on the master branch, I've implemented some partial support for AJAX pagination, which will now allow you to implement pagination within a form tab like your example.

It is not the full "subresource" feature so there is a little setup (see below) but should get you at least part of the way there.

1. Add your table to your comments admin (you could technically instead define this within the partial in the next step if you prefer):

```ruby
Trestle.resource(:comments) do
  table :account do
    column :id
    column :content
    column :user_id
  end
end
```

2. Create a partial `_comments.html.erb` within `app/views/admin/articles` (rename as appropriate):

```erb
<div data-context="<%= admin.instance_path(instance, action: :comments, page: params[:page]) %>">
  <%= table CommentsAdmin.tables[:account], collection: comments %>

  <footer class="main-content-footer">
    <%= pagination collection: comments, entry_name: CommentsAdmin.model_name, remote: true, params: { action: :comments } %>
  </footer>
</div>
```

3. Render the partial from your tab in your accounts admin with the first page of comments:

```ruby
form do |article|
  tab :comments do
    render "comments", comments: article.article_comments.page(1)
  end
end
```

4. Add the action to your accounts admin to render additional pages of comments:

```ruby
controller do
  def comments
    load_instance
    render partial: "comments", locals: { comments: instance.article_comments.page(params[:page]) }
  end
end

routes do
  get :comments, on: :member
end
```

**Comment by quantavi** [comment]
@spohlenz This almost work. I am getting problem with this line: 
```ruby
 <%= pagination collection: newsletter_subscribers, entry_name: NewsletterSubscribersAdmin.model_name, remote: true, params: { action: :newsletter_subscribers } %>
```

When it is added I am getting this error:
```
undefined method `total_count' for #<NewsletterSubscriber::ActiveRecord_AssociationRelation:0x00007facaead5d38>
Did you mean?  total_entries
```

Without this line I am seeing list of subscribers without pagination control.

**Comment by spohlenz** [comment]
@quantavi Make sure you haven't missed the call to `#page` on the collection that is passed to the partial. That will wrap it in the Kaminari object that adds methods such as `#total_count`.

**Comment by quantavi** [comment]
> @quantavi Make sure you haven't missed the call to `#page` on the collection that is passed to the partial. That will wrap it in the Kaminari object that adds methods such as `#total_count`.

You mean something like this?
```ruby
tab :newsletter_subscribers, badge: investment.newsletter_subscribers.size do
      render "newsletter_subscribers", newsletter_subscribers: investment.newsletter_subscribers.page(1)
end
```

If that is the case then it still doesn't work

**Comment by spohlenz** [comment]
@quantavi Do you perhaps have `will_paginate` as a dependency of your application?

If that is the case, could you please try the following:

1. Create an initializer `config/initializers/kaminari.rb` with the following:

```
Kaminari.configure do |config|
  config.page_method_name = :kaminari_page
end
```

2. Change the calls in your admin code from `.page` to `.kaminari_page`

If that isn't the case, then I might need an example application to track this down.

**Comment by quantavi** [comment]
@spohlenz Thank you! That was it. Now the subresource pagination works as a charm.
