### ISSUE TITLE
Search with scope of resource ?

### ISSUE THREAD

**Issue by hoangnv2107** [TrestleAdmin/trestle#205]
When i use Trestle.resource(:test, scope: Name) 
collection do
   Test.order(created_at: :desc)
 end

  search do |q|
    q ? collection.where("content LIKE ?", "%#{q}%") : collection
  end

It don't work ?

**Comment by spohlenz** [comment]
What is the specific error you are seeing? If there are no errors, then try running `bundle exec rails routes` to see what routes are being generated for the admin.

I don't see anything obviously wrong with your code. The only thing I would suggest is to use a pluralized form for the resource name (e.g. `Trestle.resource(:tests, ...)`) and to update the filename accordingly.

Also ensure that the admin file is also within a folder scope (e.g. the filename for this should be `app/admin/name/tests_admin.rb`).

**Comment by hoangnv2107** [comment]
oh yes, thanks you very much @spohlenz
