### ISSUE TITLE
How do i make with setup in Trestle use tinymce ?

### ISSUE THREAD

**Issue by hoangnv2107** [TrestleAdmin/trestle#207]
tinymce.init({
selector: ".tinymce", // change this to target the appropriate HTML control on your page
setup: function (editor) { // on the setup of the TinyMCE plugin, add a button with the alias 'addImage'
editor.addButton('addImage', {
text: 'Add Image', // the text to display alongside the button
icon: 'image', // the icon to display alongside the button
onclick: function () {
activeTextArea = editor; // onclick of this button, set the active textarea to that of which the button was pressed
$('#filePicker').modal('show'); // show the file picker modal
}
});
},

=> current , i use setup in trestle.rb

**Comment by spohlenz** [comment]
Answered in TrestleAdmin/trestle-tinymce#4.
