### ISSUE TITLE
'Can't verify CSRF token authenticity' when i try config with dropzonjs

### ISSUE THREAD

**Issue by hoangnv2107** [TrestleAdmin/trestle#209]
I think :" csrf can't pass'. Have you a way for it ? Thanks you very much.
<img width="963" alt="Screen Shot 2019-06-12 at 14 49 37" src="https://user-images.githubusercontent.com/45548185/59332825-54f09180-8d21-11e9-8ba0-89213eded440.png">

**Comment by spohlenz** [comment]
Make sure you are passing the X-CSRF-Token header. Try this SO link: https://stackoverflow.com/questions/39865170/dropzone-in-a-form-invalidauthenticitytoken/39865809#39865809
