### ISSUE TITLE
Trestle isn't including javascript custom files when it's used inside a Rails engine

### ISSUE THREAD

**Issue by vbrazo** [TrestleAdmin/trestle#210]
My javascript custom files aren't getting added to the admin dashboard when I connect `Trestle` in a Rails Engine. The files simply aren't being included in the project.

I read all the documentation and you don't explain how to integrate it in an engine. Any tips?

Do I need to add anything to my `Rails::Engine` object?

**Comment by spohlenz** [comment]
To keep Sprockets happy, you'll need to add your CSS/JS files to the precompile list.

Check out how trestle-search does it here:
https://github.com/TrestleAdmin/trestle-search/blob/master/lib/trestle/search/engine.rb#L4

This is in addition to the configuration hook which I'm assuming you already have in place:
https://github.com/TrestleAdmin/trestle-search/blob/master/config/initializers/trestle.rb#L4-L6

**Comment by vbrazo** [comment]
Your suggestion was great and helped me solve the problem. Thank you!

I was missing the `config.hook(:javascripts)` in the `components/my_engine/config/initializers/trestle.rb`.

If anyone gets stuck in this point, my solution looked like:

```ruby
# components/my_engine/config/initiailizers/trestle.rb
config.hook(:javascripts) do
   javascript_include_tag("trestle/shipping_same_as_billing.js")
end

# components/my_engine/app/assets/javascript/trestle/shipping_same_as_billing.js
Trestle.init(function(e, root) {
  $('#merchant_shipping_same_as_billing').click(function(){
     ....
  });
});

# components/my_engine/lib/my_engine/engine.rb
module MyEnglish
  class Engine < ::Rails::Engine
    config.assets.precompile << "trestle/shipping_same_as_billing.js"
  end
end
```
