### ISSUE TITLE
Nested routes for creating resources

### ISSUE THREAD

**Issue by andrerpbts** [TrestleAdmin/trestle#212]
Hi, 

Do you have an example of how I can create a new record using a nested route? For example: in the demo site, it lists the seasons of a TV show in a tab, inside the TV Show resource, and this page lets me edit records there. But it's not clear how to add a new season through this same page, opening the dialog form, which will automatically set the tv_show relationship to the new season created. 

Is this a thing already possible in the current version or it needs some customization? Can you help me?

**Comment by spohlenz** [comment]
Here's a guide on how to do this currently: https://github.com/TrestleAdmin/trestle/wiki/Has-Many-Relationship-Tab. It definitely does need streamlining, which is what subresources will eventually accomplish.

If your child models are simpler, you may prefer this solution which uses [Cocoon](https://github.com/nathanvda/cocoon): https://github.com/TrestleAdmin/trestle/issues/19#issuecomment-347499096. This is also eventually going to be wrapped in a nicer DSL and built into Trestle.

**Comment by andrerpbts** [comment]
Thank you, it will help a lot. 👍
