### ISSUE TITLE
disabled datepicker allows to clear

### ISSUE THREAD

**Issue by balbesina** [TrestleAdmin/trestle#213]
When my datetime_field is marked as disabled: true I am still able to see clear button and it allows to clear the field.
```
form do
  datetime_field :created_at, disabled: true
end
```
See app/assets/javascripts/trestle/components/_datepicker.js:2 it checks only for data-allow-clear.

**Comment by spohlenz** [comment]
Thanks for reporting. I also found and fixed some related issues with readonly/disabled date pickers and select fields.
