### ISSUE TITLE
Authorization and content filtering

### ISSUE THREAD

**Issue by WhatTheChad** [TrestleAdmin/trestle#217]
I need to support multiple administrators in a multi-tenant environment. 

They will have similar functionality available to each, but will need all content (entity lists, etc) filtered by their associated company_id.

For example they will each need:
1. A list and CRUD for stores that exist inside their company
2. A list and CRUD for users of the associated desktop/mobile app

And 0 access to the records that exist within other client's companies.

And of course will need a "super-admin" that can create the companies with an admin for each.

Is there any support for this built in that I'm not seeing?

Anything coming soon?

Thanks!!

**Comment by spohlenz** [comment]
Full support for this type of setup is definitely coming (in trestle-auth) and is fairly high on my priorities list now. However it looks like what you are hoping to do should be achievable without the proposed future enhancements.

A couple of things that will be key:

1) Override the `collection` block to scope the admin to the current user:

```ruby
Trestle.resource(:stores) do
  collection do
    current_user.company.stores
  end
end
```

2) Use a `before_action` to prevent access to admins to users with insufficient privileges:

```ruby
Trestle.resource(:administrators) do
  before_action do
    unless current_user.super_admin?
      flash[:error] = "Access denied."
      redirect_to Trestle.config.root
    end
  end
end
```
