### ISSUE TITLE
Adding sidebar without filling form fields?

### ISSUE THREAD

**Issue by skamsie** [TrestleAdmin/trestle#218]
I am trying to add a sidebar but unless I also explicitly add the fields for the form, the form is empty. For example, the following (see code below) renders the sidebar, but there is no field in the form. I would like to have the default ones (all) without writing everything, like it happens if you do not add the `form` block. Any way to do it?

```
form do |user|
  sidebar do
    render "admin/shared/comments"
  end
end
```

**Comment by skamsie** [comment]
I have found a hack that works in my case, since I need to render the same sidebar for all resources. I am overwriting the `app/views/trestle/application/_layout.html.erb` as follows:

```html.erb
<%= render "header", hide_breadcrumbs: local_assigns.fetch(:hide_breadcrumbs, false) if local_assigns.fetch(:header, true) %>

<div class="main-content-area">
  <%= render "trestle/flash/flash" %>
  <%= render "utilities" %>
  <%= render "tabs" %>

  <% if local_assigns.fetch(:wrapper, true) %>
    <%= container do |c| %>
      <%= yield %>

      <% c.sidebar do %>
        <% unless controller_path == "admin/auth/administrators" %>
          <%= render "admin/shared/comments" %>
        <% end %>
      <% end if ["edit", "show"].include?(action_name) %>
    <% end %>
  <% else %>
    <%= yield %>
  <% end %>
</div>
```

**Comment by spohlenz** [comment]
Here's a shorter way that is probably the best solution currently:

```ruby
form do |user|
  concat Trestle::Form::Automatic.new(admin).render(self, user)

  sidebar do
    render "admin/shared/comments"
  end
end
```

I'm currently reworking the automatic form and table generators so I'll keep this in mind to see if an even cleaner solution is possible.
