### ISSUE TITLE
hidden_field in form

### ISSUE THREAD

**Issue by waghih** [TrestleAdmin/trestle#219]
Hi. Is there a method for hidden_field, or do i have to create a custom field for that?

**Comment by jevin** [comment]
You can use `hidden_field :employee_id` in your form block.

You can find the list of all form fields here: https://github.com/TrestleAdmin/trestle/tree/master/lib/trestle/form/fields

**Comment by dexter-atob** [comment]
@jevin was `hidden_field` removed?
