### ISSUE TITLE
Postgres Array serialises with extra null value

### ISSUE THREAD

**Issue by richardvenneman** [TrestleAdmin/trestle#22]
I was excited to see [here](https://github.com/TrestleAdmin/trestle/pull/15#event-1213171982) that Postgres array support has landed. So I updated the ref in my Gemfile to [2f202a5](https://github.com/TrestleAdmin/trestle/commit/2f202a5e243fdf7e5419a4a16f403c85d9d36556).

I have a model with an array column like:
```ruby
t.integer "payment_methods", default: [0], array: true
```

Before save, the column value is:

```ruby
model.payment_methods.inspect
=> "[0]"
```

When I save the value becomes:
```ruby
model.payment_methods.inspect
=> "[nil, 0]"
```

![screen shot 2017-08-20 at 14 38 52](https://user-images.githubusercontent.com/75705/29494952-4da9a076-85b5-11e7-99d3-3c209e22240c.png)

This is my admin config:

```ruby
select :payment_methods, nil, {}, { multiple: true, data: { tags: true, select_on_close: true }}
```

**Comment by spohlenz** [comment]
This is an unfortunate side effect in the way Rails handles multiple select fields. To work around this, you can filter out the empty values in your model:

```ruby
def payment_methods=(methods)
  super(methods.reject(&:blank?))
end
```

**Comment by richardvenneman** [comment]
Ah I see, thanks @spohlenz!

I created a reusable ActiveRecord concern which redefines this method for all array fields:

```ruby
module ArraySerializable
  extend ActiveSupport::Concern

  included do
    columns.select(&:array?).each do |attr|
      define_method("#{attr.name}=".to_sym) do |value|
        value = value.reject(&:blank?) unless value.nil?
        super(value)
      end
    end
  end
end
```
