### ISSUE TITLE
Custom column for the table block

### ISSUE THREAD

**Issue by jevin** [TrestleAdmin/trestle#220]
Is there anyway to create a custom column presently?

Something that could transform this:
```
column :poster, header: nil, align: :center, class: "poster-column" do |movie|
  admin_link_to(image_tag(movie.poster_url("w154"), class: "poster"), movie) if movie.poster?
end
```
Into this:
```
image_column :poster
```

**Comment by jevin** [comment]
I figured out how to do this. Here's how:

1. Register an additional column type in `trestle.rb`. Since we do not have a helper available in the configuration. We have to extend the table's builder class by adding the following at the bottom of `trestle.rb`
```
class Trestle::Table::Builder
  def sortable_column(field, options)
    table.columns << SortableColumn.new(table, field, options)
  end
end
```

2. Create the column class. I created it in `app/columns/` since custom form elements go in `app/fields/. In my case the name was `sortable_column.rb`

```
class SortableColumn < Trestle::Table
  attr_reader :table, :field, :options

  def initialize(table, field, options)
    @table, @field, @options = table, field, options
  end

  def renderer(template)
    Renderer.new(self, template)
  end

  class Renderer < Trestle::Table::Column::Renderer
    def header
      "Header"
    end

    def content(instance)
      "Content"
    end
  end
end
```

Notes:
* To get the field name, you have to use `@column.field` inside the `content` method. If you have `sortable_column :position`, then `:position` is the field name.
* If you want to use `content_tag` in the content, you'll have to include `include ActionView::Helpers::TagHelper` and `include ActionView::Context`. You'll get an error if you do not include the Context.

**Comment by LimeBlast** [comment]
Hi @jevin - I notice you've created a `SortableColumn`, and are referencing a `position` field - is this because this solution lets you reorder entries in the list?

If so, is there any more code required to make this work, as being able to reorder items in a list would be really helpful for my current app. Thank you.

**Comment by jevin** [comment]
Hey @LimeBlast, the code allows a user to reorder table rows. You guessed correctly, there are quite a few missing pieces to make it work. I'll have to do a full write up for that. I'll see if I can write a page on the WIKI.

**Comment by spohlenz** [comment]
I'm really pleased you were able to make this work without much code. I think at some point I will add some registration hooks so that the builder doesn't need to be monkey-patched, but otherwise what you've done is nice and neat.

Add me to the list of people keen to see a writeup on the Wiki! 😃

**Comment by LimeBlast** [comment]
Hi again @jevin - did you have any joy with the write up on making sortable columns work? Thank you.

**Comment by jevin** [comment]
Hey @LimeBlast and @spohlenz 

I finally got around to posting on the WIKI: https://github.com/TrestleAdmin/trestle/wiki/Has-Many-Relationship-Tab-(with-Sorting)

Let me know if there's any change you'd like me to do. I'd love for somebody else to test it out too, just in case I forgot anything.

**Comment by LimeBlast** [comment]
That's fantastic, thank you @jevin - I'm not currently on the project that used Trestle, but I will be again in a couple of weeks, so I'll give this a test then.

**Comment by LimeBlast** [comment]
Hi @jevin - I'm working on the project again, so I've just given this a try - and it seems to be working as intended.

I had some trouble initially, as I missed passing the `sortable-table` class to the table., but after I fixed this, I was rolling.

Thank you.

**Comment by jevin** [comment]
@LimeBlast Thanks for trying it out (and confirming that it works 😄). I clarified the WIKI to specify that the `sortable-table` class is needed for the drag and drop capabilities.
