### ISSUE TITLE
Creating Devise Users with Trestle

### ISSUE THREAD

**Issue by RailsCod3rFuture** [TrestleAdmin/trestle#221]
I know this may seem like a trivial question, but what is the best approach to generating users for devise? I have an app that I must seed users into. It will be intranet based.

**Comment by spohlenz** [comment]
This definitely depends on how many users you are seeding your database with.

For just a couple of users, I'd suggest just creating them via the Rails console. If you have just 
a few more, then you could enter them by hand within a Trestle admin, and for many users you could look at importing from a CSV file.
