### ISSUE TITLE
Separate new and edit forms

### ISSUE THREAD

**Issue by LimeBlast** [TrestleAdmin/trestle#222]
Hi, my apologies if this has been answered elsewhere - I did have a look, but wasn't able to find it.

Is there an easy way to define separate new and edit forms?

We've got some instances of data which is auto-generated upon creation (so don't need a field shown on the new form), but would like the ability to edit them (so they do need to show on the edit form).

Is this something I'm able to do with Trestle? Thank you.

**Comment by LimeBlast** [comment]
Update: I've had a quick play myself, and have come up with this:

```ruby
  form do |category|
    text_field :title
    text_field :icon, placeholder: 'fa fa-star'

    unless category.new_record?
      text_field :slug
    end
  end
```

This seems to work, but I'd be interested in knowing if there's a better way. Thanks.

**Comment by jevin** [comment]
The way you did it is the only way I know of.

**Comment by spohlenz** [comment]
That's definitely the solution I would recommend in your situation, and is what I use in the vast majority of cases. I often use a similar approach for creating child models where I show a parent association select field within the new resource form but not when editing. I also sometimes do the reverse of your example where I allow the user to enter a slug on creation but disallow editing if the model has been persisted.

There are some situations where I do want to have entirely separate show and edit views. A prime example of this is an Order model, where I usually just want to have the read-only view showing the addresses, line items, etc. but then need the ability to edit certain details if required. In this case I create a separate show template, and manually create links/buttons to the edit form.
