### ISSUE TITLE
Linking to different resource based on single table inheritance

### ISSUE THREAD

**Issue by LimeBlast** [TrestleAdmin/trestle#223]
I've got an app with a basic structure where:

`Page` has_many `:blocks`
`Block` belongs_to `:page`

but also

`MarkdownBlock` inherits from (STI) `Block`

To allow the first two to work within trestle, I've got the following in my `pages_admin.rb` file:

```ruby
  form do |resource|
      # ...

      tab :blocks, badge: resource.blocks.size do
        table resource.blocks, admin: :blocks do |row|
          column :heading, link: true
          column :content
          column :type
          actions
        end
    end
```

which lets me link to the `blocks_admin.rb` form, but what I'd like is for the link to recognise that some of the records are going to be `MarkdownBlock` records, and link to the `markdown_block_admin.rb` instead.

With this in mind, is there some way I can drop a conditional on the

```ruby
table resource.blocks, admin: :blocks do
```

line, to make it selectively use `admin: markdown_blocks` instead (because the form for `MarkdownBlock` is formatted differently)?

------------

I did some experiments, and found the `admin` flag can be used on the

```ruby
column :heading, link: true
```

line instead, so tried to find the model data for the `row` being rendered, but didn't get very far with it.

I'd appreciate any help you're able to give. Thank you.

**Comment by spohlenz** [comment]
In this case, I'd suggest not using the auto-linking (which doesn't support a dynamic admin option), and instead pass a block to the column method.

Something like this should work:

```ruby
column :heading do |block|
  admin_link_to(block.heading, block, admin: block.is_a?(MarkdownBlock) ? :markdown_blocks : :blocks)
end
```
