### ISSUE TITLE
Custom search & Sorting in table

### ISSUE THREAD

**Issue by jmsong** [TrestleAdmin/trestle#224]
Hi,

Currently I implemented custom search function with several filter conditions, it works well with collection block:

collection do

    Article.includes(:category, :tags, article_tags: [:tag])
           .accessible_by(current_ability, :read)
           .filter(
             params[:q],
             params[:field],
             params[:admin_option],
             params[:category_option],
             params[:visible],
             params[:state],
             params[:is_featured]
           )
           .order(updated_at: :desc)
  end

But when I combined with built-in sorting feature of table header like:
`column :title, link: true, sort: :title`

Then I'm facing with issue that, the result of search function will be reset after triggering sorting by clicking on header of the table.

As my understanding, URL of search function let's say:
http://localhost:3000/admin/articles?q=abc&field=title&visible=&state=&admin_option=&category_option=&is_featured=
will be changed to:
http://localhost:3000/admin/articles?order=asc&q=abc&sort=title
after I click sort header.

Please show me how to combine those two functions (search and sort).

Thanks in advanced.

**Comment by spohlenz** [comment]
What you want to look at here is the `config.persistent_params` option within your `config/initializers/trestle.rb`. This will ensure that those additional params are kept when the table is sorted or paginated. e.g.

```ruby
config.persistent_params += [:field, :admin_option, :category_option, :visible, :state, :is_featured]
```

**Comment by jmsong** [comment]
Thanks so much for your guide @spohlenz

**Comment by karan-ta** [comment]
How can I make a form that passes in the params on form submit? 

The form should have select boxes pre filled with options.
