### ISSUE TITLE
redirect to showing message instrad of redirecting in custom action

### ISSUE THREAD

**Issue by randomCharacter** [TrestleAdmin/trestle#225]
After finishing create action in controller, the message ```200 (OK)``` with text
```
Turbolinks.clearCache()
Turbolinks.visit("https://bot-manager-0.herokuapp.com/admin/instances", {"action":"replace"})
```
is shown instead of redirecting.
```
 controller do
   def create
      flash[:success] = "The instance was successfully created."
      redirect_to admin.path(:index)
    end
  end
```

**Comment by spohlenz** [comment]
Try specifying `turbolinks: false` on the call to `redirect_to`.

```ruby
controller do
  def create
    flash[:success] = "The instance was successfully created."
    redirect_to admin.path(:index), turbolinks: false
  end
end
```

I do need to look into this further as to why (and when) it is required, and hopefully implement some workarounds that will eventually mean this is no longer necessary.

**Comment by randomCharacter** [comment]
Thank you, that solved it.
