### ISSUE TITLE
Custom action get value from other db table and use it as param for custom action

### ISSUE THREAD

**Issue by hdbreaker** [TrestleAdmin/trestle#230]
I'm creating an import function in order to get the data from table B and import it to Table A, to this I created a custom function that must receive the current resource id and also the selected template title from a drop-down menu.

<img width="272" alt="Screen Shot 2019-08-06 at 3 20 51 PM" src="https://user-images.githubusercontent.com/5799585/62570963-2d6c0000-b85e-11e9-8643-469d00efa824.png">

my code looks like the following:

```
sidebar do
  select :title, Template.pluck(:title), {}
  static_field :_ do
    link_to('Import', admin.path(:import, id: resource.id, params: {"select_title": "TEMPLATE_TITLE_HERE"}), method: :post, class: "btn btn-warning btn-block")
   end
end
```
I need a way to select template title from the dropdown menu and set it in "TEMPLATE_TITLE_HERE" value to call my custom function.

Can you explain to me how to do that?

Regards,

**Comment by spohlenz** [comment]
This will require some custom JavaScript to achieve. I'd suggest binding an event handler to the `ajax:before` event on the link, and then setting the `data-params` attribute on the link.

Here are a couple of resources with similar situations (non-Trestle but still using Rails/jQuery UJS):

* https://github.com/rails/jquery-ujs/issues/470
* https://stackoverflow.com/questions/38960084/rails-ujs-adding-form-params-to-link-in-ajaxbefore-hook
