### ISSUE TITLE
About selectable_column

### ISSUE THREAD

**Issue by hoangnv2107** [TrestleAdmin/trestle#231]
i have added a selectable_column to project. But it error same with https://github.com/TrestleAdmin/trestle/issues/163

You have a by the way for it. Please help me. thanks you very much
<img width="719" alt="Screen Shot 2019-08-10 at 02 01 25" src="https://user-images.githubusercontent.com/45548185/62802810-0558f700-bb13-11e9-808b-39a9f786e0d9.png">

**Comment by hoangnv2107** [comment]
@spohlenz if you know it, you can suggest me. Thanks you.

**Comment by spohlenz** [comment]
This is fixed in master but I haven't had a chance to put out a new release yet. I should finally have time this week though.

Until then you can update your Gemfile to point to the GitHub repo:

```ruby
gem 'trestle', github: 'TrestleAdmin/trestle'
```

**Comment by hoangnv2107** [comment]
oh yes, thanks you very much Mr @spohlenz
