### ISSUE TITLE
Error dialog shown for respond_to js format

### ISSUE THREAD

**Issue by waghih** [TrestleAdmin/trestle#232]
Hi,

How can I prevent the error dialog modal from showing for respond_to js format when using ajax remote form?

<img width="616" alt="Screenshot 2019-08-12 at 11 24 56 PM" src="https://user-images.githubusercontent.com/15120020/62877517-c963a300-bd59-11e9-9277-69c3a8c777ee.png">

**Comment by spohlenz** [comment]
This should now be fixed in the 0.8.13 release.
