### ISSUE TITLE
Version of Font awesome

### ISSUE THREAD

**Issue by metronom72** [TrestleAdmin/trestle#235]
I'm trying to use icons from Font Awesome and some of them are shown, and some of them not.

Do you have plans for updating font awesome in dependencies?

**Comment by petitkriket** [comment]
Could it be because some are available in fontawesome 5 free and other such as fas or fal are only available with pro version ?

**Comment by spohlenz** [comment]
The major asset overhaul of #195 has now been merged into master, which includes the latest version of FontAwesome.
