### ISSUE TITLE
I18n locales model translation for french raise an exception

### ISSUE THREAD

**Issue by pifleo** [TrestleAdmin/trestle#238]
Hi,

When trying to set the page title to use the i18n model activerecord translation, following Rails patterns (https://guides.rubyonrails.org/i18n.html#translations-for-active-record-models) I get an exception in the admin

Trestle (0.8.13) - last version (we had the problem with the previous one)
Ruby: 2.6.3p62

```
ActionView::Template::Error (comparison of Symbol with 0 failed):
```

Raising exception:
```yaml
# config/locales/activerecord.fr.yml
fr:
  activerecord:
    models:
      article:
        one: Article
        other: Articles
```

Working:
```yaml
# config/locales/activerecord.fr.yml
fr:
  activerecord:
    models:
      article: Article(s)
```

Exception Trace
```
rails-i18n (5.1.3) lib/rails_i18n/common_pluralizations/one_upto_two_other.rb:7:in `>='
rails-i18n (5.1.3) lib/rails_i18n/common_pluralizations/one_upto_two_other.rb:7:in `block in rule'
i18n (1.6.0) lib/i18n/backend/pluralization.rb:36:in `pluralize'
i18n (1.6.0) lib/i18n/backend/base.rb:49:in `translate'
i18n (1.6.0) lib/i18n.rb:190:in `block in translate'
i18n (1.6.0) lib/i18n.rb:186:in `catch'
i18n (1.6.0) lib/i18n.rb:186:in `translate'
activemodel (5.2.3) lib/active_model/naming.rb:190:in `human'
trestle (0.8.13) lib/trestle/model_name.rb:49:in `human'
trestle (0.8.13) lib/trestle/model_name.rb:29:in `plural'
trestle (0.8.13) lib/trestle/resource.rb:108:in `translate'
trestle (0.8.13) lib/trestle/admin.rb:17:in `method_missing'
trestle (0.8.13views) trestle/resource/index.html.erb:
```

![image](https://user-images.githubusercontent.com/1569526/64641315-35463380-d40c-11e9-92ba-f1ce587896e3.png)

It's caused by this line: https://github.com/TrestleAdmin/trestle/blob/master/lib/trestle/model_name.rb#L29 where the `:many` option is passed.

I found a similar error here: https://github.com/spree-contrib/spree_i18n/issues/505
Fixed here: https://github.com/JDutil/spree/commit/fd0b057e956490500b5295777947f080c07b1ed9

So for a quick monkey patch in my project ...
```ruby
# app/lib/trestle/model_name.rb
module Trestle
  class ModelName
    I18N_PLURAL_MANY_COUNT = 2.1

    def plural(options={})
      if i18n_supported? && i18n_pluralizations_available?
        human(default_plural, { count: I18N_PLURAL_MANY_COUNT }.merge(options))
      else
        default_plural
      end
    end
    alias_method :pluralize, :plural
  end
end
```

```ruby
# app/admin/article.rb
require 'trestle/model_name'

Trestle.resource(:article) ...
```
And then it's working with the Rails pattern form model translation

Do you think something can be fixed in TrestleAdmin ?

**Comment by spohlenz** [comment]
Thank you for reporting. This should now be fixed in d61193f.
