### ISSUE TITLE
Dependent fields / custom JS

### ISSUE THREAD

**Issue by subdigital** [TrestleAdmin/trestle#24]
I know documentation is still coming, so I've been getting up to speed by reading the code and looking at the examples.

For field dependencies where you have some dynamic control over what is required / displayed if a user selects a certain choice, how do you handle this?

For instance, if the user checks a box, I need to display another field for them to fill out. How do you handle these cases?

Thanks!

**Comment by subdigital** [comment]
Ah, I see there's a custom js file in there that gets included by default.

**Comment by sithik-sharedlabs** [comment]
@subdigital can you please direct me where I can import custom js?

**Comment by subdigital** [comment]
Look for `app/assets/javascripts/trestle/custom.js.coffee`. You can include your own js there.
