### ISSUE TITLE
Impossible to manually set label on radio button

### ISSUE THREAD

**Issue by willtcarey** [TrestleAdmin/trestle#240]
I'm trying to set a label for a `radio_button` form input that is different from the `tag_value`. This looks like it should be possible by passing a `label` option in to the radio button,
`options[:label] || tag_value.to_s.humanize` from `radio_button.rb`

So I tried the following:
```ruby
radio_button :test, "1", label: "Testing"
```
Which gave the following

![image](https://user-images.githubusercontent.com/880387/65056677-eb42dd80-d936-11e9-8ecf-97d301b8f2d8.png)

And it ignored my label :(

Looking into it, it looks like in `Trestle::Form::Field` we delete all the "wrapper" options and store them in the `@wrapper` instance variable, [here](https://github.com/TrestleAdmin/trestle/blob/master/lib/trestle/form/field.rb#L42). So the `label` option is deleted before it get's used in the `radio_button` rendering. It appears `check_box.rb` works around this by merging the options in a second time after the `super` call is made, [here](https://github.com/TrestleAdmin/trestle/blob/master/lib/trestle/form/fields/check_box.rb#L10).

Would you take a pull request that did something similar for the radio buttons or do you have something else in mind for how to solve this?

**Comment by spohlenz** [comment]
I've reworked some of the `check_box` & `radio_button` behavior in the latest updates to Bootstrap 4 (#195), which has recently been merged into master.

I've just given your example a quick test and it appears to now be working properly with those changes.

**Comment by willtcarey** [comment]
@spohlenz Ah yes I see what you did, that looks great. Thanks for your work!
