### ISSUE TITLE
Custom action launching modal dialog

### ISSUE THREAD

**Issue by dboucqueau** [TrestleAdmin/trestle#248]
Hello,

I'm trying to figure out how to have a custom action display a modal dialog. I looked at the wiki and in the issues, but did not find what I want to do.

I use the standard "out-of-the-box" approach for the crud actions on Users of my app, and all works fine. In my use case, I also need to add a custom action on a user ("suspend user") that changes its status from active to suspended. I have been able to add that custom action when it just does the change on the user and redirects to the user page (or user collection).

Now I'd like to improve the UC by asking the admin to enter the reason for the suspension when he's suspending a user, via a modal launched by the custom action.

In my `users_admin.rb`, I added the routes:

    routes do
      get     :suspend, on: :member
      post    :do_suspend, on: :member
    end

I also added controller actions (controller do... def suspend...end def do_suspend...end end).
Finally in my partial displaying the sidebar, I have coded the link to the action to ask for a dialog like this:
`<%= link_to('Suspend', admin.path(:suspend, id: instance.id), method: :get, class: "btn btn-primary btn-block", data: {behavior: "dialog"}) %>`

Well, documentation of Trestle being what it is, I tried to add a `app/views/admin/users/suspend.html.erb` view to support the form, but I can't make it work as a dialog: it tries to load the view as a dialog (spinner, and the modal is very briefly displayed) but then falls back to a standard page. If I try to add the whole Bootstrap modal plumbing in that form, nothing is displayed at all.

I looked at [https://github.com/TrestleAdmin/trestle/issues/55](url) but did not figure out.

Thanks in advance for any insight you may have.

**Comment by spohlenz** [comment]
Here's a quick overview of how I would do this currently. I aim to make this easier in future.

Simple service class (makes the form slightly easier):

```ruby
class SuspendUser
  attr_accessor :reason

  def initialize(user)
    @user = user
  end

  def suspend!
    # Do the suspension
  end
end
```

Within your admin:

```ruby
controller do
  def suspend
    load_instance

    if request.post?
      suspension = SuspendUser.new(instance)
      suspension.reason = params[:reason]
      suspension.suspend!

      flash[:message] = "User suspended (#{suspension.reason})."
      redirect_to admin.instance_path(instance)
    end
  end
end

routes do
  match :suspend, on: :member, via: [:get, :post]
end
```

Linking to the dialog:

```erb
<%= admin_link_to "Suspend", instance, action: :suspend, class: "btn btn-primary btn-block", data: { behavior: "dialog" } %>
```

The dialog view (`app/views/admin/users/suspend.html.erb`):

```erb
<% content_for(:title, "Suspend User") %>

<% toolbar(:primary) do |t| %>
  <%= t.button "Suspend", style: :success %>
<% end %>

<%= form_for(SuspendUser.new(instance), as: :suspension, builder: Trestle::Form::Builder, url: admin.instance_path(instance, action: :suspend), method: :post, remote: false) do |f| %>
  <%= render layout: "trestle/application/dialog" do %>
    <p>Are you sure you want to suspend this user?
    <%= f.text_field :reason, name: :reason %>
  <% end %>
<% end %>
```

**Comment by carlson** [comment]
@spohlenz I followed your instructions and everything worked except I get the same behavior that @dboucqueau described:  "it tries to load the view as a dialog (spinner, and the modal is very briefly displayed) but then falls back to a standard page". btw - great project!
