### ISSUE TITLE
Ability to Scope by Subdomain - Kind of a multi tenancy back-end

### ISSUE THREAD

**Issue by ziyan-junaideen** [TrestleAdmin/trestle#249]
I am building a multi tenancy application and curious about how to use Trestle in it. I have some thing like this.

```
# Corresponds to sub domains...
# tenant1.myapp.com
class Tenant
  has_many :posts
end

class Post
  belongs_to :tenant
end

```
When displaying posts, I would like to scope them by the `request.subdomain`. How can this be done?

some thing like `tenant1.myapp.com/admin/posts` to do some thing like `Posts.join(:tenant).where(tenants: { subdomain: request.subdomain })`.

I was thinking making request object available in a custom `scope'`might do the trick?

If its some thing you are interested, I can have a look and see  when I am free, which I might not if I have to muster an admin interface for the app.

**Comment by spohlenz** [comment]
The `collection` (and other) blocks are executed in a context that allows access (via `method_missing`) to controller methods such as `request` or `current_user`, so the following should work inside your posts admin:

```ruby
collection do
  Posts.join(:tenant).where(tenants: { subdomain: request.subdomain })
end
```

**Comment by ziyan-junaideen** [comment]
Great. Thank you!
