### ISSUE TITLE
Check box field with custom switch class

### ISSUE THREAD

**Issue by McRipper** [TrestleAdmin/trestle#255]
I can see that in the CheckBoxHelpers is possibile to pass che switch option to che checkbox, but seems the option is never taken into consideration

`check_box :published, { custom: true, switch: true }`

What is the correct way to use it?

Thanks

**Comment by spohlenz** [comment]
The following should be sufficient, as `:custom` defaults to true in the master branch:

```ruby
check_box :featured, switch: true
```

<img width="100" alt="Screen Shot 2019-11-07 at 8 59 18 am" src="https://user-images.githubusercontent.com/7600/68343563-fcd98200-013c-11ea-9786-fa3a93107a73.png">

Note that this hasn't yet been released as a gem, so you'll need to point your Gemfile to the git repo. I'm considering doing a release tomorrow though as all of my apps are now running on master without any issues.

**Comment by spohlenz** [comment]
Trestle 0.9.0 has now been released to rubygems.org.
