### ISSUE TITLE
Custom File Field seems broken

### ISSUE THREAD

**Issue by simonc** [TrestleAdmin/trestle#256]
Hi!

I recently upgraded to v0.9.0 and it seems the custom file field behavior is broken.

**What I do:**

I call `file_field` for a specific attribute.

**What I expected:**

When I click on the field I can select a file and when I do its name shows in the field instead of the placeholder text.

**What actually happens:**

When I click on the field I can select a file but the placeholder text doesn't change.

**Steps to reproduce:**

I created a specific app with a default Trestle setup, a `Thing` model with a `file` attribute powered by Carrierwave. You can inspect it at https://github.com/simonc/trestle-custom-file-bug-demo

Let me know if I can be of any additional help.

Thanks! ❤️ 

Edit: I think the `init` function of `bsCustomFileInput` is not called at all but I might be wrong.

**Comment by spohlenz** [comment]
Thanks for reporting. This looks to be a broader issue with the JS not being initialized when Turbolinks is not available.

I'll get that fixed and push out a new release ASAP.

**Comment by simonc** [comment]
@spohlenz Thanks! 😊

**Comment by spohlenz** [comment]
Version 0.9.1 has now been released.

**Comment by simonc** [comment]
Just tried it and it works like a charm. Thank you!
