### ISSUE TITLE
Clicking a column heading in a tab loads the first column

### ISSUE THREAD

**Issue by swrobel** [TrestleAdmin/trestle#258]
If you click on a column heading, it applies the sort, but navigates back to the main tab.
![2019-11-22 18 26 21](https://user-images.githubusercontent.com/157270/69471588-a92e8180-0d55-11ea-8721-dcae826a96de.gif)

**Comment by spohlenz** [comment]
There is actually something slightly different going on here.

The intention (currently) is actually for tables nested in the form like this to not be sortable. And in fact when a table is defined with a block, the `:sortable` option defaults to false and the sort links are not rendered.

However in the example you posted from the demo, the table defined within `CreditsAdmin` is referenced directly [(source)](https://github.com/TrestleAdmin/RailsFlixDemo/blob/master/app/admin/movies_admin.rb#L58), inheriting its options (with `:sortable` set to true). I will need to find some way to rectify this.

Of course what is really desired here is for the table to be sorted (likely via AJAX, it isn't actually sorting at all in the demo), along with other things like pagination and child record creation. This is on the roadmap with a 'subresources' like feature.

**Comment by spohlenz** [comment]
I've now fixed the core issue of the table options not being correctly passed down in cbc74f4. I'll close the issue now but rest assured the subresources feature is still on the roadmap.
