### ISSUE TITLE
undefined method `career_path`

### ISSUE THREAD

**Issue by LimeBlast** [TrestleAdmin/trestle#260]
I'm probably doing something dumb here, but I'm trying to provide a preview link from the sidebar to the article being edited. My code looks something like this:

```
      sidebar do
        concat link_to('Preview', career_path(resource))
        text_field :title
        text_field :slug
        # etc.......
      end
```

The issue is the admin panel doesn't know how to resolve the `career_path` method, which I'm guessing is because I've not included some routing helpers or something - but I don't know how to do that.

-----------

As an aside, it would be handy to have some an optional "Preview" link for each item, maybe on the edit form (perhaps near the "Save" and "Delete" buttons), and/or perhaps on the table view?

**Comment by McRipper** [comment]
Just added yesterday to the wiki

https://github.com/TrestleAdmin/trestle/wiki/How-To:-Preview-link

**Comment by LimeBlast** [comment]
Fantastic, thank you.
