### ISSUE TITLE
How to override admin views of model

### ISSUE THREAD

**Issue by rcholody** [TrestleAdmin/trestle#264]
It is possible to override or add new button in class="content-header-toolbars" in admin form views of model? I have created file in /app/views/trestle/users/edit.html.erb directory. Then I have tried to add new custom button above Save and Delete but it doesn't work.

**Comment by spohlenz** [comment]
The easiest way is to add it within your form block:

```ruby
form do |instance|
  # Optionally pass clear: true to remove the default buttons
  toolbar(:primary, clear: true) do |t|
    # Render a button -- you might need to add some custom JS to achieve what you want
    t.button "Custom Button", style: :info, data: { foo: "bar" }

    # Render a link styled as a button
    t.link "Custom Link to Instance", instance, action: :edit, icon: "fas fa-star", style: :warning
    t.link "Custom Link to URL", "https://...", icon: "fas fa-star", style: :secondary
  end

  toolbar(:secondary) do |t|
    # Same syntax for the secondary toolbar which is rendered with smaller buttons
  end
end
```

Overriding the view will also work but might potentially break with future updates. In your case, it looks like the file path was wrong -- the default scope is admin and the default action is show, so your view should be at `app/views/admin/users/show.html.erb`.
