### ISSUE TITLE
Is it possible to use javascript_tag in custom form field?

### ISSUE THREAD

**Issue by rcholody** [TrestleAdmin/trestle#267]
I have worked on custom form field that gonna display the google maps and get latitude and longitude after users clicked mark. I have tried to use javascript_tag but then realised that I can use only content_tag. To handle those values I need to use javascript. Is it possible to approach that with specific custom form field?

**Comment by spohlenz** [comment]
When using a `form` block, it is possible to use helpers like `javascript_tag`. However you will need to prepend them with `concat` to ensure that their output is appended to the form.

```ruby
form do |instance|
  concat javascript_tag("Your JS here...")
  # or 
  concat javascript_include_tag("path/to/js/file")
end
```
