### ISSUE TITLE
Trestle + Mobility

### ISSUE THREAD

**Issue by rcholody** [TrestleAdmin/trestle#268]
I have used mobility to mapping translated attribute accessors (readers and writers) to an abstract pluggable “backend”, which encapsulates (and isolates) all the storage logic. It give me functionality like this: 
post = Post.first
post.title_en
#=> "Mobility"
post.title_ja
#=> "モビリティ"
Is it possible to change the language for field in a given model when entering data into it?

**Comment by spohlenz** [comment]
If you haven't seen it already, Richard Venneman has done a great job with the `trestle-mobility` plugin. https://github.com/richardvenneman/trestle-mobility

It should do exactly what you want with a very nice UI to go with it.
