### ISSUE TITLE
Compatability issues with friendly_id gem

### ISSUE THREAD

**Issue by joeczucha** [TrestleAdmin/trestle#27]
I'm using the popular [FriendlyId gem](https://github.com/norman/friendly_id) in conjunction with Trestle but there seems to be an issue with the way that it handles finding models.

FriendlyId gem rewrites the `to_param` method to use a slug rather than an ID. This part is working fine in the dashboard: I can see that the data-url attribute of a row is set to, for example, `/admin/people/joe-czucha` rather than `/admin/people/1`.

However, clicking a row gives the following error:

> Couldn't find Person with 'id'=joe-czucha

From the FriendlyId documentation, I found the following:

> Finders are no longer overridden by default. If you want to do friendly finds, you must do Model.friendly.find rather than Model.find.

So it looks like the error is because Trestle is using Model.find (rather than the new Model.friendly.find). I was wondering whether it's worth including a configuration option to allow one to specify a customised model finder method? I appreciate that this might be an edge case, but if there is one gem that does this then there are bound to be others.

The other possible solution, also from the FriendlyID docs:

> You can however restore FriendlyId 4-style finders by using the :finders 

This means that Model.find will continue to work and, in theory, Trestle should be able to handle it out-of-the-box. Unfortunately this addon doesn't actually seem to be working for me at the moment so I've not been able to test it properly.

Thanks again for your work on Trestle, it really is awesome.

Steps to reproduce:

1. Create a (working) Trestle project

		rails new friendlytrestle && cd friendlytrestle
		rails g model Person name:string slug:string:uniq
		rake db:migrate

		gem 'trestle' (-> Gemfile)
		bundle

		rails generate trestle:install
		rails generate trestle:resource Person

		http://localhost:3000/admin

2. Add a person using Trestle. You can view them using `http://localhost:3000/admin/people/1`

3. Install FriendlyId

		gem 'friendly_id', '~> 5.1.0' (-> Gemfile)
		bundle

		rails g friendly_id
		rake db:migrate

4. Add to Person model

		include FriendlyId
		friendly_id :title, :use => :slugged

5. Add another person (or resave the first). Links in Trestle point to `http://localhost:3000/admin/people/person-name` but you get the above error.

**Comment by spohlenz** [comment]
I've very recently pushed a change (3baacdde92c741e30f27b5603e7b2861dcd9e984) that makes the instance plain ID the default URL parameter (as this will cause fewer issues as a default). I'm in the process now of putting out a new release.

However if you do want to use the friendly_id slugs in the admin, you can override the `to_param` and `find_instance` methods:

```ruby
Trestle.resource(:people) do
  to_param do |instance|
    instance.slugged
  end

  find_instance do |params|
    model.friendly.find(params[:id])
  end
end
```

**Comment by joeczucha** [comment]
Wow thanks for the incredible speedy response. 

Would I just put that in the Trestle initializer? I tried that but got: `undefined method 'find_instance' for #<Trestle::Resource::Builder:0x007fccf3a35f80> (NoMethodError)`

**Comment by spohlenz** [comment]
My mistake, that should be `instance` rather than `find_instance`:

Trestle.resource(:people) do
  to_param do |instance|
    instance.slugged
  end

  instance do |params|
    model.friendly.find(params[:id])
  end
end

**Comment by joeczucha** [comment]
Sorry to be a pain but still no luck :( Do I need to put it somewhere different? I've just got it in the initializer after the close of the `Trestle.configure do |config|` block at the moment.

I set the `to_param` override to just output a string but that didn't seem to make any difference so I'd imagine I've just got it in the wrong place and it's being ignored...

**Comment by joeczucha** [comment]
(deletes previous comment out of over-tired embarrasment)

Got you - added that to my admin resource and worked a charm.

Thanks again, Sam.
