### ISSUE TITLE
Default values in forms

### ISSUE THREAD

**Issue by TomHetmer** [TrestleAdmin/trestle#270]
Hi,

I'm trying to set a default form value but I haven't found a good way to do it.

I'm using 

```
  build_instance do |attrs, params|
    AbrPreset.new(attrs).tap do |abr_preset|
      abr_preset.refs = 3 unless abr_preset.refs?
      abr_preset.bframes = 3 unless abr_preset.bframes?
    end
  end
```

with limited success.
I.e. this fails when the user actually wants to keep the form value empty.
Any ideas?

**Comment by spohlenz** [comment]
I'd go with something like this:

```ruby
Trestle.resource(:abr_presets) do
  DEFAULT_ATTRIBUTES = {
    refs: 3,
    bframes: 3
  }

  build_instance do |attrs|
    model.new(request.post? ? attrs : DEFAULT_ATTRIBUTES.merge(attrs))
  end
end
```

I am currently considering functionality for a kind of form object API for more complex forms, so I may end up putting full support for default attributes in there.
