### ISSUE TITLE
Custom button always reload page after click.

### ISSUE THREAD

**Issue by rcholody** [TrestleAdmin/trestle#271]
Is it possible to not reload the page after click on custom button defined in Trestle form?

**Comment by spohlenz** [comment]
If you specify `type: "button"` on the button options, then you should be able to hook onto the click event without the form submitting.

e.g. in your admin form block:

```ruby
concat button_tag("Click me!", type: "button", data: { behavior: "clicker" })
```

and in `app/assets/javascripts/trestle/custom.js`:

```js
$(document).on('click', '[data-behavior="clicker"]', function() {
  alert("Clicked");
});
```
