### ISSUE TITLE
flatpickr locale not loaded automatically

### ISSUE THREAD

**Issue by mitosch** [TrestleAdmin/trestle#274]
**Error description**

Flatpickr UI is still displayed in english in Trestle, even when the configured language in Rails is set to german ( `I18n.available_locales =  [:de, :en]` and `config.i18n.default_locale = :de` )

**Expected behaviour**

Trestle automatically loads the flatpickr locales, according to Rails' available_locales.

**Current behaviour**

When using another language (e.g. :de) in Rails with trestle, the flatpickr locale json is not loaded automatically. Only english is loaded.

I've debugged until the following line in the frontend:

<img width="641" alt="Bildschirmfoto 2020-01-05 um 10 53 04" src="https://user-images.githubusercontent.com/922559/71871590-dffc0380-3119-11ea-8257-a58e51fa7161.png">

Source: [admin.html.erb](https://github.com/TrestleAdmin/trestle/blob/master/app/views/layouts/trestle/admin.html.erb#L33)

So trestle is successfully calling Trestle.localize("de") in the frontend, but flatpickr l10ns doesn't have de.json loaded (see console in screenshot).

I can try to fix it: Is the expected behaviour assumed correctly or is it intended to do it like below? Can you give me a hint, where I could further debug and how the locale-js files of flatpickr are bundled and loaded? (I saw it in webpacker configuration, it was copied to the right place, but where not loaded I guess)

**Quickfix**

As a fix, I've created a file in my Rails app (`app/assets/javascripts/trestle/custom.js`) with the following content and copied the flatpickr locale to `app/assets/javascripts/trestle/flatpickr/de.js`:

```js
//= require "trestle/flatpickr/de"
```

**Comment by spohlenz** [comment]
Thanks for the report.

It looks like the Flatpickr locale import code didn't end up making it across in the 0.9 asset rebuild. See [here](https://github.com/TrestleAdmin/trestle/blob/v0.8.13/vendor/assets/javascripts/trestle/flatpickr.js.erb) for what it was originally doing.

I'll verify that this code still does what it should and then bring it back in, but until then your workaround effectively does the same thing.
