### ISSUE TITLE
Bootstap version

### ISSUE THREAD

**Issue by lphm** [TrestleAdmin/trestle#276]
Hello,
What is the number version of the Bootstrap's framework bundled with latest Trestle's version ?
Thank you.

**Comment by spohlenz** [comment]
As of Trestle 0.9.2, the current Bootstrap version is 4.4.1.

In general I'll ensure that this version is always documented on https://github.com/TrestleAdmin/trestle/releases since it is a fairly major component.

**Comment by lphm** [comment]
Perfect, thank you :)
