### ISSUE TITLE
Tables randomly lose the ability to sort

### ISSUE THREAD

**Issue by swrobel** [TrestleAdmin/trestle#278]
I've noticed something strange ... some of my tables have become un-sortable over time. A new deploy (with no code changes to the admin config) seems to fix this. I have a production & qa environment with the exact same code, that are always deployed together. The production site was sortable after the deploy a few days ago, but somewhere along the way, the headers lost the sort buttons (no deploys since then). I just deployed again and now it's sortable again. Strange! Here are screenshots right before this deploy:

qa:
<img width="682" alt="Screen Shot 2020-02-05 at 10 35 26 AM" src="https://user-images.githubusercontent.com/157270/73871971-aba46180-4803-11ea-87af-5b0b4594870a.png">

production:
<img width="681" alt="Screen Shot 2020-02-05 at 10 35 18 AM" src="https://user-images.githubusercontent.com/157270/73871976-afd07f00-4803-11ea-9923-d117399bd68d.png">

I had never noticed this before, and just recently upgraded to gem version 0.9.2 so that's the one thing I could see being the cause. I haven't seen any exceptions nor anything in the javascript console.

**Comment by spohlenz** [comment]
This should now be fixed. A spec (and hence the behavior under test) wasn't doing what I thought it was due to a lazily-initialized subject.
