### ISSUE TITLE
How to clear session just before login

### ISSUE THREAD

**Issue by karan-ta** [TrestleAdmin/trestle#284]
I am using trestle admin with trestle auth.

users generally forget to logout.

for my custom code - i add some variables in the session.

i wish to clear these session variables when a user logs in.

how can i possibly do this so that login works as is and my session variables are cleared as well in each login.

**Comment by spohlenz** [comment]
In the current `master` branch of trestle-auth, I've been working on support for alternative backends (e.g. Devise, Warden or custom). A custom backend extension would probably be a good option in this case.

Create a custom backend e.g. `lib/custom_trestle_auth_backend.rb`:

```ruby
class CustomTrestleAuthBackend < Trestle::Auth::Backends::Basic
  def logout!
    super

    # Do what you want with `session` or `cookies`
    session.delete(:my_key)
    # or session.destroy
  end
end
```

Configure trestle-auth to use the backend in `config/initializers/trestle.rb`:

```ruby
require "custom_trestle_auth_backend"
config.auth.backend = CustomTrestleAuthBackend
```

Further documentation and a gem release for this update is coming very soon.

**Comment by spohlenz** [comment]
Sorry, missed that you wanted to reset these session variables on login rather than logout:

```ruby
class CustomTrestleAuthBackend < Trestle::Auth::Backends::Basic
  def login!(user)
    super

    session.delete(:my_key)
  end
end
```
