### ISSUE TITLE
ActionView::Template::Error (Invalid CSS after "...lor}: #{$value}": expected "{", was ";"):

### ISSUE THREAD

**Issue by xvpe** [TrestleAdmin/trestle#287]
Getting CSS syntax error for a clean install. I am able to make it go away by removing double hyphens within _**[trestle/frontend/theme/trestle/theme/bootstrap/_color-vars.scss](https://github.com/TrestleAdmin/trestle/blob/master/frontend/theme/trestle/theme/bootstrap/_color-vars.scss)**_

Does anybody know any workaround?

**Comment by spohlenz** [comment]
Could you post what Sass-related and minifier-related gems and versions you have installed? I'm guessing it's a minifier getting hung up on the syntax.

**Comment by xvpe** [comment]
Thank you for the quick response! @spohlenz 

As far as I can tell it's this:

`gem 'sass-rails', '~> 5.0'`
`gem 'uglifier', '>= 1.3.0'`
`gem 'coffee-rails'`

I'm not sure if it matter but I get similar issue when trying to use a converter with that chunk of code:
<img width="1360" alt="Screen Shot 2020-02-24 at 9 09 50 PM" src="https://user-images.githubusercontent.com/9598663/75208699-6d3afc00-574a-11ea-8b19-d488089071ec.png">

**Comment by spohlenz** [comment]
It looks like the JSONformatter converter you are using doesn't support CSS variables.

Could you please post the full output of `bundle list` and I'll try to match my environment to yours.

**Comment by xvpe** [comment]
Thank you! Please see below:

Gems included by the bundle:
  * aasm (5.0.3)
  * actioncable (5.0.4)
  * actionmailer (5.0.4)
  * actionpack (5.0.4)
  * actionview (5.0.4)
  * activejob (5.0.4)
  * activemodel (5.0.4)
  * activemodel-serializers-xml (1.0.1)
  * activerecord (5.0.4)
  * activerecord-postgis-adapter (4.0.4)
  * activeresource (5.0.0)
  * activesupport (5.0.4)
  * addressable (2.5.2)
  * arel (7.1.4)
  * ast (2.3.0)
  * aws-eventstream (1.0.3)
  * aws-partitions (1.211.0)
  * aws-sdk (3.0.1)
  * aws-sdk-acm (1.25.0)
  * aws-sdk-apigateway (1.34.0)
  * aws-sdk-applicationautoscaling (1.30.0)
  * aws-sdk-applicationdiscoveryservice (1.21.0)
  * aws-sdk-appstream (1.36.0)
  * aws-sdk-athena (1.19.0)
  * aws-sdk-autoscaling (1.28.0)
  * aws-sdk-batch (1.25.0)
  * aws-sdk-budgets (1.25.0)
  * aws-sdk-clouddirectory (1.20.0)
  * aws-sdk-cloudformation (1.25.0)
  * aws-sdk-cloudfront (1.22.0)
  * aws-sdk-cloudhsm (1.18.0)
  * aws-sdk-cloudhsmv2 (1.18.0)
  * aws-sdk-cloudsearch (1.15.0)
  * aws-sdk-cloudsearchdomain (1.15.0)
  * aws-sdk-cloudtrail (1.17.0)
  * aws-sdk-cloudwatch (1.28.0)
  * aws-sdk-cloudwatchevents (1.24.0)
  * aws-sdk-cloudwatchlogs (1.25.0)
  * aws-sdk-codebuild (1.40.0)
  * aws-sdk-codecommit (1.28.0)
  * aws-sdk-codedeploy (1.26.0)
  * aws-sdk-codepipeline (1.24.0)
  * aws-sdk-codestar (1.17.0)
  * aws-sdk-cognitoidentity (1.16.0)
  * aws-sdk-cognitoidentityprovider (1.25.0)
  * aws-sdk-cognitosync (1.15.0)
  * aws-sdk-configservice (1.37.0)
  * aws-sdk-core (3.67.0)
  * aws-sdk-costandusagereportservice (1.17.0)
  * aws-sdk-databasemigrationservice (1.27.0)
  * aws-sdk-datapipeline (1.15.0)
  * aws-sdk-dax (1.17.0)
  * aws-sdk-devicefarm (1.27.0)
  * aws-sdk-directconnect (1.24.0)
  * aws-sdk-directoryservice (1.21.0)
  * aws-sdk-dynamodb (1.34.0)
  * aws-sdk-dynamodbstreams (1.15.0)
  * aws-sdk-ec2 (1.108.0)
  * aws-sdk-ecr (1.20.0)
  * aws-sdk-ecs (1.49.0)
  * aws-sdk-efs (1.21.0)
  * aws-sdk-elasticache (1.25.0)
  * aws-sdk-elasticbeanstalk (1.25.0)
  * aws-sdk-elasticloadbalancing (1.18.0)
  * aws-sdk-elasticloadbalancingv2 (1.33.0)
  * aws-sdk-elasticsearchservice (1.26.0)
  * aws-sdk-elastictranscoder (1.17.0)
  * aws-sdk-emr (1.21.0)
  * aws-sdk-firehose (1.20.0)
  * aws-sdk-gamelift (1.24.0)
  * aws-sdk-glacier (1.25.0)
  * aws-sdk-glue (1.43.0)
  * aws-sdk-greengrass (1.24.0)
  * aws-sdk-health (1.19.0)
  * aws-sdk-iam (1.29.0)
  * aws-sdk-importexport (1.15.0)
  * aws-sdk-inspector (1.22.0)
  * aws-sdk-iot (1.37.0)
  * aws-sdk-iotdataplane (1.15.0)
  * aws-sdk-kinesis (1.19.0)
  * aws-sdk-kinesisanalytics (1.20.0)
  * aws-sdk-kms (1.24.0)
  * aws-sdk-lambda (1.30.0)
  * aws-sdk-lambdapreview (1.15.0)
  * aws-sdk-lex (1.19.0)
  * aws-sdk-lexmodelbuildingservice (1.21.0)
  * aws-sdk-lightsail (1.24.0)
  * aws-sdk-machinelearning (1.16.0)
  * aws-sdk-marketplacecommerceanalytics (1.16.0)
  * aws-sdk-marketplaceentitlementservice (1.15.0)
  * aws-sdk-marketplacemetering (1.18.0)
  * aws-sdk-migrationhub (1.17.0)
  * aws-sdk-mturk (1.18.0)
  * aws-sdk-opsworks (1.20.0)
  * aws-sdk-opsworkscm (1.24.0)
  * aws-sdk-organizations (1.32.0)
  * aws-sdk-pinpoint (1.27.0)
  * aws-sdk-polly (1.26.0)
  * aws-sdk-rds (1.65.0)
  * aws-sdk-redshift (1.31.0)
  * aws-sdk-rekognition (1.30.0)
  * aws-sdk-resourcegroupstaggingapi (1.18.0)
  * aws-sdk-resources (3.0.2)
  * aws-sdk-route53 (1.29.0)
  * aws-sdk-route53domains (1.17.0)
  * aws-sdk-s3 (1.48.0)
  * aws-sdk-secretsmanager (1.31.0)
  * aws-sdk-servicecatalog (1.32.0)
  * aws-sdk-ses (1.26.0)
  * aws-sdk-shield (1.20.0)
  * aws-sdk-simpledb (1.15.0)
  * aws-sdk-sms (1.16.0)
  * aws-sdk-snowball (1.20.0)
  * aws-sdk-sns (1.19.0)
  * aws-sdk-sqs (1.22.0)
  * aws-sdk-ssm (1.55.0)
  * aws-sdk-states (1.22.0)
  * aws-sdk-storagegateway (1.32.0)
  * aws-sdk-support (1.15.0)
  * aws-sdk-swf (1.16.0)
  * aws-sdk-waf (1.24.0)
  * aws-sdk-wafregional (1.25.0)
  * aws-sdk-workdocs (1.18.0)
  * aws-sdk-workspaces (1.27.0)
  * aws-sdk-xray (1.20.0)
  * aws-sigv2 (1.0.1)
  * aws-sigv4 (1.1.0)
  * aws_cf_signer (0.1.3)
  * axiom-types (0.1.1)
  * bcrypt (3.1.11)
  * benchmark-ips (2.7.2)
  * binding_of_caller (0.7.2)
  * builder (3.2.3)
  * bundler (1.17.3)
  * byebug (9.0.6)
  * cancancan (2.0.0)
  * capybara (2.14.4)
  * carrierwave (0.10.0)
  * cloudinary (1.2.2)
  * coercible (1.0.0)
  * coffee-rails (4.2.2)
  * coffee-script (2.4.1)
  * coffee-script-source (1.12.2)
  * concurrent-ruby (1.0.5)
  * connection_pool (2.2.1)
  * crack (0.4.3)
  * dante (0.2.0)
  * debug_inspector (0.0.3)
  * descendants_tracker (0.0.4)
  * devise (4.4.3)
  * diff-lcs (1.3)
  * docile (1.1.5)
  * domain_name (0.5.20180417)
  * dotenv (2.2.1)
  * dotenv-rails (2.2.1)
  * dwolla_v2 (2.2.0)
  * ed25519 (1.2.4)
  * equalizer (0.0.11)
  * erubis (2.7.0)
  * excon (0.62.0)
  * execjs (2.7.0)
  * factory_girl (4.8.0)
  * factory_girl_rails (4.8.0)
  * faker (1.8.7 679fd50)
  * faraday (0.16.2)
  * faraday_middleware (0.12.0)
  * faraday_middleware-aws-signers-v4 (0.2.0.beta)
  * ffi (1.9.18)
  * geokit (1.11.0)
  * geokit-rails (2.2.0)
  * gibbon (2.2.4)
  * globalid (0.4.0)
  * haml (5.0.4)
  * hashdiff (0.3.4)
  * hashie (3.5.7)
  * honeybadger (2.7.2)
  * http-cookie (1.0.3)
  * httparty (0.17.1)
  * i18n (0.8.6)
  * ice_nine (0.11.2)
  * interactor (3.1.0)
  * jbuilder (2.7.0)
  * jmespath (1.4.0)
  * jquery-rails (4.3.1)
  * jquery-ui-rails (6.0.1)
  * json (2.1.0)
  * jwt (2.2.1)
  * kaminari (1.1.1)
  * kaminari-actionview (1.1.1)
  * kaminari-activerecord (1.1.1)
  * kaminari-core (1.1.1)
  * koala (3.0.0)
  * launchy (2.4.3)
  * letter_opener (1.4.1)
  * listen (3.0.8)
  * loofah (2.0.3)
  * mail (2.6.6)
  * mandrill-api-json (1.0.56)
  * method_source (0.8.2)
  * mime-types (3.2.2)
  * mime-types-data (3.2018.0812)
  * mini_portile2 (2.2.0)
  * minitest (5.10.3)
  * mixpanel-ruby (2.2.0)
  * multi_json (1.13.1)
  * multi_xml (0.6.0)
  * multipart-post (2.1.1)
  * nested_form_fields (0.8.1)
  * net-http-persistent (3.1.0)
  * netrc (0.11.0)
  * newrelic_rpm (4.3.0.335)
  * nio4r (2.1.0)
  * nokogiri (1.8.0)
  * oauth2 (1.4.3)
  * oj (3.3.2)
  * omniauth (1.9.0)
  * omniauth-google-oauth2 (0.7.0)
  * omniauth-oauth2 (1.5.0)
  * orm_adapter (0.5.0)
  * pagy (3.2.0)
  * parallel (1.12.1)
  * parser (2.4.0.2)
  * paypal-sdk-rest (1.6.0)
  * pg (0.21.0)
  * plaid (6.1.0)
  * powerpack (0.1.1)
  * public_suffix (3.1.1)
  * puma (3.9.1)
  * rack (2.0.7)
  * rack-cors (1.0.3)
  * rack-protection (1.5.3)
  * rack-test (0.6.3)
  * rails (5.0.4)
  * rails-controller-testing (1.0.2)
  * rails-dom-testing (2.0.3)
  * rails-html-sanitizer (1.0.3)
  * rails_12factor (0.0.3)
  * rails_serve_static_assets (0.0.5)
  * rails_stdout_logging (0.0.5)
  * railties (5.0.4)
  * rainbow (3.0.0)
  * rake (12.3.0)
  * rb-fsevent (0.10.2)
  * rb-inotify (0.9.10)
  * rdoc (6.1.1)
  * redis (3.3.3)
  * redis-actionpack (5.0.2)
  * redis-activesupport (5.0.7)
  * redis-rack (2.0.5)
  * redis-rails (5.0.2)
  * redis-store (1.6.0)
  * remotipart (1.3.1)
  * responders (2.4.0)
  * rest-client (2.0.2)
  * rgeo (0.6.0)
  * rgeo-activerecord (5.0.1)
  * rspec-core (3.6.0)
  * rspec-expectations (3.6.0)
  * rspec-mocks (3.6.0)
  * rspec-rails (3.6.0)
  * rspec-sidekiq (3.0.3)
  * rspec-support (3.6.0)
  * rspec_junit_formatter (0.4.1)
  * rspotify (2.8.0)
  * rubocop (0.52.1)
  * ruby-progressbar (1.9.0)
  * safe_yaml (1.0.4)
  * sass (3.5.1)
  * sass-listen (4.0.0)
  * sass-rails (5.0.6)
  * scout_apm (2.4.14)
  * sdoc (1.0.0)
  * shopify_api (4.3.9)
  * shoulda-matchers (3.1.2)
  * sidekiq (4.2.2)
  * simplecov (0.15.1)
  * simplecov-html (0.10.2)
  * spotify-client (0.0.10)
  * spring (2.0.2)
  * spring-commands-rspec (1.0.4)
  * spring-watcher-listen (2.0.1)
  * sprockets (3.7.1)
  * sprockets-rails (3.2.0)
  * stripe (1.47.0)
  * stripe-ruby-mock (2.3.1)
  * telnyx (0.0.4)
  * temple (0.8.0)
  * thor (0.19.4)
  * thread_safe (0.3.6)
  * tilt (2.0.9)
  * timecop (0.9.1)
  * trestle (0.9.2)
  * turbolinks (5.0.1)
  * turbolinks-source (5.0.3)
  * twilio-ruby (5.5.1)
  * tzinfo (1.2.3)
  * unf (0.1.4)
  * unf_ext (0.0.7.5)
  * unicode-display_width (1.3.0)
  * uphold (1.2.3)
  * vcr (3.0.3)
  * virtus (1.0.5)
  * warden (1.2.7)
  * web-console (2.3.0)
  * webmock (3.0.1)
  * websocket-driver (0.6.5)
  * websocket-extensions (0.1.2)
  * xml-simple (1.1.5)
  * xpath (2.1.0)

**Comment by spohlenz** [comment]
It looks like your version of sass (3.5.1) is causing the issue. I was able to reproduce the same error when pinning to that version.

Assuming you don't have it pinned in your Gemfile, and no other gems are causing a version conflict, then running `bundle update sass` should update it to 3.7.4.

If it still doesn't work after updating the sass gem, then also try `rake tmp:cache:clear` and restarting the Rails server.

**Comment by xvpe** [comment]
Thank you @spohlenz ! Updating sass helps.
