### ISSUE TITLE
Clear select field relation

### ISSUE THREAD

**Issue by ppietrasik** [TrestleAdmin/trestle#289]
In one of my models, I have optional relation defined as so: `belongs_to :relation, optional: true`
I would like to nullify it when updating a record through the admin panel.
I have tried multiple things eg. :
```
select :relation, Relation.all, include_blank: true
select :relation, Relation.all, {},  data: { placeholder: 'Placeholder', allow_clear: true }
```
Nothing works tho, at most I can manage to receive 500 Error with `expected, got "" which is an instance of String(#70355721240040)`.
Usually, when I have to work with this gem, that means reading my way through the source code, cause documentation is very sparse. But this time I haven't even found anything that would help me :/ Maybe I'm just missing something. Anyway, I would be very thankful if someone could provide me with a solution.

**Comment by spohlenz** [comment]
In this case, you'll want to use `:relation_id` rather than `:relation`. This is one of those Rails quirks which is often hard to remember. I'm contemplating adding support to allow both to work but this will probably be something I add in future alongside form object support.

**Comment by ppietrasik** [comment]
So I was missing something. Now it works like a charm, thank you very much! I end up with: 
`select : relation_id, Relation.all, { include_blank: true }, data: { placeholder: 'Placeholder', allow_clear: true }`
