### ISSUE TITLE
I18N support

### ISSUE THREAD

**Issue by Dolbager** [TrestleAdmin/trestle#29]
Do you have a plan to support i18n or module for it?

**Comment by spohlenz** [comment]
I don't currently have any additional languages defined. However I have done my best to extract out any translatable strings into https://github.com/TrestleAdmin/trestle/blob/master/config/locales/en.yml (and if any are missing it should be considered a bug).

Any contributions for additional locales would be welcomed with open arms!

**Comment by Dolbager** [comment]
Thanks, i will try to do this at free time.
