### ISSUE TITLE
Default column sort doesn't work

### ISSUE THREAD

**Issue by lphm** [TrestleAdmin/trestle#290]
Hello,
We use default order with this code : 
`
...
column :created_at, sort: {default: true, field: :created_at, default_order: :desc}
...
`
But records in table are not sorted correctly. Icon is shown correctly but records are not sorted.
I saw in logs that no SQL fragment order "ORDER BY" is applied...

Maybe a bug ...?

**Comment by quantavi** [comment]
I can confirm that. Using Trestle 0.9.2

Have this line in table block:
`column :id, sort: { default: true, default_order: :desc }`
I can see the the down arrow near the ID column correctly, but the records are not sorted. I need to click twice to get the correct result.
The SQL queries that are executed are:
- First load: SELECT `audit_logs`.* FROM `audit_logs` LIMIT 25 OFFSET 0
- First click on arrow: SELECT `audit_logs`.* FROM `audit_logs` ORDER BY `audit_logs`.`id` ASC LIMIT 25 OFFSET 0
- Second click: SELECT `audit_logs`.* FROM `audit_logs` ORDER BY `audit_logs`.`id` DESC LIMIT 25 OFFSET 0

**Comment by spohlenz** [comment]
The way this works isn't entirely intuitive and I either need to make sure it is more clearly documented, or come up with something in the DSL that is more neatly integrated.

In short, using `sort: { default: true }` assumes that you are already sorting by that column within your main `collection` block. e.g.

```ruby
collection do
  model.order(created_at: :desc)
end
```

When no sort parameters are passed to the index view (i.e. a fresh page load), the table doesn't know by default which column is being sorted by (or the order), so it needs to be marked explicitly.

If it helps to think of it this way, basically the `sort` option on a column doesn't do any sorting by itself, but merely controls how the sorting arrows will work (i.e. when they show up vs down vs unsorted).

**Comment by lphm** [comment]
Ok, this works perfectly but when we associate Ransack on models, we have to add "collection" block into Ransack block to be fully functionnal.

So for sharing :
```
def ransackable(base_collection = nil)
    q = nil

    before_action do
      @q = q
    end

    collection do |params|
      if base_collection.nil?
        q = model.order(created_at: :desc).search(params[:q])
      else
        q = base_collection.call.search(params[:q])
      end
      q.result
    end
  end
```
