### ISSUE TITLE
Form class problem on scoped resources

### ISSUE THREAD

**Issue by lphm** [TrestleAdmin/trestle#297]
Classes names on forms build on modular(scoped) resources are a big problem.

For example I have differents resources into scopes : crm/projects
Form class generated automatically is "edit_crm/projects"

Normally, HTML class name cannot contains "/" character. Maybe a simple call to ".undescore" method on class builder name should resolve this problem.

**Comment by spohlenz** [comment]
The "/" character isn't technically disallowed within HTML class names, but you have a fair point that it definitely becomes harder to target properly within your CSS.

The call to render the form doesn't currently specify the class name explicitly but does pass the admin parameter name as the `:as` option within the [trestle_form_for](https://github.com/TrestleAdmin/trestle/blob/master/app/helpers/trestle/form_helper.rb#L7) helper.

Ideally, it should be possible to pass a custom class (or ID, or `data-` variables) explicitly to the form block, e.g.

```ruby
form class: "crm-projects-form" do
  ...
end
```

And further still it would be nice to support separate form definitions for new vs edit (or a custom one for embedding within another admin), similar to the way tables can be now.

Until then, you should be able to escape the `/` within your CSS with a `\`:

```css
.edit_crm\/projects {
  ...
}
