### ISSUE TITLE
Sample Application & Documentation

### ISSUE THREAD

**Issue by eshaiju** [TrestleAdmin/trestle#3]
@spohlenz  I tried it and I really liked the admin. Can you start a documentation session?. I can also contribute to documentation and also in sample application development.

**Comment by spohlenz** [comment]
Documentation is currently in the works and will be available soon on https://trestle.io.

I have a number of demo apps in my local environment, so I will endeavour to clean them up ASAP and upload to GitHub and put a live-demo on Heroku.

**Comment by garo** [comment]
Any updates on the documentation and examples? I would love to have a clonable github project which would present a set of general features where one could learn from.

**Comment by petrisrf** [comment]
Any updates on docs?
