### ISSUE TITLE
Allow configuration of datepicker firstDayOfWeek in Trestle initializer

### ISSUE THREAD

**Issue by unikitty37** [TrestleAdmin/trestle#30]
I have placed `Flatpickr.l10ns.default.firstDayOfWeek = 1;` in a `<script>` tag in the document's head, and set `config.i18n.default_locale = :'en-GB'` in `config/initializers/application.rb`, but the generated datepickers are still incorrectly showing with the week running from Sunday to Saturday, rather than from Monday to Sunday.

It would be useful if there was a config option to set the first day of the week in the Trestle initializer.

In the meantime, could somebody please tell me how to configure Trestle to display the datepicker correctly for my locale? I can't put the site out with it like this — I will get a load of complaints…

**Comment by spohlenz** [comment]
With the latest version of Flatpickr, the global variable is `flatpickr` with a lowercase f. So `flatpickr.l10ns.default.firstDayOfWeek = 1;` should work.

I've just confirm the following lines in `config/initializers/trestle.rb` work as expected:

```ruby
config.hook(:javascripts) do
  javascript_tag "flatpickr.l10ns.default.firstDayOfWeek = 1;"
end
```

**Comment by unikitty37** [comment]
Thanks — looks like the Flatpickr docs I was using hadn't been updated yet :)
