### ISSUE TITLE
Unable to find model Article. Specify a different model using Trestle.resource(:articles, model: MyModel) 

### ISSUE THREAD

**Issue by LennartRommeiss** [TrestleAdmin/trestle#300]
I'am using rails 6.0.2.2.
 After the installation from the readme I get this Error:
![image](https://user-images.githubusercontent.com/61516567/80599388-22c84b00-8a2b-11ea-8b93-79890962f311.png)

It's the only Gem I added after a fresh rail project.

**Comment by spohlenz** [comment]
The instructions in the README assume you have an existing model named `Article`. If you're just looking to try out Trestle on a new app, you can create a sample model with the following:

```
$ rails generate model Article title:string body:text published:boolean
$ rails db:migrate
```

Alternatively, if you have an existing model then replace `Article` with the name of your model.

I've updated the README to hopefully make this a little clearer.
