### ISSUE TITLE
Expected file to define constant exception

### ISSUE THREAD

**Issue by pelted** [TrestleAdmin/trestle#302]
Ran into an issue creating a resource around the **audited** gem's `Audited::Audit` AR model.

Based on other issues I would expect the below example to work with `:scope`.
```ruby
# /app/admin/audited/audits_admin.rb

Trestle.resource(:audits, scope: Audited) do
  menu do
    item :activity_log, icon: 'fa fa-list-alt'
  end

  table do
    column :id, link: true
    column :username
    column :created_at
  end

  form do |_audit|
    text_field :username
  end
end
```

The result on app load is:

`Uncaught exception: expected file .../app/admin/audited/audits_admin.rb to define constant Audited::AuditsAdmin, but didn't
`

**Comment by spohlenz** [comment]
Your example seems to work for me. I did notice in your original post there was a typo in your first line (`:aduits` instead of `:audits`). Does that typo also exist in your app?

**Comment by pelted** [comment]
In the end it was a combination of a typo, and an autoloader issue with a class override. Lots of debugging time.

By they way, first time really digging in and using Trestle. Great work, made this quick internal project happen in days rather than weeks or months. Thank you for the efforts.

**Comment by leifg** [comment]
@pelted can you elaborate on the autoloader issue, I'm having the same problem.
