### ISSUE TITLE
scope label translation

### ISSUE THREAD

**Issue by petitkriket** [TrestleAdmin/trestle#303]
Hello,

Is there a specific path to assign a yml translation to scopes ?

Iv'e tried 
```rb
scope :large_band, -> { Band.where('members_count > ?', 5) }, label: t('admin.more_than_members', count: '100')
```

then used i18n.t() like so
```rb
scope :large_band, -> { Band.where('members_count > ?', 5) }, label: I18n.t('admin.more_than_members', count: '100')
```
but it does not load the translations at server start and works only after a refresh

any clue ?

**Comment by spohlenz** [comment]
That's an interesting issue regarding the translations not showing on initial load. I am able to replicate it so I will look into that further. I suspect the admins are initially being loaded before the i18n files are initialized.

In your case though, you can use the i18n key `admin.scopes.large_band` to target that particular scope, without specifying the `label` option.

You've also alerted me to another fix I need to make, which is to have the scope label use the `Admin#translate` helper, which will allow the i18n value to be defined per-admin (i.e. look up `admin.bands.scopes.large_band` before falling back to `admin.scopes.large_band`).

**Comment by spohlenz** [comment]
Both of these issues should now be fixed in `master`.

**Comment by petitkriket** [comment]
happy if I had help, thank you for theses fixes !
