### ISSUE TITLE
current_user is not available in scopes block

### ISSUE THREAD

**Issue by quantavi** [TrestleAdmin/trestle#309]
Hi,

Is there a way to access current_user in that section?
I am trying to add ability to switch displaying of items between "All" and user owned items. I know I can do similar thing in collection block, but then I am loosing ability to display all items.

Thanks

**Comment by spohlenz** [comment]
This isn't currently possible but is definitely something I want to address (sooner rather than later).

Ideally I will add support for both of the following cases, which will require some (mostly minor) reworking of the way scopes work.

```ruby
scopes do
  scope :all
  scope :mine, -> { where(user: current_user) }
end
```
```ruby
scopes do
  scope :all
  scope :deleted if current_user.administrator?
end
```

**Comment by pelted** [comment]
Yes please! Both of these cases would be awesome.
