### ISSUE TITLE
Trestle in Gemfile causes ExecJS error

### ISSUE THREAD

**Issue by joeczucha** [TrestleAdmin/trestle#31]
This is a bit of a strange one: I'd assumed that I'd used some ES6 somewhere by mistake but it seems that if Trestle is included in my Gemfile then `rake assets:precompile RAILS_ENV=production` fails with:

    yarn install v0.27.5
    warning package.json: No license field
    warning No license field
    [1/4] Resolving packages...
    success Already up-to-date.
    Done in 2.43s.
    rake aborted!
    ExecJS::RuntimeError: SyntaxError: Unexpected token: punc ())
    JS_Parse_Error.Object.defineProperty.get ((execjs):3538:621)
    (execjs):4060:47
    (execjs):1:102
    Object.<anonymous> ((execjs):1:120)
    Module._compile (module.js:556:32)
    Object.Module._extensions..js (module.js:565:10)
    Module.load (module.js:473:32)
    tryModuleLoad (module.js:432:12)
    Function.Module._load (module.js:424:3)
    Module.runMain (module.js:590:10)
    /Users/joe/.rbenv/versions/2.4.0/bin/bundle:22:in `load'
    /Users/joe/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'
    Tasks: TOP => assets:precompile
    (See full trace by running task with --trace)

Running the command without `RAILS_ENV=production` works fine, as does removing the entry from the Gemfile, deleting the initializer and re-running `rake assets:precompile RAILS_ENV=production`.

I'm using Rails 5.1, Yarn and Webpack (eeeugh!)

**Comment by spohlenz** [comment]
I'm not seeing this on a fresh Rails 5.1.3 app with Yarn, Webpack 3.0 and Trestle 0.8.4. Are you able to upload a sample app?

**Comment by joeczucha** [comment]
Ah, scratch that - updated to Trestle 0.8.4 via Github (was just using the repo version before which resolved to 0.8.3) and the problem went away 👍  

Apologies for the false alarm... :)
