### ISSUE TITLE
How to link to trestle without view context

### ISSUE THREAD

**Issue by timdiggins** [TrestleAdmin/trestle#310]
I've successfully used `.trestle` in controllers/views/helpers as discussed in reading https://github.com/TrestleAdmin/trestle/wiki/How-To:-Link-To-Trestle.

I've been trying to output a link to a trestle admin url in a Job, and  and I've found that I can't find a way to access the trestle helper. 

I had thought that adding in `include Rails.application.routes.url_helpers` to the Job would allow this, but it gives access to defined routes but not the trestle helper. 

Any mechanism to do this? 
(I'm happy to update the wiki page if you can give a quick reply).

**Comment by spohlenz** [comment]
There are a couple of methods you can use here.

The first method (which I'd recommend using) is to use the `#path` and `#instance_path` methods on the admin class.

Assuming you have declared `Trestle.resource(:articles)` then the admin class will be ArticlesAdmin (calling `Trestle.lookup(:articles)` will also return the relevant admin), and you can call the following methods.

```ruby
ArticlesAdmin.path => "/admin/articles"
ArticlesAdmin.path(:show, id: 123) => "/admin/articles/123"

ArticlesAdmin.resource_path(article) => "/admin/articles/1"
ArticlesAdmin.resource_path(article, action: :edit) => "/admin/articles/1/edit"
```

Note that the `resource_path` method is only available on a Resource (declared with `Trestle.resource(...)`) and not a plain Admin (declared with `Trestle.admin(...)`).

Alternatively, you can include `Trestle::Engine.routes.url_helpers` in your Job to call the Rails route helpers directly. Running `rails routes` will list all the route names under the heading "Routes for Trestle::Engine:".

**Comment by timdiggins** [comment]
@spohlenz Thanks! You mention `resource_path` as well as `instance_path` but `resource_path` doesn't seem to exist (even for Trestle resources). But replacing this with `instance_path` works perfectly. If that's just a typo - great. But if I'm missing something, please let me know!

**Comment by timdiggins** [comment]
FYI @spohlenz I've updated the wiki page with this info: https://github.com/TrestleAdmin/trestle/wiki/How-To:-Link-To-Trestle/_compare/4a908d1e57df401e21323c3435d0aacc2699db66...9f536d51dd6606b6ba052427a2e7ff2c0a40cb72

**Comment by spohlenz** [comment]
@timdiggins That was indeed a typo and `instance_path` is the correct method name. I've updated my comment above in case anyone is searching here in future.

Thank you for the excellent wiki edits.
