### ISSUE TITLE
Is there an easy way to expose `_count` columns without having to fully define a `form`?

### ISSUE THREAD

**Issue by jiblits** [TrestleAdmin/trestle#318]
I have some non-counter columns that are suffixed with `_count` and as a result they are getting ignored by trestle. Looking through the documentation it appears it would be possible to expose these columns if I were to define every column I need, however is it possible to just append to the default column list instead?

I'm thinking it would be something like this:

```
form do
  default_fields
  text_field :live_cell_count
  text_field :dead_cell_count
end
```

**Comment by spohlenz** [comment]
I'd recommend overriding the method within the adapter that determines whether a column is a counter cache column. This can be done via the `adapter` block method:

```ruby
adapter do
  WHITELISTED_COUNT_COLUMNS = %w(live_cell_count dead_cell_count)

  def counter_cache_column?(attribute)
    super && !WHITELISTED_COUNT_COLUMNS.include?(attribute.name.to_s)
  end
end
```

If you wanted further control (e.g. to only show the counts in the form but not the table), you could override the `default_table_attributes` and `default_form_attributes` individually within this block.

The built-in definitions for those methods can be found at https://github.com/TrestleAdmin/trestle/blob/master/lib/trestle/adapters/active_record_adapter.rb#L44-L54.
