### ISSUE TITLE
How roles and accesses works in Trestle?

### ISSUE THREAD

**Issue by BKDruby** [TrestleAdmin/trestle#319]
I have two roles Admin and Manager and can't understand why records created by admin can't be updated by manager.
How roles and accesses works in Trerstle?

**Comment by eduardotamaki** [comment]
Hi @BKDruby,
How have you resolved that?

**Comment by BKDruby** [comment]
@eduardotamaki honestly in my case problem was in another place. I just add information about instance saving to logs and found that validation was failed.

**Comment by spohlenz** [comment]
Please see the authorization branch of trestle-auth (https://github.com/TrestleAdmin/trestle-auth/tree/authorization) for some work in progress on integrating with Pundit and CanCanCan (plus there's a simple DSL if you don't want to use either of those).

Note that implementation of roles is left up to you. You may wish to use simple boolean columns on your admin model or something more complex such as rolify (https://github.com/RolifyCommunity/rolify/). Either of these approaches is possible with this branch.
