### ISSUE TITLE
Custom actions

### ISSUE THREAD

**Issue by martio** [TrestleAdmin/trestle#32]
**Good job! This is great!**

How to disable ability to delete a resource?

**Comment by spohlenz** [comment]
At present, the options are to either make the entire resource read only, using `Trestle.resource(:name, readonly: true) do`, or to disable the destroy action using:

```
controller do
  undef_method :destroy
end
```

However this won't remove the delete links (yet).

I am currently working on an API for custom actions which will allow the default actions to be disabled. I may be able to get that part out sooner than the rest.

**Comment by martio** [comment]
Thx! 👍

**Comment by spohlenz** [comment]
It is now possible to properly remove an action using the `remove_action` builder method. Relevant buttons (e.g. save, delete, etc) will also be removed when removing an action.

Usage:

```ruby
Trestle.resource(:articles) do
  remove_action :destroy, :edit, :update
end
```

**Comment by svoboda-jan** [comment]
Using `remove_action :show` causes `ActionController::UrlGenerationError`.

**Comment by svoboda-jan** [comment]
Workaround for `ActionController::UrlGenerationError` when using `remove_action :show`:

```ruby
table autolink: false do
  # ...
end
```

**Comment by hdbreaker** [comment]
Hi, is possible to call  remove_action :destroy, :edit, :update inside an if statement?  I want to remove actions based on user roles (devise).

Something like:
```
if not current_user.admin?
   remove_action :destroy, :edit, :update
end
```

Regards,

**Comment by pandabamboo90** [comment]
@hdbreaker 

Yes you can do that

```
actions do |toolbar, user|
  toolbar.edit if user.role_user?
  toolbar.delete if user.role_user?
end
```

**Comment by skiggety** [comment]
> @hdbreaker
> 
> Yes you can do that
> 
> ```
> actions do |toolbar, user|
>   toolbar.edit if user.role_user?
>   toolbar.delete if user.role_user?
> end
> ```

Where does that go?

**Comment by skiggety** [comment]
OK, I figured out that I could put that 'actions do' block inside 'table do', but not inside the form.

**Comment by jclin8** [comment]
For actions, how do we disable modal when click "Show" button?
