### ISSUE TITLE
No redirect after delete action

### ISSUE THREAD

**Issue by matthieubrau** [TrestleAdmin/trestle#323]
When i am in a tab for a main item and i want to delete a child item, there is a redirection to the entire list of child items and i lose main item context.
I'd like to be able to avoid this redirection after deleting child item and stay in the tab without loosing main item context.
It will be more friendly.

Maybe is it already possible, but i can't found the solution.

Thanks

**Comment by matthieubrau** [comment]
En fait j'ai trouvé la solution grâce au ticket #49

**Comment by sorich87** [comment]
A simpler solution could be with `return_to`, like `return_to(on: :destroy) { :back }`.
