### ISSUE TITLE
File permissions on gem files are causing error when deploying app to AWS Elastic Beanstalk new platform

### ISSUE THREAD

**Issue by quantavi** [TrestleAdmin/trestle#327]
We have noticed that the lack of read permission for others is causing problem with deploying the app using trestle. Here is the output of a command that checks if migration is available:
```
-sh-4.2$ bundle exec /opt/elasticbeanstalk/config/private/checkforraketask.rb db:migrate
rake aborted!
LoadError: cannot load such file -- /var/app/staging/vendor/bundle/ruby/2.7.0/gems/trestle-0.9.3/lib/trestle.rb
/var/app/staging/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/var/app/staging/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/var/app/staging/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/var/app/staging/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/var/app/staging/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/var/app/staging/config/application.rb:7:in `<top (required)>'
/var/app/staging/Rakefile:4:in `require_relative'
/var/app/staging/Rakefile:4:in `<top (required)>'
/opt/elasticbeanstalk/config/private/checkforraketask.rb:21:in `<top (required)>'
/opt/elasticbeanstalk/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
/opt/elasticbeanstalk/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)

```

it is not only the trestle.rb that doesn't have read for others. Not sure what is the rule here, but I have checked some other gems and they tend to have read rights for others.
The same situation is with trestle-auth gem, but probably other trestle related gems may have this issue. 
We have tried (with success) to override those permissions on later stages on deployment, but migration was not run, because the above script is run before predeploy hooks.

Thanks!

**Comment by spohlenz** [comment]
I've fixed the permissions and released new versions of trestle (0.9.4), trestle-auth (0.4.1) and trestle-search (0.4.3).

If you find any other trestle gems are affected, please let me know.

**Comment by finleye** [comment]
I was bumping into this same issue until the version bump. Is there a commit you can point to where the permissions were updated? I've compared the two versions and don't see anything. Maybe github just doesn't display those changes very well.

**Comment by spohlenz** [comment]
Git only tracks the executable status on files, no other permissions, so if you were referencing the GitHub repo in your Gemfile then you shouldn't encounter this issue.

The problem stemmed from me having my home directory on an external drive with incorrect permissions. I was mistakenly under the assumption that permissions within a gem file didn't matter and that they would be set correctly at install time, which isn't the case.

I've fixed the permissions within my repo checkouts so any gems I build from now should be correct.

**Comment by finleye** [comment]
@spohlenz Thanks for the detail! I haven't come across anything like this before. I appreciate your help in understanding.
