### ISSUE TITLE
navigation usability problem

### ISSUE THREAD

**Issue by okliv** [TrestleAdmin/trestle#33]
I have a lot of ul-li groups of menu items at left nav bar (long scrollable div)

If i click on something from the bottom of the list, i lost focus where i am in menu. so... i wrote for now quick solutions for two cases:

1 pre-scroll to current menu item
2 ability to toggle groups and save their states

```coffee
toggleSiblings = (e) ->
  e.siblings().toggle()
  e.find('i').toggleClass('fa-chevron-right fa-chevron-down')

saveToggleState = (v) ->
  c = JSON.parse(localStorage.getItem('clicked-nav-headers'))
  a = if $.isArray(c) then c else []
  i = a.indexOf(v)
  if i == -1 then a.push v else a.splice i, 1
  localStorage.setItem('clicked-nav-headers', JSON.stringify(a))

$(document).ready ->
  # clickable nav headers with saving it's states
  $('.nav-header').css('cursor','pointer').prepend('<i class="fa fa-chevron-down" style="color: grey"></i> ').on 'click', (e) ->
    toggleSiblings($(this))
    saveToggleState($(this).parent().index())
  if localStorage.getItem('clicked-nav-headers')!=undefined
    cnh = JSON.parse(localStorage.getItem('clicked-nav-headers'))
    if $.isArray(cnh)
      cnh.forEach (e) ->
        toggleSiblings($($('.nav-header')[e]))
  # prescroll
  $('.app-sidebar-inner').animate { scrollTop: $('.app-nav .active').offset().top-100 }, 100

```

hope something similar will be included in next releases

i know, it has a clearness problem for collapsed nav bar (just because groups are represented only by dashes, i would leave a first letter of group name, for example) but it is not vital for me for now

**Comment by spohlenz** [comment]
I definitely like these ideas. I'll try to incorporate them soon.

**Comment by spohlenz** [comment]
Both of these features have now been implemented in master.
