### ISSUE TITLE
Nested fields don't get initialised after adding to form

### ISSUE THREAD

**Issue by quantavi** [TrestleAdmin/trestle#336]
We are using Trestle + Cocoon gem. 

We found an issue when adding a new item (subform) it's fields are not initialised - for example date picker is standard, not the one used by Trestle:

<img width="696" alt="Screenshot 2020-12-15 at 14 24 53" src="https://user-images.githubusercontent.com/32466875/102221070-fa219280-3ee1-11eb-96e7-11df8550c1bc.png">

but if you try saving the form, when validation kicks in and the form is returned from the server the Datepicker is different -  the one used by default in Trestle:

<img width="472" alt="Screenshot 2020-12-15 at 14 25 14" src="https://user-images.githubusercontent.com/32466875/102221082-00b00a00-3ee2-11eb-9a42-4429be715e89.png">

We have following code in custom.js file, but it is obviously not enough:

```js
//= require cocoon

$(document).on('cocoon:after-insert', function(e, fields) {
    $(Trestle).trigger('init', fields);
});
```

what are we missing? Thanks!

**Comment by spohlenz** [comment]
In `0.9.0` onwards, you should use `Trestle.triggerInit(fields)` in place of `$(Trestle).trigger('init', fields);`

**Comment by quantavi** [comment]
> In `0.9.0` onwards, you should use `Trestle.triggerInit(fields)` in place of `$(Trestle).trigger('init', fields);`

It works. Thanks!
