### ISSUE TITLE
how to hide specific menu depends on current user's permission

### ISSUE THREAD

**Issue by kxu1988** [TrestleAdmin/trestle#338]
I want to hide the specific menu when user does not have the permission of the resource, is there any way ?

**Comment by quantavi** [comment]
This is what I did for this specific resource:
```ruby
Trestle.resource(:unapproved_cards, model: Decision) do
  before_action do
    unless current_user.organization_level == 1
      flash[:error] = I18n.t('admin.flash.unauthorized.message')
      # use your own 'home' url here
      redirect_to trestle.professional_cards_admin_index_path
    end
  end
 
 .
 .
 .

 menu do
    group I18n.t("menu_registration") do
      item :unapproved_cards, icon: "fas fa-folder-open", priority: 0 if current_user.organization_level == 1
    end
  end
end
```
I know it is not pretty, but it works. 

Unless you use trestle-auth with cancancan (or pundit I believe), then you can control menu and resources using the ability definition. It works as a charm, yet you need to use specific commit of branch authorization of trestle-auth in your Gemfile

```
gem 'trestle-auth', github: 'TrestleAdmin/trestle-auth', branch: 'authorization', ref: '7d164117a60ffb46f657c721874c01950c64a566'
```

if for example, user cannot manage Book, the corresponding book_admin.rb will not be added to the menu and it will not be accessible by url. If you try using url, it will flash unauthorized message.

**Comment by kxu1988** [comment]
> This is what I did for this specific resource:
> 
> ```ruby
> Trestle.resource(:unapproved_cards, model: Decision) do
>   before_action do
>     unless current_user.organization_level == 1
>       flash[:error] = I18n.t('admin.flash.unauthorized.message')
>       # use your own 'home' url here
>       redirect_to trestle.professional_cards_admin_index_path
>     end
>   end
>  
>  .
>  .
>  .
> 
>  menu do
>     group I18n.t("menu_registration") do
>       item :unapproved_cards, icon: "fas fa-folder-open", priority: 0 if current_user.organization_level == 1
>     end
>   end
> end
> ```
> 
> I know it is not pretty, but it works.
> 
> Unless you use trestle-auth with cancancan (or pundit I believe), then you can control menu and resources using the ability definition. It works as a charm, yet you need to use specific commit of branch authorization of trestle-auth in your Gemfile
> 
> ```
> gem 'trestle-auth', github: 'TrestleAdmin/trestle-auth', branch: 'authorization', ref: '7d164117a60ffb46f657c721874c01950c64a566'
> ```
> 
> if for example, user cannot manage Book, the corresponding book_admin.rb will not be added to the menu and it will not be accessible by url. If you try using url, it will flash unauthorized message.
> When using the second method please include something like this in your _admin.rb file
> 
> ```ruby
> Trestle.resource(:unapproved_cards, model: Decision) do
>   authorize_with cancan: Ability
>  .
>  .
>  .
> end
> ```

Thanks! I will the the second method
