### ISSUE TITLE
Creating has_many relations in multiple select field

### ISSUE THREAD

**Issue by jtruzzi** [TrestleAdmin/trestle#34]
Hi! I wanted to know if it's posible to add, to the edit form, a multiple select field for a has_many relationship. I tried with collection_check_boxes and it shows all the checkboxes, but it won't save. Also tried with collection_select and services, but it's not a multiple select and i won't save either.

Love the admin! I hope this is possible

Thanks!

**Comment by spohlenz** [comment]
Here is some sample code required to collection_select or collection_check_boxes work:

```ruby
collection_select :author_ids, User.all, :id, :name, { label: "Author(s)" }, { multiple: true }
```
or
```ruby
collection_check_boxes :author_ids, User.all, :id, :name, { label: "Author(s)" }
```

There might be a couple of things that are tripping you up: a) Make sure you use the `_ids` suffix on the field name, or b) For selects, `{ multiple: true }` is a separate, second options hash (for HTML options). You can use an empty hash for the first options hash if you don't need to set a custom label.

**Comment by spohlenz** [comment]
Closing. Feel free to re-open if it hasn't solved your issue.

**Comment by jtruzzi** [comment]
Hi sorry for the delay, i just tried it but i'm getting a "undefined method `services_ids' for #<Hotel" (that field is has_many relation to another model) . And when i remove the suffix, i get the multiple checkboxs showing correctly in the form, but when i post i get  " #<ActiveRecord::AssociationTypeMismatch: Service(#70191805563060) expected, got String(#70191807635240)>".

Any idea what am i doing wrong?

**Comment by spohlenz** [comment]
Try with `:service_ids` (service is singular). This is a method defined by Rails when you declare a has_many association (http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many).

Without the `_ids` suffix, it is trying to assign the IDs (array of strings) to the association, when it is expecting an array of `Service` objects.

**Comment by karan-ta** [comment]
I am facing this issue.

class Content < ApplicationRecord
	scope :alphabetical, -> { order(name: :asc) }
	belongs_to :type

class Type < ApplicationRecord
	has_many :content	
end

-----------------------------------form do |content|
      text_field :name
      text_field :hours 
      collection_check_boxes :type_ids, Type.all, :id, :name, {label: "Types"}
  end
-------------------------

form do |content|
      text_field :name
      text_field :hours 
      collection_check_boxes :type_ids, Type.all, :id, :name, {label: "Types"}
  end

**Comment by karan-ta** [comment]
i am facing this issue.

please see pastebin - https://pastebin.com/ipEB6w0Z
