### ISSUE TITLE
Issues with an `Action` model

### ISSUE THREAD

**Issue by Tao-Galasse** [TrestleAdmin/trestle#347]
Hi!

I have some troubles to create a form because one on my models is called `Action`. It seems to be a word used internally when passing parameters to the controller (to declare the method to call), and causes the params I want to save in the db to be erased.

The params passed to the controller look like this :
`#<ActionController::Parameters {"authenticity_token"=>"FNb7XDhUSJpzhGVJ8b7e0gyryYqMDpd9h-l0YiZei-kzeHlp_El5b-R_RWae7s-aY-9Vje388gcpZSXgt4xl-Q", "action"=>"create", "button"=>"", "controller"=>"actions_admin/admin"} permitted: false>`

Usually, I would have another key containing the name of my model with the params passed on the UI, but it's not possible because the model is called `action` too.

It there a way to enforce trestle to use a custom name for the record, to be able to keep the `"action"=>"create"` in the parameters AND to get the values I want to save ?

Thanks you 🙏

**Comment by spohlenz** [comment]
It is possible to override the parameter name used for the model params with the following:

```ruby
Trestle.resource(:actions) do
  admin do
    def parameter_name
      "action_model"
    end
  end
end
```

**Comment by Tao-Galasse** [comment]
That's exactly what I needed, thank you very much 🙏
