### ISSUE TITLE
Security issue. Useless CSRF check.

### ISSUE THREAD

**Issue by edgarMeinart** [TrestleAdmin/trestle#354]
Hi!

I have detected that `protect_from_forgery` doesn't work with the TrestleAuth in conjunction with the Devise. 
Tested over several productions, all 3rd party form actions are successfully passed and performed.
I think the default Rails value `null_session` for `protect_from_forgery` not working properly, quickly workaround is to use `with: :exception`
 https://github.com/TrestleAdmin/trestle/blob/master/app/controllers/trestle/application_controller.rb#L2

Sorry guys, there is no time from my side to discover the issue deeper.

**Comment by spohlenz** [comment]
If you are using trestle-auth 0.4.0 or 0.4.1, please see the security advisory at https://github.com/TrestleAdmin/trestle-auth/security/advisories/GHSA-h8hx-2c5r-32cf and upgrade to 0.4.2.

If you are already on trestle-auth 0.4.2, could you please let me know your trestle and Rails versions and I will try to investigate further.
