### ISSUE TITLE
Travis-CI not building, needs OSS subscription

### ISSUE THREAD

**Issue by timdiggins** [TrestleAdmin/trestle#356]
Travis CI has stopped building because it now requires an OSS subscription. 

Sam, I think it's easiest if you @spohlenz can request this from support@travis-ci.com. I've opened a ticket https://support.travis-ci.com/hc/requests/28409 but they need the project lead / regular committer to lead the request and validate various things. I've cced you in that request, so hopefully you'll get that, but just making an issue so you can track it if not.

**Comment by spohlenz** [comment]
Thank you @timdiggins for taking the charge on this. It looks like Travis support has now added in the necessary credits for continuing builds for the project.
