### ISSUE TITLE
Disabling resource/authorizing

### ISSUE THREAD

**Issue by quantavi** [TrestleAdmin/trestle#357]
Currently we are using Trestle along with trestle-auth plugin and CanCanCan. We have two resources that use the same models underneath, so with CanCanCan/Trestle it is all or nothing.
Let's say that both use model PersonalCard. If the user can read the Personal card it will see both resources, however we would like to control that some other way.
For example user can read PersonalCard, but should be able only to access :authority_cards and not :personal_cards, even though they are both registered like this:
```ruby 
Trestle.resource(:authority_cards, model: PersonalCard) do
.
.
.
end
```
```ruby
Trestle.resource(:personal_cards, model: PersonalCard) do
.
.
.
end
```

How can this be achieved?

In one of issues @spohlenz suggested overriding the authorize method
```ruby
authorize do
.
. (code here)
.
end
```
but don't know what code should be inside of it. Once I added the block the resource disappears from the menu.

Any help appreciated!

**Comment by spohlenz** [comment]
Check out the README within the `authorization` branch at https://github.com/TrestleAdmin/trestle-auth/tree/authorization#built-in-dsl. It's easy to miss -- I need to finish off the last few small items and get that merged into master.

If that still leaves unanswered questions, please let me know and I will do my best to help.

**Comment by quantavi** [comment]
@spohlenz Thanks. That was what I was looking for :)
