### ISSUE TITLE
can I get the Administrator instance in a resource's table block?

### ISSUE THREAD

**Issue by i-free-developer** [TrestleAdmin/trestle#369]
Using Trestle and TrestleAdmin in some projects, really like the admin. 

One project like to have different Administrator access, such as some Administrator would be readonly, some would be editable...

I can get the Administrator instance in the form block, but can not get it in the table block. 

form do |model|
    if current_user.super_admin?
        # current_user is the login Administrator instance
        # customized form fields
    else
        # other customized form fields
    end
end

Is there any way I can get the Administrator instance  in the table block?

table do
    column :id, link: true, sort: :id
    if current_user.super_admin?
      # customized columns
    else
      # other customized columns
    end
end

**Comment by spohlenz** [comment]
You can pass the `:if` (or `:unless`) options to the columns, with a proc containing your conditional.

e.g.

```ruby
table do
  column :secret, if: -> { current_user.super_admin? }
end
```

**Comment by i-free-developer** [comment]
Thank you! That's what I'm looking for. 

It works very well. Saved me again!
