### ISSUE TITLE
Disable some fields in update form

### ISSUE THREAD

**Issue by dendomenko** [TrestleAdmin/trestle#37]
How can I disable some fields only on edit form?

**Comment by spohlenz** [comment]
To make them read-only on the edit form set the :readonly option on the fields.

```ruby
form do |instance|
  text_field :name, readonly: instance.persisted?
end
```

Alternatively to remove them from the form entirely, wrap the fields in an `if` block:

```ruby
form do |instance|
  if instance.new_record?
    text_field :name
  end
end
```
