### ISSUE TITLE
Avoid duplicates the same code in two admin panels

### ISSUE THREAD

**Issue by mateuszbozek** [TrestleAdmin/trestle#371]
Hello everyone. Is it possible to create a `form` for view which can be used in many others admin panels ? I just what to avoid duplicates the same form in two admin panels.

For example in

customer_admin.rb
...
```
form do
 tab :customer do
      text_field :name
      text_field :surename
      text_field :email
      editor :body
    end
end
```

deleted_customer_admin.rb
...
```
form do
 tab :customer do
      text_field :name
      text_field :surename
      text_field :email
      editor :body
    end
end
```

I will be grateful for advices.

**Comment by spohlenz** [comment]
The best way to do this currently is to first create a partial, e.g. `admin/shared/_customer.html.erb`. Within this partial, you can define the form fields, although you will need to use ERB and prepend field calls with `form.`. e.g.

```ruby
<%= form.text_field :name %>
<%= form.text_field :surname %>
<%= form.text_field :email %>
<%= form.editor :body %>
```

Then from your admins, you can reference this partial using either of the following methods:

1. Use the partial as the tab content:

```ruby
tab :customer, partial: "admin/shared/customer"
```

2. Render the partial from within the tab:

```ruby
tab :customer do
  render "admin/shared/customer"
end
```
