### ISSUE TITLE
Avoid index view to redirect to edit view

### ISSUE THREAD

**Issue by Tao-Galasse** [TrestleAdmin/trestle#380]
Hi !

I'm looking for a way to add a new custom resource, which should not redirect to an index view when clicking on it in the menu, but directly on the edit page of a record. I have a very specific table with only one record on it, so i don't want to show a list and would prefer to redirect to the edit page.

Do you know how I could achieve this ?

Thank you very much ! 😄

**Comment by spohlenz** [comment]
I believe a singular admin will do what you want here. To use it, specify the `singular: true` option on your Trestle resource and then define an `instance` block to load the specific model instance. You might also want to remove a few of the unnecessary actions too depending on your use case.

e.g.

```ruby
Trestle.resource(:my_model, singular: true) do
  instance do
    MyModel.first
  end

  remove_action :new, :edit, :destroy

  form do |instance|
    ...
  end
end
```
