### ISSUE TITLE
Multiple Trestle instances

### ISSUE THREAD

**Issue by dmbrooking** [TrestleAdmin/trestle#384]
Hi... I have a use case where I have 2 distinct types of admin accounts in our system and it'd make more sense to have two completely different instances of Trestle within the app. 

Is that possible?

**Comment by spohlenz** [comment]
This unfortunately isn't possible right now as there is only one admin namespace in Trestle. It is something I would like to support in future but I haven't looked into how complex a change that would be.

The closest option I can suggest is to look at the [authorization branch of trestle-auth](https://github.com/TrestleAdmin/trestle-auth/tree/authorization), which will allow you to conditionally allow access to the relevant admins for each particular admin type.

**Comment by dmbrooking** [comment]
OK thanks!
