### ISSUE TITLE
Performance issue using Trestle in production with CanCanCan

### ISSUE THREAD

**Issue by quantavi** [TrestleAdmin/trestle#385]
On production we have around 100k records. We noticed a huge performance hit. 

It looks like the code, to check wether the menu item should be visible is causing it.
We added extended logs to trestle.rb: 
```ruby
 def self.navigation(context)
    Rails.logger.debug "Start: " + Time.now.to_i.to_s
    blocks = config.menus + admins.values.map(&:menu).compact
    Rails.logger.debug "Middle: " + Time.now.to_i.to_s
    nav = Navigation.build(blocks, context)
    Rails.logger.debug "End: " + Time.now.to_i.to_s
    nav
  end
```

this produces:
```
D, [2021-12-05T20:08:02.363200 #4275] DEBUG -- : [b991d403-9e08-4932-92df-13470c22e009] Start: 1638731282
D, [2021-12-05T20:08:02.363443 #4275] DEBUG -- : [b991d403-9e08-4932-92df-13470c22e009] Middle: 1638731282
D, [2021-12-05T20:08:22.229331 #4275] DEBUG -- : [b991d403-9e08-4932-92df-13470c22e009] End: 1638731302
I, [2021-12-05T20:08:22.233636 #4275]  INFO -- : [b991d403-9e08-4932-92df-13470c22e009]   Rendered /usr/local/rvm/gems/ruby-2.7.1/gems/trestle-0.9.4/app/views/trestle/shared/_sidebar.html.erb (Duration: 19871.0ms | Allocations: 21900857)
```

Which shows 20 seconds for that function. It is not taking hit to display the records. Only for manu items. Any ideas why?

The performance is ok ( of course we see items, that shouldn't be there) when we added line navigation.rb in trestle-auth:
```ruby
 def visible?(context)
            return true # this was added
            return false unless authorized?(context)
            super
end
```

We are using Trestle 0.9.4 and trestle-auth 0.4.0.

**Comment by courtsimas** [comment]
We've noticed the same thing! When we got to 80k. It's bizarre. It's not the sql query itself (which is indexed, and fast).

**Comment by quantavi** [comment]
> We've noticed the same thing! When we got to 80k. It's bizarre. It's not the sql query itself (which is indexed, and fast).

@courtsimas Please check the newest commits of trestle-auth (on authorization branch). I have been communicating with @spohlenz and he was so great to prepare fix for this! I haven't integrated/tested it yet as I just got the news. Basically, the proposed solution is to cache ability class through out the request.

**Comment by courtsimas** [comment]
@quantavi it helped! It went from timing out on heroku (30 seconds), to loading in about 12 seconds. It runs in less than a second in console, (the query), but I'll take 12 seconds over timing out. Much improvement!

**Comment by quantavi** [comment]
@courtsimas I am glad it did. Maybe something else(not Trestle) is causing delay? Did you try profiler? I used https://github.com/rbspy/rbspy among other things to locate this bug.

@spohlenz thank you for your work. In our case, the improvement is huge.

**Comment by spohlenz** [comment]
@quantavi I'm glad to hear that has helped in your situation.

@courtsimas 12 seconds is definitely still much slower than I would expect it to be. If you are able to reproduce this in a sample application with some fake data, I would be very interested in looking into this further.
