### ISSUE TITLE
Adding custom view helpers

### ISSUE THREAD

**Issue by rennanoliveira** [TrestleAdmin/trestle#4]
Are there any non-hacky ways to add custom helpers to the views?
Example:

```ruby
# In my project using trestle
module ApplicationHelper
  def custom_method(name)
    ...
  end
end

Trestle.resource(:posts) do
  table do
    column :author, ->(post) { custom_method(post.author_name) }
  end
end
```

Maybe loading whatever's on app/helpers/trestle on the main app

**Comment by mariomarroquim** [comment]
Yes, this would be much appreciated. I developed this in an ActiveAdmin webapp, but It was very "hacky"

**Comment by spohlenz** [comment]
You can include helpers on a per-admin basis using the `helper` method. e.g.

```ruby
Trestle.resource(:posts) do
  helper ApplicationHelper
end
```

I plan on adding a `config.helper` option to include helpers globally, as well as a `config.helper_paths` option which would function the way you have suggested.

**Comment by spohlenz** [comment]
7e56d08 introduces a `config.helper` option that can be used to include helpers across all of your admins. It can be used as follows:

```ruby
Trestle.configure do |c|
  c.helper ApplicationHelper
end
```

You could also call `config.helper :all` to include all of your application's helpers.
