### ISSUE TITLE
How to have different form for new and show actions?

### ISSUE THREAD

**Issue by dmbrooking** [TrestleAdmin/trestle#403]
From the index view for a User resource, for adding a new user, I want a form modal to pop up that has minimum fields - name, email, password.  I then want the show view to use a much more detailed form so when someone clicks on an existing user in the table, all fields associated with the User are visible.

Is this possible?

I'm thinking of having my form definition in the admin file be the new modal and then implementing my own edit view for the resource - but I'd like to avoid this as the edit form is pretty complex with multiple tabs and sidebars and I'm not sure I still have access to the handy Trestle DSL in custom views?

**Comment by spohlenz** [comment]
For this type of behavior, I would generally wrap the 'detailed' fields (to only show on the edit forms) with `if instance.persisted?`. Replace instance with the name of your resource that you passed to the form block, e.g. `user`.

**Comment by dmbrooking** [comment]
This worked. Thanks!
