### ISSUE TITLE
tabs inside tabs

### ISSUE THREAD

**Issue by okliv** [TrestleAdmin/trestle#42]
i would like to render something like this

``` ruby
form do |instance|
  tab '1' do
    tab '1.1' do
      'content 1.1'
    end
    tab '1.2' do
      'content 1.2'
    end
  end
  tab '2' do
  end
end
```

but receive one flat tab nav panel ( 1 | 1.1 | 1.2 | 2 ). is this a bug or nested tabs are not supported\can not be implemented?

**Comment by spohlenz** [comment]
Nested tabs (at least using the tab helpers) probably won't be supported in the near future.

However you may be able to work around this by rendering your own partial. e.g.

```ruby
form do |instance|
  tab '1' do
    # Renders app/views/admin/admin_name/_mytabs.html.erb
    render 'mytabs'
  end
  tab '2' do
  end
end
```

You'll need to set up the HTML for the tabs and panes within the partial yourself (see https://getbootstrap.com/docs/3.3/javascript/#markup), but this approach should hopefully work.

Within the partial, you can refer to the form builder using the `form` helper.
