### ISSUE TITLE
select empty if no relation?

### ISSUE THREAD

**Issue by samnymr** [TrestleAdmin/trestle#428]
Hiya

So i've trying to allow users to relate products to products without having to do any extra tables

I've tried both of these below:

      # select :shop_the_look_product_ids, Product.all, { label: "Category" }, multiple: true
      # collection_select :shop_the_look_product_ids, Product.all, :id, :name, { label: "Category" }, { multiple: true }

both are saving into the database as ["", "6", "7"] but for whatever reason when looking at the field in the admin it shows as blank?

some help with this would be amazing!

**Comment by spohlenz** [comment]
Could you share a bit more of what your tables, models and relations look like? From "without having to do any extra tables", I'm guessing you are possibly using an array DB column and not using a regular Rails `has_many`?

**Comment by samnymr** [comment]
As I came to reply I just solved it, again thinking this was me being stupid, Ended up having to do a string in the database with array: true and it worked first time...
