### ISSUE TITLE
How to add icons in sidebar buttons?

### ISSUE THREAD

**Issue by basharabdullah** [TrestleAdmin/trestle#429]
I am trying to add Font Awesome icons to sidebar button. Is there a way to do this?

```
      form_group :generate_invoice, label: false do 
        link_to("Generate Invoice", "/charges/#{invoice}",  method: :get, icon: "fa-solid fa-receipt",
          class: "btn btn-success btn-block", target: "_blank") 
      end 
```

Thanks

**Comment by mvondoyannick** [comment]
Try this
```
form_group :generate_invoice, label: false do 
  link_to "/charges/#{invoice}",  method: :get, class: "btn btn-success btn-block", target: "_blank"  do
    icon('fa-solid', 'user-secret', class:"fa-7x, fa-shake")
    Generate Invoice
  end
end 
```

**Comment by basharabdullah** [comment]
> form_group :generate_invoice, label: false do 
>   link_to "/charges/#{invoice}",  method: :get, class: "btn btn-success btn-block", target: "_blank"  do
>     icon('fa-solid', 'user-secret', class:"fa-7x, fa-shake")
>     Generate Invoice
>   end
> end

Thanks for the suggestion! It gave error around Generate Invoice. I wrapped it with strings, and it just showed the text without icon. Did it work for you?

**Comment by spohlenz** [comment]
There are a couple of issues compounding here:

1. With the `icon` helper, all classes should be passed as regular arguments (not as a `class` option, though other HTML attributes can be passed as options). e.g.

```ruby
icon("fa-solid", "fa-receipt") # Although I would typically just do icon("fas fa-receipt")
icon("fa-solid", "fa-user-secret", "fa-7x", "fa-shake")
```

2. Within the admin form builders, when a block is used (such as `form_group` or `link_to`) the last value is the only one that is returned (usually -- there are some exceptions). In the last example, that is the string `"Generate Invoice"`. To get around this, you can either `concat` each value:

```ruby
link_to ... do
  concat icon("fas fa-receipt mr-2")
  concat "Generate Invoice"
end
```

or do a `safe_join`:

```ruby
link_to ... do
  safe_join([
    icon("fas fa-receipt mr-2"),
    "Generate Invoice"
  ])
end
```

**Comment by basharabdullah** [comment]
> ```ruby
>   concat icon("fas fa-receipt mr-2")
>   concat "Generate Invoice"
> ```

Thanks a lot. That's excellent explanation. Code works now.
