### ISSUE TITLE
actions column enhancements

### ISSUE THREAD

**Issue by okliv** [TrestleAdmin/trestle#43]
I tried to do something like this

```ruby
table do
  #...
  actions header: 'Act', data: {info: 'some info'}
end
```

but received `wrong number of arguments (given 1, expected 0)`

if i look to the code 

```ruby
def actions(&block)
  table.columns << ActionsColumn.new(table, &block)
end
```

this is expected but i think it would be useful to have exact same options as for any other table's column

And another request:

for now, as i can see, there is only one action: `delete` (but method name is plural - `actions`), so it is not makes much sense to use a block construction unless - see my code comments above

```ruby

actions do |a|
  a.delete
  a.show # or a.edit would be useful too, in case user want to disable default full-row "clickability" with admin: false option (as i digged somehow - maybe it is wrong)
  a.any_other_custom_action #defined in controller do end block
end
```

and so, if actions will become really plural (multiple), they possibly need a `btn-group` bootstrap container

**Comment by spohlenz** [comment]
These issues (except for the `btn-group`) have now been addressed in cdd5d9712b8424b13ccffe3cbb28aa45bee1fd58 and a5bd3362cd8a4e442d943831057079ff3bb806d2.

The following code now works (`button` was already implemented for custom actions, but the `show` and `edit` shorthands have been added).

```ruby
actions header: "Act", data: { foo: "bar" } do |a, instance|
  a.show
  a.edit
  a.delete
  a.button icon("fa fa-magic"), my_custom_admin_path(instance), class: "btn-primary"
end
```

I'm in two minds about adding a `btn-group` wrapper. I quite like the way it looks as separate buttons, but it also works well as a group.
