### ISSUE TITLE
Listing dates per page

### ISSUE THREAD

**Issue by Guih12** [TrestleAdmin/trestle#432]
Hello guys. How are you? Guys, i need a help. How i to implement a new component in dashboard of trestle? 

My idea is to implement a component that have numbers to listing 

See a example of like i want to implement 
![image](https://user-images.githubusercontent.com/55898683/210796500-88fdeada-22b6-47ca-b582-03729dc7bfe1.png)

I know that it is not nature of Treslte, but somebody can me help?

**Comment by joshmn** [comment]
The easiest way to do this is to want to copy `app/views/trestle/resource/_scopes.html.erb` from Trestle gem into your views folder and make the necessary changes, and then some real hacky stuff on the collection:

```
Trestle.resource(:movies) do 
  collection do
    admin.pagination_options[:per] = params[:per]
    Movie.all 
  end
end
```

Make sure that you're returning a relation in the `collection` block.
