### ISSUE TITLE
uninitialized constant custom field rails 7

### ISSUE THREAD

**Issue by alxlion** [TrestleAdmin/trestle#434]
Hello,

I try to add a new custom field according to https://github.com/TrestleAdmin/trestle/wiki/How-To:-Make-a-Custom-Form-Field 

I have
`app/fields/address_field.rb`

```
class AddressField < Trestle::Form::Field
  def field
    content_tag :div, class: "col-span-6 grid grid-cols-6 gap-6" do
      builder.raw_rich_text_area(name, options)
    end
  end
end
```

`config/initializers/trestle.rb`

```
...
config.form_field :address, AddressField
...
```

When I start the server I get an error: 

```
config/initializers/trestle.rb:128:in `block in <main>': uninitialized constant AddressField (NameError)

  config.form_field :address, AddressField
                              ^^^^^^^^^^^^
```

Do you know what I missed ? 

thanks

**Comment by matthieubrau** [comment]
+1

Was working with rails 5 not with rails 7

**Comment by spohlenz** [comment]
With Rails 7, you will need to use a Proc (or a String) when referencing classes from `app/` within the Trestle initializer:

```ruby
config.form_field :address, -> { AddressField }
```

This will ensure that it is loaded lazily and will pick up any changes if/when the class is reloaded.

**Comment by alxlion** [comment]
Yes it works ! Nice to add in the wiki 😉  

Thanks !
