### ISSUE TITLE
Changing date format

### ISSUE THREAD

**Issue by dylan-hoefsloot** [TrestleAdmin/trestle#435]
The docs site is down and I can't find anything on the website or github describing how to change format of dates.

I am looking to change the date format from `mm/dd/yyyy` to `dd/mm/yyyy` in my admin pages.

**Comment by joshmn** [comment]
You might be able to change the locales: https://github.com/TrestleAdmin/trestle/blob/main/config/locales/en.rb

**Comment by dylan-hoefsloot** [comment]
@joshmn This got me halfway there, the dates in the list view for objects are now in the correct format, however the date selectors in any forms still show the old format, I'm wondering if the form fields have the options to specify format, but I can't find a list of the options anywhere. 

Any ideas?

**Comment by dylan-hoefsloot** [comment]
Looking at [this existing issue](https://github.com/TrestleAdmin/trestle/issues/275) and doing something suggested there like [this](https://github.com/TrestleAdmin/trestle/blob/main/config/locales/de.yml#L97-L101) didn't work either.
