### ISSUE TITLE
image/file uploading/processing/serving over shrine/carrierwave etc

### ISSUE THREAD

**Issue by okliv** [TrestleAdmin/trestle#44]
Hi, again =)!

Any plans on integration with something like

http://shrinerb.com
https://github.com/carrierwaveuploader/carrierwave

to handle files, render thumbnails etc?

if no, maybe there is some quick advices how can i try to integrate, let it be, shrine, with trestle by myself?

thanks

**Comment by spohlenz** [comment]
I know that there is a Trestle user who is currently working on an ActiveStorage plugin for Trestle. They're looking at putting it into production soon, and I've promised I'll link to them from the wiki or README once they are ready to publish.

For Shrine integration, most of the integration probably isn't too Trestle-specific if you stick with the regular `file_field`. I'd suggest starting with a tutorial such as https://www.sitepoint.com/rails-file-uploading-you-can-believe-in-with-shrine/. You should be able to ignore most of the controller-related code, as Trestle's default resource controller should work the same. For the view code, you may find it easier to create a partial and call `render "partial"` from the form block.

**Comment by okliv** [comment]
ActiveStorage is not an option for me, as far as i understand, just because it works only with ActiveRecord but i use Sequel... so, ok... will try to do it by myself. thanks
