### ISSUE TITLE
Best Way To Provide a Select Dropdown for belongs_to that is optional

### ISSUE THREAD

**Issue by jonmchan** [TrestleAdmin/trestle#451]
I would like to create a select dropdown for a `belongs_to :user, optional: true`. 

If I just put `select :user_id, User.all`, if there is nothing selected, it always selects the first one. There is no blank in the list. Is there any way to achieve this? This is the hack I have used, is this the best way to do this?

```
select :user_id, User.all.to_a.append(['<none>', nil])
```

Thanks!

**Comment by spohlenz** [comment]
You can use the `:include_blank` option to specify a default nil selection:

```ruby
select :user_id, User.all, include_blank: "<None>"
```

To make it clearable after assignment, also add `allow_clear: true`:

```ruby
select :user_id, User.all, include_blank: "<None>", allow_clear: true
```

**Comment by jonmchan** [comment]
Works perfectly! Thank you!
