### ISSUE TITLE
Enum Radio Button Missing Current Selection

### ISSUE THREAD

**Issue by jonmchan** [TrestleAdmin/trestle#454]
Enum support was added in #379. However, the code does not appear to capture the currently selected option. This leads to an issue where enum values are lost when you use trestle admin. I believe the enum needs the checked option set (something like `collection_radio_buttons(attribute.name, values, :first, :last, { checked: instance.public_send(attribute.name) })`).

Here's how it shows up by default even when I have a value set for this enum:

<img width="549" alt="image" src="https://github.com/TrestleAdmin/trestle/assets/1827190/9705a3f9-ab22-449e-b7a0-e01767621b56">

**Comment by spohlenz** [comment]
Are you seeing this behavior on the `main` branch? This should theoretically be fixed by 55963f56fff687f1931257564c639da252822d30 but I haven't made a new release containing that fix yet.

**Comment by jonmchan** [comment]
I haven't tried on main branch yet, I'll give it a shot.

**Comment by jonmchan** [comment]
no go:

```
irb(main):008:0> Response.find(5).response_state
  Response Load (0.6ms)  SELECT "responses".* FROM "responses" WHERE "responses"."id" = $1 LIMIT $2  [["id", 5], ["LIMIT", 1]]
=> "sent"   
```

![image](https://github.com/TrestleAdmin/trestle/assets/1827190/08c8d275-a962-4013-9ca6-4b64f36bb1ff)

```
GIT
  remote: https://github.com/TrestleAdmin/trestle.git
  revision: d89b3b8550879f24faa6a9510f072a3337a0bb38
  branch: main
  specs:
    trestle (0.9.8)
      activemodel (>= 5.2.0)
      kaminari (>= 1.1.0)
      railties (>= 5.2.0)
      sprockets-rails (>= 2.0.0)
```

**Comment by spohlenz** [comment]
How are you declaring the enum in your model?

In my testing, I've been testing for three types of declarations:

1. String backed enum with a hash declaration:
```enum status: { draft: "Draft", published: "Published", junk: "Junk" }```

2. Integer backed enum with an array declaration:
```enum status: %w(draft published junk)```

3. Integer backed enum with a hash declaration:
```enum status: { draft: 0, automated: 1, mixed: 2 }```

These all behave correctly in my own testing, but perhaps I've missed another option.

To cover all bases, could you also please let me know your Rails (and Ruby) versions?

**Comment by jonmchan** [comment]
I am defining it like this:

```
  enum response_state: {
    created: 0,
    awaiting_agent_input: 10,
    rejected_by_agent: 90,
    sent: 100
  }
```

```
root@a3a68b4ee119:/app# bin/rails -v
Rails 6.1.6
root@a3a68b4ee119:/app# ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
```

Thanks for investigating into this -  I thought everyone had this issue.

**Comment by spohlenz** [comment]
I'm at a bit of loss -- I've created a fresh Rails 6.1.6 app which matches your setup (as far as I can tell) and it works for me.

I've pushed the repo up to https://github.com/spohlenz/TrestleEnums-jonmchan. Perhaps you might be able to trace the commits to see where things might differ within your app.

**Comment by jonmchan** [comment]
Let me look through my application and see if I have anything custom installed. This is certainly puzzling!

**Comment by jonmchan** [comment]
Just to double check, I checked out your example and ran it locally, it worked as expected. 

![image](https://github.com/TrestleAdmin/trestle/assets/1827190/bf31c188-1443-4555-ac81-2924f0102a31)


I did notice on my project, it is rendering the table column as string and not the box:

![image](https://github.com/TrestleAdmin/trestle/assets/1827190/a130273f-e702-4416-a385-a6653e58f3d5)


vs yours:

![image](https://github.com/TrestleAdmin/trestle/assets/1827190/3abb1913-4da4-4cf1-86e6-20d6a4dba873)

Is this indicative of anything?

The only other difference I see is your version is using sqlite. I'm going to try switching your project to postgres and see if it breaks.

**Comment by jonmchan** [comment]
switched the example project to pg, still works... so it isn't PG... I'll continue investigating into this.

**Comment by jonmchan** [comment]
Got it working in my project! It's a bit embarrassing, but I may have not restarted my rails server when switching to the github branch. The latest changes does indeed fix this issue.

![image](https://github.com/TrestleAdmin/trestle/assets/1827190/e7bbb630-0c04-4586-9a28-869f98830a95)

**Comment by spohlenz** [comment]
Thanks for the update. Glad to hear it's all sorted!
