### ISSUE TITLE
[Datetime Field / Safari] Screen freeze on datetime field manipulation with Popup behavior on Safari

### ISSUE THREAD

**Issue by GabGab** [TrestleAdmin/trestle#463]
Hello everyone, 

I'm on a Rails 6 project, with Trestle 0.8.13 and Trestle-search 0.3.0.
I'm testing with Safari 17.5, and Chrome 125.0.6422.142

I have a Task model and am using Trestle to let an admin create/update tasks. 
In the form, which has the `dialog: true` option, i have simple `datetime_field` fields.

On Chrome, everything works perfectly fine.
On Safari however, when i click on the field, a calendar opens nicely. But once i interact once with it (for example by selecting a date), the interaction goes through (the date is selected) but then the whole browser freezes and i can't do anything.

I have noticed this behavior only with the `dialog: true` option activated on the form, i have other datetime fields in other forms (which are not displayed in a dialog), and there is no freeze on Safari.

This is a screen after the freeze happens : 

<img width="896" alt="Capture d’écran 2024-06-18 à 11 11 45" src="https://github.com/TrestleAdmin/trestle/assets/1652333/f268d322-79a9-4f87-9334-8af300b24561">

A javascript error happens in the console : 

<img width="1438" alt="Capture d’écran 2024-06-18 à 11 12 00" src="https://github.com/TrestleAdmin/trestle/assets/1652333/4e1c03c6-17f0-4396-90df-65efac9943fc">

To reproduce, simply use a standard Trestle admin model and code a form like this : 

```
form dialog: true do |task|
      row do
        col(xs: 6) {
          datetime_field :datetime_column1
        }
        col(xs: 6) {
          datetime_field :datetime_column2
        }
      end
end
```

Are you able to reproduce this behavior ? If so, do you know what could cause this specific problem ? 

Thank you for your help!

**Comment by spohlenz** [comment]
I am able to reproduce this with Trestle 0.8.13 (on Chrome as well). However this is a particularly old release.

Trestle 0.9.x does not exhibit this behavior. Are you able to upgrade to version 0.9.9?

**Comment by GabGab** [comment]
Hi again @spohlenz !

The update to 0.9.9 indeed fixed the Safari freeze on datetime field change, thank you for that !
I'm having another issue after the update but as it is a different topic, i will create a new Issue for it :)

I don't know what's the best practice, should i close this issue myself or do you ? 

Thanks again for your timely help

**Comment by spohlenz** [comment]
Glad to hear it's resolved.
