### ISSUE TITLE
[v0.10.0.pre] Link_to(method: :post) no longer working

### ISSUE THREAD

**Issue by jonmchan** [TrestleAdmin/trestle#468]
After upgrading to v0.10.0.pre, I noticed that my link_to with `method: :post` is no longer working. I assume this is due to certain javascript libraries that are no longer loaded.

Here's the button in a custom sidebar:

```
link_to('Activate User Account', admin.path(:activate_user, id: instance.id), method: :post, class: "btn btn-primary btn-block")
```

It used to send a POST request, now it is sending a GET request and resulting in a 404 error because only the POST endpoint exists.

**Comment by jonmchan** [comment]
The solution is all these links have to be migrated to use turbo post method. Might want to mention this in the upgrading notes.

```
link_to('Activate User Account', admin.path(:activate_user, id: instance.id), method: :post, class: "btn btn-primary btn-block")
```

becomes:

```
link_to('Activate User Account', admin.path(:activate_user, id: instance.id), {data: {turbo_method: :post}, class: "btn btn-primary btn-block"}))
```

Feel free to close this. :)

**Comment by spohlenz** [comment]
Thank you. I've added some comments on this to the Breaking Changes section of the 0.10.0.pre release notes.
