### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/fa-solid-900.ttf") bump from 0.9 to 0.10

### ISSUE THREAD

**Issue by eddygarcas** [TrestleAdmin/trestle#479]
I've just update Trestle admin version from 0.9 to 0.10 an running the server i start getting this route not match error:

`ActionController::RoutingError (No route matches [GET] "/fa-solid-900.ttf"):`

I ran the `rails generate trestle:install` afterwards just i case, but no luck. Also I have a custom theme to change the background colors, etc...but they are not picked up.

Any help?

**Comment by spohlenz** [comment]
> I've just update Trestle admin version from 0.9 to 0.10 an running the server i start getting this route not match error:
> 
> `ActionController::RoutingError (No route matches [GET] "/fa-solid-900.ttf"):`

First off, I assume you're using Sprockets (rather than Propshaft) since it's an upgrade. Let me know if that's incorrect.

Trestle 0.10.0 now includes the stylesheets with the FontAwesome Sprockets paths separately -- https://github.com/TrestleAdmin/trestle/blob/main/app/views/layouts/trestle/admin.html.erb#L19.

Do you see that `<link>` tag being output?

```html
<link rel="stylesheet" href="/assets/trestle/icons/font-awesome.debug-f6575a715181bbbd79ccbec8156ebb917e7a8081aa288ab7333663f37f3c0d48.css" data-turbo-track="reload" />
```

One thing that might help is to clear out any stale assets and Sprockets caches:

```sh
$ rails assets:clobber
$ rails tmp:cache:clear
```

> Also I have a custom theme to change the background colors, etc...but they are not picked up.

Theming in Trestle 0.10.0 works a little differently to previous versions, in order to remove the requirement for a Sass compiler. Instead of defining theme variables within `app/assets/stylesheets/trestle/_custom.scss`, the primary and secondary colors can now be set within `config/initializers/trestle.rb`:

```ruby
# Define primary and secondary theme colors. Color values may be specified
# as either 3- or 6-digit hex codes, or rgb/hsl() triplets.
config.theme = { primary: "#338ab7", secondary: "#719dc3" }
```

Any other CSS customizations can be added to `app/assets/stylesheets/trestle/custom.css`.

**Comment by eddygarcas** [comment]
> Theming in Trestle 0.10.0 works a little differently to previous versions, in order to remove the requirement for a Sass compiler. Instead of defining theme variables within app/assets/stylesheets/trestle/_custom.scss, the primary and secondary colors can now be set within config/initializers/trestle.rb:

regarding styles, that made the trick, thanks, I was able to move all the styles into `custom.css` and setup the primary and secondary in the initializer.

> Do you see that <link> tag being output?

I saw that `admin.html.erb` has this stylesheet link tag defined:
` <%= stylesheet_link_tag "trestle/icons/font-awesome", 'data-turbo-track': 'reload' if defined?(Sprockets) %>`
and I don't see this line inspecting the resultant html code but getting the routing error.
I'll review the whole app configuration see if I can find a root cause for that.

**Comment by mattbee** [comment]
We're also experiencing routing errors in our app, for example the following route worked on 0.9.0 but it gives a 404 in the browser. What I found interesting is that after writing a spec to test the route works. 

```
Trestle.resource(:our_model) do
  ...
  controller do
    def controller_method
      ...do stuff...
    end
  end
  
  routes do
    post :controller_method, on: :member
  end
end
```

As a side note, it seems to work in 0.9.0 **and** 0.10.0 **_in our RSpec suite_**, but just not in the browser (I am currently treble checking our tests are not somehow still using 0.9.0 despite defining 0.10.0 in our Gemfile for the test)

**Comment by spohlenz** [comment]
@mattbee There haven't been any changes on the routing side between the two versions (and you can also verify the route is active using the `rails routes` command.

However I am guessing you have a link that is using the old Rails-UJS style with `method: :post`. This will need to be changed to `data: { turbo_method: :post }` for 0.10.0. I am thinking it may be worth putting in an automatic conversion for 0.10.1.

**Comment by eddygarcas** [comment]
> turbo_method: :post

Yes, that worked for me. Thanks.
