### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by seanarnold** [TrestleAdmin/trestle#5]
Are there any plans to add a basic auth authentication method?

I don't need actual users for my use case.

**Comment by mariomarroquim** [comment]
That would be really nice. I wonder if it could be done by using a before action / filter in the application_controller.

**Comment by seanarnold** [comment]
It doesn't look as though the Trestle controllers inherit from ApplicationController.

**Comment by spohlenz** [comment]
I'll look at adding a `config.before_action` option that could be used to inject before actions into the `Trestle::ApplicationController` base class (which is different from your app's `ApplicationController`).

This would make HTTP basic auth easy, and also provide a handy insertion point for new functionality.

**Comment by 42thcoder** [comment]
```ruby
module TrestleDeviseAuth
  extend ActiveSupport::Concern

  included do
    helper_method :current_admin

    before_action :authenticate_admin!
  end
end

Trestle::ApplicationController.send(:include, TrestleDeviseAuth)
```

If you already have got a rails app, maybe this will help you.

**Comment by spohlenz** [comment]
I've now added support for global callbacks `before_action`, `after_action` and `around_action` which make adding HTTP Basic Auth very easy. I've added a page on the wiki about how to do so here: https://github.com/TrestleAdmin/trestle/wiki/Authentication#http-basic-authentication.

**Comment by seanarnold** [comment]
Awesome! Any chance of this getting released in the next day or two? <3 @spohlenz

**Comment by spohlenz** [comment]
Just pushed `v0.8.3` to rubygems.org which includes these updates.
