### ISSUE TITLE
ArgumentError: bad argument (expected URI object or URI string) when calling DELETE

### ISSUE THREAD

**Issue by cjhutchi** [TrestleAdmin/trestle#514]
Didn't see this documented anywhere, and just wanted to raise this for visibility in case anyone is upgrading from `0.9.x` to `0.10.x` and is running into this error.

[There was some logic added to the `destroy` method in the `0.10.0` release](https://github.com/TrestleAdmin/trestle/compare/v0.9.9...v0.10.0#diff-60839b455174b94c6562f4cd92ae3dbd23d9991fe9115bdd739535d85d3aacd1R111) that uses the referrer on the request to add a turbo stream response when a resource is deleted. If you don't include a referrer on the request, you'll get the `ArgumentError: bad argument (expected URI object or URI string)` error because it will try to make a `URI` object out of `nil`.

If you have any calls to `delete` on a resource (I experienced it in a unit test), you now need to include a referrer in the headers of that call, e.g.:

```
delete Post.instance_path(post),
            headers: {
              HTTP_REFERER: Article.instance_path(article)
            }
```

**Comment by spohlenz** [comment]
Thank you for reporting this. This should now be fixed in #515.
