### ISSUE TITLE
Failed to show image thumbnail using url helper

### ISSUE THREAD

**Issue by 33218024** [TrestleAdmin/trestle#527]
I'm using trestleAdmin to create students menu to collect student's information. They have attribute photos and I use active storage to save it. I failed when trying to show image thumbnail using image_tag and url_for. Is there any way I could make it correctly? Thanks for any helps.

![image](https://github.com/user-attachments/assets/a0fe4749-bad4-4545-be2d-ab5266514f42)

**Comment by spohlenz** [comment]
I believe you'll need to use `main_app.url_for(...)` when rendering ActiveStorage attachments, though it's possible there might be other workarounds available.

**Comment by 33218024** [comment]
It works! Thank you very much.
