### ISSUE TITLE
disable row clickability

### ISSUE THREAD

**Issue by okliv** [TrestleAdmin/trestle#53]
is it possible to disable full row clickability on index view?

i have implemented custom tooltips on click and i need to show only tooltip instead of redirect to show\edit view

thanks

**Comment by spohlenz** [comment]
The automatic row linking can be disabled by removing the `data-url` which can be done via:

```ruby
table do
  row data: { url: nil }
  # columns...
end
```

**Comment by okliv** [comment]
looks tricky... maybe `table(row_url: false) do` will be more harmonious with current DSL?

**Comment by spohlenz** [comment]
I've now added `table(autolink: false)` as a cleaner way to disable the automatic `data-url` attributes.
