### ISSUE TITLE
Why is bower_components on git?

### ISSUE THREAD

**Issue by danieltdt** [TrestleAdmin/trestle#54]
Hi,
I've started using Trestle recently for my rails apps and it is awesome! The code is clean and easy to read and extend.
Also, I liked the way you manage assets with a rails engine (I'm following this style for my engines now), but I am a bit confused about `vendor/assets/bower_components` folder: why is this folder on git? This is not a dependency folder (just like .bundle folder) and shouldn't be ignored by git?

**Comment by spohlenz** [comment]
I think there's two schools of thought on this, and neither are necessarily wrong. I'm open to either way but have chosen to check it in for simplicity.

For me, the main advantage to checking it in is that it removes the extra `bower install` step that would be needed when checking out the project to begin working on.
