### ISSUE TITLE
Custom field example

### ISSUE THREAD

**Issue by joeczucha** [TrestleAdmin/trestle#59]
Apologies - this isn't really an issue but I wasn't sure where else to ask.

I see that, in the Trestle config, you can define custom field types. However, I'm not really sure how this works. 

    class CustomFormField
      def initialize(builder, template, name, options={}, &block)
        
      end
      def render

      end
    end

Would it be possible to provide a simple example (say, if I wanted to override the email_field to include an email icon, similar to the datetime_field)

Thanks :)

**Comment by spohlenz** [comment]
There are a couple of ways to write a custom form field type depending on how much control you need.

The lowest-level way, as alluded to by the comments in the Trestle config, is to write a plain Ruby object conforming to the provided interface. e.g.

```ruby
class BasicField
  def initialize(builder, template, name, options={}, &block)
    @builder, @template, @name, @options, @block = builder, template, name, options, block
  end

  def render
    @template.content_tag(:div, class: "well") do
      @builder.raw_text_field(@name, @options.merge(class: "form-control"))
    end
  end
end
```

If you want to create a fairly standard field that is wrapped with a `form-group` div and includes a label and automated error messages, you will likely find it easier to inherit from `Trestle::Form::Field` and override the `field` method. e.g.

```ruby
class InheritedField < Trestle::Form::Field
  def field
    template.content_tag(:div, class: "well") do
      builder.raw_text_field(name, options.merge(class: "form-control"))
    end
  end
end
```

The simplest way to achieve your given example is to pass the `:prepend` option to the `email_field` helper. e.g.

```ruby
email_field :email, prepend: icon("fa fa-envelope-o")
```

You can check out the built-in field types in https://github.com/TrestleAdmin/trestle/tree/master/lib/trestle/form/fields if you wish to dive deeper.
