### ISSUE TITLE
Shouldn't permitted_params run controller context?

### ISSUE THREAD

**Issue by danieltdt** [TrestleAdmin/trestle#60]
Why permitted_params runs on adapter context? From the context of a model, all parameters is always permitted, the validation of params only have meaning if running on controller context (thats why protected_attributes/strong_parameters gems moved from active_record to action_controller).
In the current codebase, it's impossible to validate params base on current user, for example:

```rb
# app/admin/users_admin.rb
params do |params|
  if current_user.admin?
    [:all, :user, :attrs, :is, :permitted]
  elsif current_user.id == instance.id
    [:password, :password_confirmation]
  else
    []
  end
end
```

The code above rises an error because it is an "instance_exec" on Admin class and doesn't have access to `current_user` neither `instance`.

**Comment by spohlenz** [comment]
You are correct. The controller context is a definitely a better choice for the `permitted_params` block to execute in. I have updated this in 2af4dd3.
