### ISSUE TITLE
How do I set the order of sidebar's categories?

### ISSUE THREAD

**Issue by zippax** [TrestleAdmin/trestle#61]

**Comment by slenderock** [comment]
I see posibility to set :first and :last in group only..
```
menu do
  item :resourses, icon: 'fa fa-star', group: :resourses_group, priority: :first
end
```

**Comment by spohlenz** [comment]
You can use the long form of the menu block to set the group priority:

```ruby
menu do
  group :group_name, priority: :last do
    item :resource, icon: "fa fa-star", priority: :first
  end
end
```

The `:priority` option also accepts an integer for finer tuned ordering.

**Comment by zippax** [comment]
it will be good if we can set each item's order, set priority not helpful for large tree
