### ISSUE TITLE
how to show me the table where column :active = 1

### ISSUE THREAD

**Issue by zippax** [TrestleAdmin/trestle#62]

**Comment by slenderock** [comment]
U can use scope for it :
  ```
  scope(:all, default: true) { Plan.order(id: :desc) }

  scope :completed, -> { Plan.completed }
  scope :current,   -> { Plan.current }
  scope :deleted,   -> { Plan.only_deleted }
```

**Comment by spohlenz** [comment]
Thank you @slenderock. Excellent example.

The only thing I would add, is that if you only ever want to show the active instances and don't need the alternative scopes, you can override the collection block instead:

```ruby
collection do
  Plan.active
end
```
