### ISSUE TITLE
fetch column parent :name instead of :parent_id

### ISSUE THREAD

**Issue by zippax** [TrestleAdmin/trestle#63]
````
table do
    column :name
    column :parent_id
    actions
end
````

the second column will show the id. I want to show parent name instead of the id.

**Comment by slenderock** [comment]
Try this:
```
column :parent, ->(parent) { parent.name }
or 
column :parent, &:name
```

**Comment by zippax** [comment]
Hi @slenderock this will show me the current child name, I need to show the parent name

**Comment by slenderock** [comment]
Hello, @zippax 
Sorry for that. I make little typo
```
column :parent, ->(current_record) { current_record.parent&.name }
```
I guess "&" is required to prevent errors when parent doesn't exist for this record.

**Comment by zippax** [comment]
Error
`undefined method `parent'`

**Comment by slenderock** [comment]
**undefined method 'parent'**

for what class ?

**Comment by zippax** [comment]
```
ActionView::Template::Error at /categories
undefined method `name' for 1:Fixnum
```

**Comment by slenderock** [comment]
You should use active_record object(not id)  to get access to method #name 
So you need to change back #parent_id to #parent 

If you get "undefined method 'parent'" you probably forgot to set belongs_to association in your model.
Please check this out.
It will be great if u can share github link where this problem produses

Btw, I have this line of code in my project and it works fine:
```
column :user, ->(current_record) { current_record.user.full_name }
```

**Comment by zippax** [comment]
Actually the Category model have name and parent_id so there is no association between 2 models. both are in the same table

**Comment by zippax** [comment]
this is a Github repo https://github.com/zippax/cs

**Comment by slenderock** [comment]
Seems like you don't have parent model at all. So how you want to get parent name, if you don't have this relation?

**Comment by zippax** [comment]
so I have to make subCategory model and make association between it and the Category model

**Comment by slenderock** [comment]
You should have this code for subcategory 
```
has_many :subcategories, class_name: 'foreign_key: 'parent_id'
belongs_to :parent, class_name: 'Category', inverse_of: :subcategories, optional: true
```

**Comment by slenderock** [comment]
and then you can use:
```
column :parent, ->(category) { category.parent&.name }
```

**Comment by spohlenz** [comment]
As @slenderock mentions, having the associations in place are the key to getting this working.

One thing I would add is that in many cases, you can drop the custom block all together and just use:

```ruby
column :parent
```

This will automatically display the parent instance (if present) by finding a method from `Trestle.config.display_methods` that it responds to. This defaults to `[:display_name, :full_name, :name, :title, :username, :login, :email]` so you won't need to alter anything when using the `name` method.

It will also automatically link the name to a corresponding admin for the parent model, if it exists.
