### ISSUE TITLE
How to customize actions in header of index view?

### ISSUE THREAD

**Issue by patybastos** [TrestleAdmin/trestle#65]
Hi @spohlenz, is it possible to insert a button in the header next to the "new" button? I want to create a button to upload a file to import registers, but I didn't find a hook where I could do it.

**Comment by spohlenz** [comment]
Eventually I'd like to make this easier, but currently you'll need to override the index template (https://github.com/TrestleAdmin/trestle/blob/master/app/views/trestle/resource/index.html.erb) by creating a template that matches your resource name, e.g. `app/views/admin/{resource_name}/index.html.erb`.

You can add the new button next to the 'New Resource' button within the `content_for(:primary_toolbar)` block, or create a new `content_for(:secondary_toolbar)` block to add it as smaller button in the second row.
