### ISSUE TITLE
Sidekiq authentication using trestle

### ISSUE THREAD

**Issue by slenderock** [TrestleAdmin/trestle#68]
Can I somehow use sidekiq auth via trestle as well?

**Comment by okliv** [comment]
what is  sidekiq auth? look like question if far away from any trestle issues...

**Comment by slenderock** [comment]
https://github.com/mperham/sidekiq

I just want to make /sidekiq endpoint available for admin only.

**Comment by slenderock** [comment]
for now I did it with

lib/admin_constraint.rb
```
class AdminConstraint
  def matches?(request)
    return false unless request.session[:trestle_user]
    user = Administrator.find request.session[:trestle_user]
    user.present?
  end
end
```
routes.rb
```  
require 'admin_constraint'
mount Sidekiq::Web, at: '/sidekiq', constraints: AdminConstraint.new
```

But I am looking for more secure way.

**Comment by spohlenz** [comment]
That looks like it *should* be a reasonably secure approach. I gather that the overall pattern was sourced from the AuthLogic example [here](https://github.com/mperham/sidekiq/wiki/Monitoring#authlogic)? Are you seeing any ways that it can be bypassed?

I actually thought the Sidekiq web authentication was in the pro version only. Has that changed recently (or was I entirely mistaken)? If so, I wouldn't mind putting together a simple trestle-sidekiq plugin that embeds it within the dashboard (and eventually with a live status view somewhere within the header or sidebar!).

**Comment by slenderock** [comment]
You know, it may be really secure in production environment.
Recently I have tried to set :trestle_user key in session(as I did it in dev environment) but I can not as this key doesn't exist(I guess it is encrypted somehow).

Thanks everyone.

**Comment by spohlenz** [comment]
In response to this issue (and some free time this morning), I've implemented the following:

1) A [`Trestle::Auth::Constraint`](https://github.com/TrestleAdmin/trestle-auth/blob/master/lib/trestle/auth/constraint.rb) class, allowing you to protect custom routes within the admin. I would suggest using it like this:

```ruby
Trestle::Engine.routes.draw do
  mount Sidekiq::Web => "/sidekiq", constraints: Trestle::Auth::Constraint.new
  get "/sidekiq", to: redirect("login", status: 302)
end
```

2. A new (and currently very basic) [trestle-sidekiq plugin](https://github.com/TrestleAdmin/trestle-sidekiq) which handles the Sidekiq integration with Trestle and trestle-auth.
