### ISSUE TITLE
Reloading trestle resources at runtime issue (development environment)

### ISSUE THREAD

**Issue by okliv** [TrestleAdmin/trestle#69]
I have some trestle classes defined dynamically. i'll try to keep it simple to explain, so here is simplified approach i use:

    #app/admin/my_gem/trestle_represented_models_admin.rb

    MyGem.trestle_represented_models.each do |klass|
      Trestle.resource(klass.trestle_resource_name, model: klass, scope: MyGem do
        table do
          klass.columns.each do |col|
            column col.sym_name
          end
        end
      end

in this example any of `MyGem.trestle_represented_models` are just `Sequel::Model` classes with some, mostly repeated, columns (like, `BlogPost` and `News`, for example)

And now, if i change something inside `BlogPost` sequel model file (which i defined inside my_gem) and then try to refresh it's trestle's index page, for example (like /admin/my_gem/blog_posts) i randomly eventually receive this error:

    uninitialized constant MyGem::BlogPostsAdmin

During a quick digging inside trestle's code i found this method `Trestle::Engine.reloader.updater.execute`. 
I call it over a rails developer console every time i want to remove that error.

It helps me sometimes to (?renew Trestle classes in memory with changes i made for represented model?), but this trick can be done only once... than i need to restart the app

Any suggestions or leading questions why\how it can be done without app restart every time i change my sequel model classes? (Hope this is relevant enough question to ask it here)

**Comment by spohlenz** [comment]
Reloading issues are always a bit tricky, as `ActiveSupport::Dependencies` can try to be a bit too clever sometimes.

A couple questions that might help:

1) Are you using spring at all? If so, does it work if spring is disabled?

2) How is `MyGem.trestle_represented_models` computing the list of classes? Are they hard-coded, or inferred dynamically? Is there any caching involved within that method? One thing I can think of that might be worth a try is to return a list of class names as strings, and then call `#constantize` on these to get the actual model.

**Comment by okliv** [comment]
1. I always disable spring. it can make me stuck for a minutes not refreshing what it has to, so that couple springed seconds is not really the goal

2. that classes names persist in a db table `entitites` (as well as corresponding model files exist in `models/my_gem` folder inside my gem) and then i do `safe_constantize`:

```ruby
Entity.adminable.each do |entity|
       Trestle.resource(entity.trestle_resource_name, model: entity.name.safe_constantize, scope: MyGem do
```

**Comment by spohlenz** [comment]
Hi @okliv. Sorry for the massive delay in getting back onto this one. I just wanted to let you know that I have been able to reliably reproduce it now, so hopefully I'll be able to find a fix soon.

**Comment by spohlenz** [comment]
In dc09740, I've added a new config option `Trestle.config.reload` which can be used to always reload Trestle admins every time `to_prepare` is called (rather than just when file changes within `app/admin` are detected).

Note that this won't necessarily help you if you are modifying entities whilst running in production. If this is the case, you may need to add some code to call `Trestle::Engine.reloader.execute` across all your app servers when changes are detected.

**Usage:**

```ruby
config.reload = :always # Default is :on_update
```

**Comment by svoboda-jan** [comment]
I can reproduce the same error (uninitialized constant) in `0.8.7` even using the normal way to define resources in `app/admin`. I get the error any time I change any locale file and then reload the page in browser.

**Comment by svoboda-jan** [comment]
Another way to reproduce the uninitialized constant error:

```ruby
form do
  text_field :name
end

# in the model file (app/models)
# add after the application is started
def name
  raise
end
```

Instead of throwing the expected exception, this shows the `uninitialized constant` error, even if the `raise` is removed, so the application needs to be restarted.
