### ISSUE TITLE
Pagination: How can i add pagination on listing?

### ISSUE THREAD

**Issue by kenzo2013** [TrestleAdmin/trestle#72]

**Comment by spohlenz** [comment]
The index view should already be paginated. You can customize the number of records shown per page by adding `paginates_per 20` to your model. I am also currently working on a way to customize the per-page value within the admin itself.

Pagination on custom tables rendered within a form isn't currently supported but my intention is to support this sometime in the future (when I do a proper implementation of sub-resources).

**Comment by kenzo2013** [comment]
Oh Great. Work's well. 

And also great you for this gem. Thank you
