### ISSUE TITLE
Select multiple with with data preload

### ISSUE THREAD

**Issue by kenzo2013** [TrestleAdmin/trestle#73]
How can i add select multiple field like this https://puu.sh/zm767/6513996548.png

**Comment by spohlenz** [comment]
Although, it is not precisely the same widget, you can create a multiple select field by passing `multiple: true` as the html options of a `select` field.

e.g.

```ruby
form do
  select :countries, Country.all, {}, multiple: true
end
```

Note that this should be the fourth parameter, not the third.

**Comment by njcameron** [comment]
Using this to pre-populate the already selected items 👇 

```
select :children, options_for_select(Children.all.map { |c [c.name, c.id] }, @parent.children.pluck(:id)), {}, multiple: true
```
