### ISSUE TITLE
Checkbox on Trestle table 

### ISSUE THREAD

**Issue by kenzo2013** [TrestleAdmin/trestle#74]
how can i add checkbox on Trestle table to select one row  (https://puu.sh/zm7LN/25eeceb4aa.png)or all rows at the same time (https://puu.sh/zm7NG/74553bc2ff.png). 

This will be useful for export feature

**Comment by spohlenz** [comment]
You can add a checkbox column by calling `selectable_column` within a table block.

e.g.

```
table do
  selectable_column
  column :email
  column :created_at
  actions
end
```

Note however that this feature is not 100% complete yet. In particular, you will currently have to write some JavaScript to handle the select all checkbox in the table header, as well as code to pass the selected values to your export action.

**Comment by okliv** [comment]
is there any milestones for full `selectable_column` collection actions functionality? thanks

**Comment by shenhf** [comment]
`selectable_column` raised error:
```
undefined method `options' for #<Trestle::Table::SelectColumn:0x00007fc4d5051788>
```
