### ISSUE TITLE
Edit image

### ISSUE THREAD

**Issue by kenzo2013** [TrestleAdmin/trestle#76]
When i upload image is going well but when i want to edit it how can i display image with button delete like this https://puu.sh/zmNfP/a0ba3444f0.png?

**Comment by spohlenz** [comment]
How you implement the delete button will depend on which file integration plugin you are using (e.g. ActiveStorage, Shrine, etc). However you may find my comment [here](https://github.com/TrestleAdmin/trestle/issues/77#issuecomment-365891209) helpful.

**Comment by kenzo2013** [comment]
I test it but i have error like so https://puu.sh/zofBY/0c14fb5382.png
--

**Comment by spohlenz** [comment]
You might need to add `.present?` or similar to the end of `if instance.profile_picture`, although this will depend on what gem you are using.
