### ISSUE TITLE
Displaying the image in the edit method

### ISSUE THREAD

**Issue by X-tymchenko** [TrestleAdmin/trestle#77]
How i can show image that has already been loaded into the record?
![edit image](https://user-images.githubusercontent.com/16686943/36230024-cb3ee060-11e1-11e8-995c-1873271eed44.png)

**Comment by spohlenz** [comment]
Something like this within your form block should do the trick:

```ruby
form do |instance|
  form_group :image, help: "Upload a file less than 2MB." do
    concat image_tag(instance.image.url) if instance.image
    raw_file_field :image
  end
end
```

**Comment by kenzo2013** [comment]
I test it but i have error like so https://puu.sh/zofBY/0c14fb5382.png

**Comment by thanhhai45** [comment]
> ```ruby
> form do |instance|
>   form_group :image, help: "Upload a file less than 2MB." do
>     concat image_tag(instance.image.url) if instance.image
>     raw_file_field :image
>   end
> end
> ```

thanks you, but if image I use active storage then it not work. You suggest for this problem

**Comment by madaarya** [comment]
```ruby
form_group :header_image, help: "Cover image for property" do
     concat image_tag(Rails.application.routes.url_helpers.url_for(instance.header_image)) if instance.header_image.attached?
     file_field :header_image
end
```

Just in case someone need example help with active storage :)
