### ISSUE TITLE
How can i add some id on the table

### ISSUE THREAD

**Issue by kenzo2013** [TrestleAdmin/trestle#78]

**Comment by kenzo2013** [comment]
I'm working with datatable. But i can't some id to handle it.

**Comment by spohlenz** [comment]
The table ID can't currently be set (although I should definitely enable this).

You can however set the class or data attributes by specifying them as options to the table.

e.g.
```ruby
table class: "mytable", data: { behavior: "datatable" } do
  ...
end
```

Datatable will hopefully let you initialize a table using one of these rather than the ID.

**Comment by kenzo2013** [comment]
Oh cool works fine. Thank you

**Comment by spohlenz** [comment]
In 6604860, you can now set a custom table id as an option if desired.
