### ISSUE TITLE
Custom create action controller: Relation has_and_belongs_to_many

### ISSUE THREAD

**Issue by kenzo2013** [TrestleAdmin/trestle#79]
How can i custom create action when i have has_and_belongs_to_many?
i try something like this
controller do
    def create
      params[:brand][:users].delete_if{|el| el==""}.each do |email|
        instance.users << User.find_by(email: email)
      end
    end
  end

But don't works

**Comment by spohlenz** [comment]
You can override the `build_instance` block to add custom creation behaviour:

e.g.

```ruby
build_instance do |attrs, params|
  model.new(attrs) do |instance|
    instance.users << ...
  end
end
```

However you may want to simply create a `users=` method on your model that would look like:

```ruby
def users=(emails)
  users = emails.reject(&:blank?).map { |email| User.find_by(email: email) }
  super(users)
end
```
