### ISSUE TITLE
How do I override the default breadcrumbs?

### ISSUE THREAD

**Issue by X-tymchenko** [TrestleAdmin/trestle#81]
I want add new hierarchy. Now it looks like this
![image](https://user-images.githubusercontent.com/16686943/36341394-3cddd8c8-13f6-11e8-8742-ec98121f8dd5.png)
But i want what's been like here.
![image](https://user-images.githubusercontent.com/16686943/36341398-4770d394-13f6-11e8-8b0d-a6cd36ac35fa.png)
How can I do this?

**Comment by spohlenz** [comment]
The default breadcrumbs in Trestle have this format:

```
Root Breadcrumb(s) / Current Admin / Current Action
```

If you wish to globally change the Root Breadcrumbs, you can edit your `config/initializers/trestle.rb` and add:

```ruby
config.root_breadcrumbs = -> {
  [Trestle::Breadcrumb.new("label", "/path"), Trestle::Breadcrumb.new("label", "/path"), ...]
}
```

Within an admin, you can customize the Current Admin breadcrumb using:

```ruby
Trestle.resource(...) do
  breadcrumb "label", "/path"
end
```

where the path parameter is optional.

If you want further control of the breadcrumbs within an admin, you can override the `breadcrumbs` method:

```ruby
Trestle.resource(...) do
  admin do
    def breadcrumbs
      Trestle::Breadcrumb::Trail.new([
        Trestle::Breadcrumb.new("Label", "/path1"),
        Trestle::Breadcrumb.new("Label", "/path2")
      ])
    end
  end
end
```

To override the Custom Action breadcrumb, you will need to customize the `show.html.erb` template for your admin. Within the template, you can add calls to the `breadcrumb(label, path)` helper to append additional breadcrumbs.
