### ISSUE TITLE
Link column goes to 'edit' page, not the link

### ISSUE THREAD

**Issue by coletivo** [TrestleAdmin/trestle#83]
I have a link column in my admin view, that I was hoping would open to the outside link.

However, when I click on it, it goes to the `edit` page for that row.

Side note, i'd also love the ability to have a `target="_blank"` attribute so the link would open in a new tab.

**Comment by spohlenz** [comment]
In order to customize the link URL and target, you'll need to build the link manually. e.g.

```ruby
table do
  column :url do |site|
    link_to site.name, site.url, target: "_blank"
  end
end
```

You can also override the row attributes if you want the whole row to link to the external URL (although it's not currently possibly to specify a target). e.g.

```ruby
table do
  row do |site|
    { data: { url: site.url } }
  end
end
```

**Comment by coletivo** [comment]
👍 Thank you for the help and quick response!
