### ISSUE TITLE
have error with `instance` after update trestle

### ISSUE THREAD

**Issue by X-tymchenko** [TrestleAdmin/trestle#84]
```
<% if instance %>
  <ol class="breadcrumb">
    <% if instance.new_record? %>
      <li class="breadcrumb-item" aria-current="page">
        <%= link_to "Home", projects_admin_index_path %>
      </li>
    <% else %>
      <li class="breadcrumb-item" aria-current="page">
        <%= link_to "Home", projects_admin_index_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to instance.name, projects_admin_path(instance.id) %>
      </li>
    <% end %>
  </ol>
<% end %>
```
in v'0.8.6' all work fine. 
but after update i have this error
![image](https://user-images.githubusercontent.com/16686943/36502557-fe0094aa-1752-11e8-9f8d-1a10ac9d72c8.png)

**Comment by spohlenz** [comment]
In the latest release, I changed the `instance` and `collection` variables to be lazily loaded. However I am thinking of reverting this as it can cause issues as you have found, and may not be worth the slight advantage that it brings.

In the mean time, you can change `instance` to `@instance` which will check if the instance has been loaded.

**Comment by spohlenz** [comment]
The original behavior has now been restored in 776438e.
