### ISSUE TITLE
tag_select adding blank entries when using jsonb array

### ISSUE THREAD

**Issue by kevinelliott** [TrestleAdmin/trestle#85]
The `tag_select` form field, when used with a model attribute backed by a JSONB array, is adding blank items upon every save.

`form` block looks like:

```ruby
form do |thing|
  tag_select :terms
  tag_select :blacklist
end
```

And here is the result of this:

<img width="1040" alt="screen shot 2018-02-22 at 7 51 59 am" src="https://user-images.githubusercontent.com/123112/36548551-746961ce-17a5-11e8-8e98-44f541de6865.png">

The value in the model instance (after save multiple times is):

```
[2] pry(main)> c.terms
=> ["",
 "",
 "",
 "",
 "",
 "",
 "request",
 "please",
 "remind me",
 "help me understand",
 "can you please",
 "may I",
 "can I",
 "could I",
 "would you",
 "can you",
 "do you mind",
 "if you don't mind",
 "asd"]
```

Any way to prevent these blank/incorrect items? If not, this may be a bug.

**Comment by spohlenz** [comment]
The blank items are a Rails 'gotcha' when using multiple selects, checkboxes, etc. See http://api.rubyonrails.org/v5.1/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-select-label-Gotcha.

What I usually do is add a method such as this to my model:

```ruby
def tags=(tags)
  super(tags.reject(&:blank?).uniq)
end
```

I am considering adding support for doing this in a form object as described in https://github.com/TrestleAdmin/trestle/issues/18#issuecomment-367568754.

**Comment by kevinelliott** [comment]
Ah ha, interesting, I haven't stumbled on that before. Thanks for pointing me to it.

I'll go ahead and override the setter like you suggested. If you do add support in the form object later that would be great.

**Comment by kevinelliott** [comment]
I took it a step further and wrapped `tags` with `Array.wrap()` just in case something somewhere tries to set it `nil` or some other value.
