### ISSUE TITLE
Trestle.io demo site

### ISSUE THREAD

**Issue by stevenbank** [TrestleAdmin/trestle#90]
Trestle.io is awesome, but it really lacks a documentation. I'm trying to implement your demo site with Articles & Posts resources, where can I find the demo source to let me better understand the usage of Trestle DSL?

**Comment by spohlenz** [comment]
You are absolutely right that Trestle really needs a demo and documentation. Both are in progress, although client work unfortunately has pushed them far later than I had intended.

I'll see what I can put together by way of a demo in the short term though, even if it lacks polish. It can always be improved upon later.

**Comment by stevenbank** [comment]
Cool! can't wait 👍 

I found a similar UI admin framework which implement in Laravel, CoreUI, Bootstrap 4, VueJS
Sadly it using PHP, it would be awesome if it implement in Ruby!
https://github.com/BRACKETS-by-TRIAD/craftable
https://github.com/BRACKETS-by-TRIAD/admin-generator

CoreUI documentation is really resourceful
https://coreui.io/docs/getting-started/introduction/

**Comment by blimey85** [comment]
Any update on a demo? Some simple things are proving rather difficult to figure out. For example, before I customize anything, the id column is linked and sortable. I can't figure out how to accomplish that when I customize. I need to use link_to to get the link, and then I need to use sort, but not sure how to do that together. I also saw in some places it said to use admin_link_to but that didn't work.

**Comment by BobWalsh** [comment]
Or even a list of the possible field types for form?

**Comment by spohlenz** [comment]
Long overdue, but Trestle now has a demo application.

Admin: https://demo.trestle.io/admin (demo@example.com / demo)
Source: https://github.com/TrestleAdmin/RailsFlixDemo
