### ISSUE TITLE
How to include Globalize gem translation fields on one model?

### ISSUE THREAD

**Issue by pmaojo** [TrestleAdmin/trestle#98]
Is this possible like rails_admin has globalize field tabs?

**Comment by spohlenz** [comment]
There currently isn't anything built-in to accomplish this. However it should be possible to assemble something using a combination of fields_for and form tabs.

**Comment by pmaojo** [comment]
thankyou

**Comment by diazweb** [comment]
Hey guys, is possible to use Trestle with Globalize.

You just need to use this gem: https://github.com/globalize/globalize-accessors

Model:

    translates :title, :description
    globalize_accessors locales: I18n.available_locales, attributes: %i[title description]

Admin file:

    form do |brand|
      text_field :title_en
      text_field :title_de
      text_field :description_en
      text_field :description_de
    end
